import type { Pipeline, PipelineSceneReport } from './data';
import type { PipelineModule } from './pipeline-modules';
import type { PublicationVenue } from './publication-venues';

// Primary-source-audited expansion: graphics-to-physics systems, direct
// real2sim pipelines, and historical RSS roots that predate neural rendering.
export const expansionPipelines: Pipeline[] = [
  { name:'SIM1', takeaway:'Behaviorally calibrated cloth simulation turns a small demonstration set into scalable robot training data.', year:2026, date:'Apr 2026', domain:'Robotics', input:'Garment scans + robot URDF + 200 teleoperated simulation demonstrations', representation:'Textured meshes + rigid robot + deformable cloth state', output:'Synthetic demonstrations and real-robot folding policies', simulator:'Newton / AVBD cloth solver + Blender Cycles', embodiments:'ARX ACONE dual-arm robot; ARX X5 teleoperation', summary:'Real-to-sim-to-real garment pipeline combining scene digitization, expert dynamics calibration, diffusion trajectory synthesis, filtering, and randomized rendering.', metric:'T-shirt folding: reported 90% zero-shot success; 30 trials per configuration; about 15 synthetic demos match one real demo', stages:['Geometry','Appearance','Physics','Policy'], topics:['Physical simulation'], open:'Open', paper:'https://arxiv.org/abs/2604.08544', code:'https://github.com/InternRobotics/SIM1', project:'https://internrobotics.github.io/sim1.github.io/', caveat:'Professional scanning and manual cleanup; experts tune behavior rather than recover true physical parameters. Real validation centers on T-shirt folding. Material, lighting and camera randomization are not inverse rendering.' },
  { name:'nvdiffrec', takeaway:'Joint image fitting produces an explicit mesh with editable materials and lighting.', year:2022, date:'Jun 2022', domain:'Graphics', input:'Multi-view images with camera poses and object masks', representation:'Triangle mesh + spatially varying materials + environment lighting', output:'Relightable textured mesh', simulator:'Differentiable rasterization with nvdiffrast; no dynamics engine', embodiments:'No robot deployment', summary:'Inverse rendering jointly optimizes geometry, optical materials and illumination for conventional graphics workflows.', metric:'NeRF synthetic and NeRD reconstruction evaluations; no robot-transfer benchmark', stages:['Geometry','Appearance'], topics:['Inverse rendering','Relighting'], open:'Open', paper:'https://nvlabs.github.io/nvdiffrec/', code:'https://github.com/NVlabs/nvdiffrec', project:'https://nvlabs.github.io/nvdiffrec/', caveat:'Per-object optimization; optical material recovery does not estimate mass, friction or stiffness. Simulator collision and dynamics setup remain separate.' },
  { name:'IRIS', takeaway:'Camera response estimation makes ordinary LDR captures useful for HDR material and lighting recovery.', year:2024, date:'Jan 2024', domain:'Graphics', input:'Posed multi-view LDR indoor images and scene geometry', representation:'Scene surface + BRDF + spatial HDR lighting + camera response', output:'Relightable indoor scene and consistent virtual object insertion', simulator:'Inverse path tracing / shading optimization; no dynamics engine', embodiments:'No robot deployment', summary:'Inverse rendering estimates optical materials, emitters and camera response for indoor relighting from LDR captures.', metric:'Real indoor scenes and synthetic FIPT comparisons; material, lighting and rerendering evaluation', stages:['Appearance'], topics:['Inverse rendering','Relighting'], open:'Open', paper:'https://arxiv.org/abs/2401.12977', code:'https://github.com/facebookresearch/iris', project:'https://irisldr.github.io/', caveat:'Uses scene geometry; appearance reconstruction is not mechanical system identification. No robot transfer or collision-ready asset validation.' },
  { name:'GIR', takeaway:'Gaussian scene factorization separates geometry, reflectance and illumination for editable relighting.', year:2023, date:'Dec 2023', domain:'Graphics', input:'Multi-view object images', representation:'3D Gaussians + regularized normals + material and illumination fields', output:'Relightable Gaussian scene', simulator:'Gaussian inverse renderer with indirect illumination approximation; no dynamics engine', embodiments:'No robot deployment', summary:'Inverse rendering recovers Gaussian geometry and optical materials with normal regularization and indirect illumination modeling.', metric:'Novel-view, material and relighting comparisons on inverse-rendering datasets', stages:['Geometry','Appearance'], topics:['Inverse rendering','Relighting'], open:'Open', paper:'https://arxiv.org/abs/2312.05133', code:'https://github.com/guduxiaolang/GIR', project:'https://3dgir.github.io/', caveat:'Per-scene fitting; no mechanical parameter recovery, collision representation or demonstrated robot policy transfer.' },

  { name:'Real2Sim · Approximate State', takeaway:"Coarse object and hand primitives can recover enough physical task state from video to supervise manipulation through dense rewards.", year:2020, date:'Nov 2020', domain:'Robotics', input:'1–6 third-person RGB videos per action', representation:'Cylinder hand + cuboid objects + recovered camera and 3D trajectories', output:'Aligned demonstrations and an RL manipulation policy', simulator:'PyPhysX + neural inverse-graphics renderer', embodiments:'Robot arm / gripper via Cartesian trajectory and numerical IK; SKU not prominently disclosed', summary:'Early end-to-end real-video-to-simulation-to-robot method that optimizes coarse perceptual and physical state, then uses the recovered motion as dense RL reward.', metric:'54 videos / 9 actions; selected easy-setting success 93–99%; 1,000 sampled evaluation starts', stages:['Geometry','Physics','Retargeting','Policy'], open:'Open', paper:'https://arxiv.org/abs/2011.06813', code:'https://github.com/makarandtapaswi/Real2Sim_CoRL2020', project:'https://data.ciirc.cvut.cz/public/projects/2020Real2Sim/', caveat:'Geometry is deliberately approximate; fixed-camera segmentation and contact detection dominate failure.' },
  { name:'DiSECt', takeaway:"Differentiable cutting mechanics make force traces informative for material calibration and trajectory optimization through topology changes.", year:2021, date:'Jul 2021', domain:'Cross-domain', input:'Known mesh, knife trajectory, and simulated or real cutting-force measurements', representation:'Differentiable FEM soft body + SDF contact + damage springs', output:'Calibrated cutting simulator and force-minimizing slicing trajectory', simulator:'Purpose-built differentiable FEM cutting engine', embodiments:'Robot arm with slicing knife', summary:'A historical differentiable real2sim system-identification pipeline for contact-rich cutting and topology change.', metric:'Hundreds of parameters calibrated; optimized slicing lowers average force by >40%; aggregate trial count unreported', stages:['Physics','Policy'], open:'Open', paper:'https://www.roboticsproceedings.org/rss17/p067.pdf', code:'https://github.com/NVlabs/DiSECt', project:'https://diff-cutting-sim.github.io/', caveat:'Requires known meshed geometry and force measurements; it is not an RGB reconstruction pipeline.' },
  { name:'Ditto', takeaway:"One observed state change constrains movable-part geometry and joint structure enough to instantiate an articulated object model.", year:2022, date:'Jun 2022', domain:'Cross-domain', input:'Point clouds before and after one physical interaction', representation:'Implicit occupancy + movable-part segmentation + revolute/prismatic joint parameters', output:'Explicit part meshes and a simulator-importable articulated model', simulator:'robosuite', embodiments:'Franka Panda + Intel RealSense D435i', summary:'Reconstructs category-agnostic geometry and articulation from one observed state change, then instantiates the result for robot interaction.', metric:'Shape2Motion whole/mobile Chamfer-L1 ×1000 .72/.42; revolute angle/position error 1.36/.02', stages:['Geometry','Physics'], open:'Open', paper:'https://openaccess.thecvf.com/content/CVPR2022/papers/Jiang_Ditto_Building_Digital_Twins_of_Articulated_Objects_From_Interaction_CVPR_2022_paper.pdf', code:'https://github.com/UT-Austin-RPL/Ditto', project:'https://ut-austin-rpl.github.io/Ditto/', caveat:'Recovers articulation, not mass, friction, compliance, or deformable dynamics.' },
  { name:'Approximate Differentiable Physics', takeaway:"Approximate differentiable dynamics constrain video-recovered motion enough to support direct robot execution without an intervening learned policy.", year:2022, date:'Oct 2022', domain:'Robotics', input:'One RGB manipulation video with masks and contact detections', representation:'Coarse hand/object state optimized through differentiable ODE dynamics', output:'Physically admissible object trajectory transferred directly to a robot', simulator:'TorchDiffEq dynamics + PyPhysX visualization', embodiments:'Franka Emika Panda', summary:'Replaces the earlier Real2Sim policy-learning stage with approximate differentiable physics and direct trajectory execution.', metric:'54 videos / 9 actions; nearly 30% reconstruction improvement; conversion time unreported', stages:['Geometry','Physics','Retargeting'], open:'Open', paper:'https://arxiv.org/abs/2208.01960', code:'https://github.com/petrikvladimir/video_skills_learning_with_approx_physics', project:'https://data.ciirc.cvut.cz/public/projects/2022Real2SimPhysics/', caveat:'Uses coarse primitives and simple single-/two-object tabletop actions.' },
  { name:'NeuPhysics', topics:['Physical simulation'], takeaway:"Converting between neural fields and hexahedral meshes couples monocular reconstruction to editable explicit simulation.", year:2022, date:'Nov 2022', domain:'Graphics', input:'One monocular consumer-camera RGB video', representation:'Neural SDF/appearance/rigidity fields + deformation field + hexahedral mesh', output:'Dynamic mesh sequence, inferred parameters, and editable simulation', simulator:'Differentiable mesh simulator using NVIDIA Warp', embodiments:'No robot deployment', summary:'Bridges monocular neural-field reconstruction and explicit simulation through two-way neural-field-to-hexahedron conversion.', metric:'Reconstruction and editing evaluated on synthetic and consumer videos; aggregate scene success and throughput unreported', stages:['Geometry','Appearance','Physics'], open:'Open', paper:'https://proceedings.neurips.cc/paper_files/paper/2022/file/53d3f45797970d323bd8a0d379c525aa-Paper-Conference.pdf', code:'https://github.com/gaoalexander/neuphysics', project:'https://arxiv.org/abs/2210.12352', caveat:'Per-scene optimization and monocular ambiguity; no robot policy or sim-to-real test.' },
  { name:'PAC-NeRF', topics:['Physical simulation'], takeaway:"Advecting a neural appearance field with material particles lets multiview video jointly constrain geometry and continuum physics.", year:2023, date:'May 2023', domain:'Graphics', input:'Calibrated multiview videos of moving or deforming material', representation:'Eulerian voxel NeRF advected by Lagrangian particles', output:'Geometry, appearance, constitutive parameters, and forward-simulatable state', simulator:'Differentiable Taichi MLS-MPM', embodiments:'No robot deployment', summary:'Jointly identifies neural appearance and continuum physics for elastic, plasticine, sand, Newtonian, and non-Newtonian materials.', metric:'9 synthetic identification instances, normally 11 views each; parameter and novel-view metrics reported per material', stages:['Geometry','Appearance','Physics'], open:'Open', paper:'https://openreview.net/pdf?id=tVkrbkz42vc', code:'https://github.com/xuan-li/PAC-NeRF', project:'https://xuan-li.github.io/PAC-NeRF/', caveat:'Heavy per-scene optimization, calibrated cameras, and a known material-family choice.' },
  { name:'ACDC Digital Cousins', takeaway:"Affordance-equivalent scene diversity can improve policy transfer even when individual assets are imperfect replicas of the captured objects.", year:2024, date:'Nov 2024', domain:'Cross-domain', input:'One RGB scene image', representation:'Object-centric point clouds aligned to retrieved BEHAVIOR assets', output:'Interactive digital-cousin scene ensembles and a manipulation policy', simulator:'OmniGibson / BEHAVIOR', embodiments:'Real kitchen manipulation arm; exact SKU not clearly disclosed', summary:'Builds affordance-equivalent cousins rather than an exact twin and uses their diversity to improve zero-shot policy robustness.', metric:'5 real kitchens / 3 tasks; 10k, 10k, and 2k demonstrations; 90% cousin-trained versus 25% twin-trained real success', stages:['Geometry','Appearance','Physics','Policy'], open:'Open', paper:'https://proceedings.mlr.press/v270/dai25a.html', code:'https://github.com/cremebrule/digital-cousins', project:'https://digital-cousins.github.io/', caveat:'Instance fidelity is bounded by asset-library coverage, monocular depth, and object masks; GPT API dependent.' },
  { name:'URDFormer', takeaway:"Synthetic image–URDF supervision makes articulation prediction feed-forward, with geometric fidelity bounded by the predefined asset vocabulary.", year:2024, date:'Jul 2024', domain:'Cross-domain', input:'One internet or phone RGB image plus detected part/object boxes', representation:'URDF primitives with mesh type, scale, pose, parent, and joint structure', output:'Interactive articulated object or kitchen scene', simulator:'PyBullet · Reality Gym', embodiments:'UR5 tabletop arm and Stretch mobile manipulator', summary:'Trains image-to-URDF prediction from diffusion-augmented paired synthetic data and deploys policies in inferred articulated worlds.', metric:'≈118k image–URDF pairs + ≈200k kitchens; 54 kitchen evaluation scenes; detector F1 +13%', stages:['Geometry','Appearance','Physics','Policy'], open:'Partial', paper:'https://www.roboticsproceedings.org/rss20/p124.pdf', code:'https://github.com/WEIRDLabUW/urdformer', project:'https://urdformer.github.io/', caveat:'Uses predefined meshes, does not identify mass/friction, and training-data generation remains incomplete.' },
  { name:'DiffTactile', takeaway:"Calibrating the sensor–object contact model exposes local mechanical behavior that RGB reconstruction leaves underconstrained.", year:2024, date:'May 2024', domain:'Robotics', input:'Real/sim tactile observations, sensor/object geometry, and trajectories', representation:'FEM elastomer + MLS-MPM/PBD objects + penalty contact + neural optical response', output:'Calibrated tactile simulator and optimized contact-rich skills', simulator:'Custom Taichi differentiable simulator', embodiments:'GelSight-like sensor + parallel-jaw gripper', summary:'Performs real2sim calibration at the tactile/contact layer where RGB-only reconstruction misses local mechanics.', metric:'4 contact-rich tasks plus stable/adaptive grasping; no unified throughput or aggregate scene count', stages:['Physics','Policy'], open:'Open', paper:'https://proceedings.iclr.cc/paper_files/paper/2024/file/1cc70be9fb6a83bc46cf4ac21a91e0b0-Paper-Conference.pdf', code:'https://github.com/Genesis-Embodied-AI/DiffTactile', project:'https://difftactile.github.io/', caveat:'Sensor-specific calibration and high computational cost; not a scene-geometry reconstruction system.' },
  { name:'PhysDreamer', topics:['Physical simulation'], takeaway:"Distilling generated motion into material parameters converts a video prior into an explicit simulator that responds to new forces.", year:2024, date:'Sep 2024', domain:'Graphics', input:'Static reconstructed 3DGS plus generated motion references', representation:'3D Gaussians with spatially varying material parameters', output:'Action-conditioned deformable dynamics under novel forces', simulator:'Differentiable MPM', embodiments:'Virtual interaction examples; no real robot', summary:'Distills a video-generation motion prior into explicit material parameters rather than using generated video as the final simulator.', metric:'8 gallery objects; human preference study; conversion throughput not clearly reported', stages:['Geometry','Appearance','Physics'], open:'Partial', paper:'https://physdreamer.github.io/papers/physdreamer_paper.pdf', code:'https://github.com/a1600012888/PhysDreamer', project:'https://physdreamer.github.io/', caveat:'Primarily elastic motion, strongly prior-dependent, and no measured real-robot transfer.' },
  { name:'PhysGaussian', topics:['Physical simulation'], takeaway:"Using Gaussians as both rendering primitives and material particles unifies appearance with simulation while leaving physical parameters externally specified.", year:2024, date:'Jun 2024', domain:'Graphics', input:'Pretrained 3D Gaussian scene plus assigned material and boundary parameters', representation:'Gaussians used as both rendering primitives and MPM particles', output:'Physics-integrated photoreal novel dynamics', simulator:'Custom GPU Material Point Method', embodiments:'No robot deployment', summary:'Influential “what you see is what you simulate” representation that avoids an explicit volumetric mesh.', metric:'Elastic, plastic, granular, Newtonian, and non-Newtonian examples; no standardized success/throughput benchmark', stages:['Geometry','Appearance','Physics'], open:'Open', paper:'https://openaccess.thecvf.com/content/CVPR2024/papers/Xie_PhysGaussian_Physics-Integrated_3D_Gaussians_for_Generative_Dynamics_CVPR_2024_paper.pdf', code:'https://github.com/XPandora/PhysGaussian', project:'https://xpandora.github.io/PhysGaussian/', caveat:'Does not infer physics; custom scenes need manual alignment, bounds, material assignment, and particle filling.' },
  { name:'Real2Code', takeaway:"Generating articulation programs makes part composition scalable, but executable joint code still requires independent validation of physical parameters.", year:2025, date:'Apr 2025', domain:'Cross-domain', input:'A handful of unposed multiview RGB images', representation:'Completed part meshes + oriented boxes + generated Python/MJCF articulation code', output:'Executable articulated object model', simulator:'MuJoCo-compatible MJCF', embodiments:'No downstream robot policy test', summary:'Uses language-model code generation to reconstruct articulated programs that scale beyond the part counts seen in training.', metric:'Objects up to 10 articulated parts; category Chamfer metrics reported; total real-object throughput unreported', stages:['Geometry','Physics'], open:'Open', paper:'https://proceedings.iclr.cc/paper_files/paper/2025/file/028fcbcf85435d39a40c4d61b42c99a4-Paper-Conference.pdf', code:'https://github.com/MandiZhao/real2code', project:'https://real2code.github.io/', caveat:'Executable joint code does not validate mass/contact parameters; segmentation and shape completion remain bottlenecks.' },
  { name:'Articulate-Anything', takeaway:"A render-and-critique loop repairs VLM-generated articulation code, with asset retrieval setting the ceiling on geometric fidelity.", year:2025, date:'Apr 2025', domain:'Cross-domain', input:'Text, image, or in-the-wild demonstration video', representation:'Retrieved part meshes + VLM-generated Python/URDF articulation', output:'Interactive digital twin and optional sim-trained robot policy', simulator:'SAPIEN + robosuite/MuJoCo', embodiments:'Franka Panda', summary:'A VLM actor–critic writes, renders, critiques, and repairs articulation code before optional policy training.', metric:'75% articulation success; 4 robot tasks at 100% real success; saves 40.58 annotation minutes/task', stages:['Geometry','Appearance','Physics','Policy'], open:'Open', paper:'https://proceedings.iclr.cc/paper_files/paper/2025/file/2c8047bf3ed8ef6905351608d641f02f-Paper-Conference.pdf', code:'https://github.com/vlongle/articulate-anything', project:'https://articulate-anything.github.io/', caveat:'Mesh retrieval limits instance fidelity; articulation success does not establish accurate mass, friction, or compliance.' },
  { name:'Vid2Sim · Physics', takeaway:"Feed-forward physical initialization amortizes inverse simulation, leaving short per-instance refinement to reconcile the observed motion.", year:2025, date:'Jun 2025', domain:'Graphics', input:'Sparse calibrated multiview videos', representation:'3DGS + learned LBS handles/weights + elastic parameters', output:'Simulation-ready deformable object under new forces and boundaries', simulator:'Reduced implicit-Euler mesh-free / Simplicits-style solver', embodiments:'No robot deployment', summary:'Combines feed-forward physics initialization with short refinement to reduce inverse-physics cost.', metric:'12 synthetic + 3 real objects; real PSNR 27.12; 15 min optimization versus 84–120 min baselines', stages:['Geometry','Appearance','Physics'], open:'Open', paper:'https://openaccess.thecvf.com/content/CVPR2025/papers/Chen_Vid2Sim_Generalizable_Video-based_Reconstruction_of_Appearance_Geometry_and_Physics_for_CVPR_2025_paper.pdf', code:'https://github.com/CzzzzH/Vid2Sim', project:'https://czzzzh.github.io/Vid2Sim/', caveat:'Elastic/deformable focus; the real test has only three objects and needs calibrated multiview video.' },
  { name:'Vid2Sim · Urban Navigation', takeaway:"Gaussian appearance paired with collision meshes turns urban video into a navigation-training environment without modeling manipulation-grade dynamics.", year:2025, date:'Jun 2025', domain:'Cross-domain', input:'Forward-facing monocular web video', representation:'Photoreal 3DGS plus an invisible collision mesh', output:'Editable Unity environment and zero-shot navigation policy', simulator:'Unity + ML-Agents; Isaac Sim supplementary Go2 test', embodiments:'Coco delivery robot + Unitree Go2', summary:'Uses splats for appearance and extracted mesh for collision, enabling graphics-to-policy training from ordinary urban videos.', metric:'30 environments / 9 videos; sim success 81.6/74.4%; real success 85/65/55% over 20 trials/task', stages:['Geometry','Appearance','Physics','Policy'], open:'Open', paper:'https://openaccess.thecvf.com/content/CVPR2025/html/Xie_Vid2Sim_Realistic_and_Interactive_Simulation_from_Video_for_Urban_Navigation_CVPR_2025_paper.html', code:'https://github.com/Vid2Sim/Vid2Sim', project:'https://metadriverse.github.io/vid2sim/', caveat:'Collision/navigation physics rather than manipulation-grade object dynamics; only nine source videos.' },
  { name:'PolaRiS', takeaway:"A simplified task twin can support policy selection when its simulated evaluations preserve real-world policy rankings.", year:2026, date:'Jun 2026', domain:'Cross-domain', input:'2–5 minute calibrated camera scan', representation:'2DGS visual twin + collision mesh + TRELLIS object assets + articulated robot splats', output:'Isaac Sim evaluation and policy co-training environment', simulator:'NVIDIA Isaac Sim', embodiments:'DROID / Franka Panda with two ZED cameras', summary:'Builds a fast task twin for scalable, policy-ranking-faithful evaluation and adds simulation rollouts to generalist-policy co-training.', metric:'600 real + >93k sim rollouts; mean Pearson r=.90 to real and .98 to RoboArena; 21 reconstructed scenes reported with appendix nuance', stages:['Geometry','Appearance','Physics','Policy'], open:'Open', paper:'https://arxiv.org/abs/2512.16881', code:'https://github.com/arhanjain/PolaRiS', project:'https://polaris-evals.github.io/', caveat:'Simplified dynamics; appendix environment grouping makes the 21-scene total slightly definition-dependent.' },
  { name:'D-REX', takeaway:"Differentiating through rendering and rigid-body dynamics couples visual reconstruction with physical calibration for force-aware dexterous behavior.", year:2026, date:'Apr 2026', domain:'Robotics', input:'RGB/depth videos, robot interaction signals, and a few human demonstrations', representation:'3D/2DGS + collision mesh + differentiably identified mass/contact + feasible robot demonstrations', output:'Dexterous grasp policy and real2sim2real engine', simulator:'MJX / MuJoCo', embodiments:'Franka Panda + Allegro or LEAP hands', summary:'Differentiates through rendering and rigid-body dynamics to align a photoreal scene, object physics, and force-aware dexterous behavior.', metric:'8 objects; ≈86% mean success; mass-matched 80% versus 30–40%; recon 306–337 images in 30–35 min', stages:['Geometry','Appearance','Physics','Retargeting','Policy'], open:'Open', paper:'https://openreview.net/forum?id=13jshGCK9i', code:'https://github.com/louhz/D-rex', project:'https://robot-drex-engine.github.io/', caveat:'Rigid bodies only; repository warns the Franka–LEAP path is not fully cleaned or tested.' },
  { name:'IGen', takeaway:"Image-to-3D recovery and trajectory synthesis turn one scene image into demonstrations through dynamic point-cloud rendering.", year:2026, date:'Jun 2026', domain:'Robotics', input:'One open-world RGB image plus task text', representation:'Point clouds + spatial keypoints + VLM plan + SE(3) trajectories', output:'Rendered robot demonstrations and a fine-tuned policy', simulator:'Custom dynamic point-cloud execution/rendering; no named rigid-body engine', embodiments:'Franka Research 3 + Kinect', summary:'Generates robot demonstrations from a single image by combining image-to-3D structure, reasoning, trajectory synthesis, and dynamic point-cloud rendering.', metric:'1,000 demos from one image; 18.6 s/sample; 30× TesserAct and 200× Cosmos-Predict2 throughput', stages:['Geometry','Appearance','Retargeting','Policy'], open:'Open', paper:'https://openaccess.thecvf.com/content/CVPR2026/papers/Gu_IGen_Scalable_Data_Generation_for_Robot_Learning_from_Open-World_Images_CVPR_2026_paper.pdf', code:'https://github.com/chenghaogu/IGen', project:'https://chenghaogu.github.io/IGen/', caveat:'Synthetic motion generator rather than a persistent interactive physics twin.' },
  { name:'SIMPACT', takeaway:"Simulating and scoring VLM action proposals closes a test-time planning loop, with reliability bounded by single-view physical estimates.", year:2026, date:'Jun 2026', domain:'Robotics', input:'One calibrated RGB-D observation plus language', representation:'Per-object meshes + VLM-inferred physics + simulated candidate futures', output:'Zero-shot refined action sequence', simulator:'MuJoCo rigid + projective dynamics + MPM', embodiments:'Franka Research 3 parallel jaw + RealSense D435i', summary:'Lets a VLM propose, simulate, score, and revise actions across rigid, stiff-deformable, and topology-changing tasks.', metric:'7 real tasks; selected non-toppling push 80% and rope shaping 90%; no policy training', stages:['Geometry','Physics','Policy'], open:'Open', paper:'https://openaccess.thecvf.com/content/CVPR2026/papers/Liu_SIMPACT_Simulation-Enabled_Action_Planning_using_Vision-Language_Models_CVPR_2026_paper.pdf', code:'https://github.com/simpact-bot/SIMPACT', project:'https://simpact-bot.github.io/', caveat:'Physics parameters are inferred/guessed from a single view; test-time planning rather than learned-policy training.' },
  { name:'CASHER', takeaway:"Reinforcement learning amortizes initial demonstrations across crowdsourced twins before self-generated data adapts the policy to a target scene.", year:2025, date:'Jun 2025', domain:'Robotics', input:'Crowdsourced phone/video scans plus initial human demonstrations', representation:'Reconstructed interactive twins across environments', output:'Sim trajectories, model-generated demos, and a generalist visuomotor policy', simulator:'Physics engine not disclosed in accessible primary material', embodiments:'Manipulation robot; exact SKU not disclosed', summary:'Crowdsources scene twins, amortizes initial demonstrations through RL, and self-generates further data for target-scene adaptation.', metric:'3 real tasks; super-linear zero-/few-shot scaling; scene count and added human-effort total not disclosed', stages:['Geometry','Appearance','Physics','Policy'], open:'Paper only', paper:'https://www.roboticsproceedings.org/rss21/p025.pdf', project:'https://casher-robot-learning.github.io/CASHER/', caveat:'Code, engine, robot SKU, and exact scene total are not publicly verified.' },
  { name:'PIN-WM', takeaway:"Sparse physical interaction constrains rigid-body identification, then physics-aware cousins expand the calibrated world's training distribution.", year:2025, date:'Jun 2025', domain:'Robotics', input:'Multiview static object images plus one or a few real pushes', representation:'2DGS + differentiable LCP dynamics + physics-aware digital cousins', output:'Identified push/flip simulator and PPO policy', simulator:'Custom differentiable LCP rigid-body solver', embodiments:'Fixed-base pushing arm; exact SKU not identified', summary:'Uses sparse physical interaction and photometric evidence to identify a rigid world model, then diversifies it with physics-aware cousins.', metric:'Sim push/flip 97/83%; real push-T/push-cube/flip-cube 45/40/60%; 2 objects / 3 task setups', stages:['Geometry','Appearance','Physics','Policy'], open:'Open', paper:'https://www.roboticsproceedings.org/rss21/p153.pdf', code:'https://github.com/pinwm/pinwm', project:'https://pinwm.github.io/', caveat:'Rigid tabletop pushes/flips with few objects; exact hardware identity is not disclosed.' },
  { name:'Prompting with the Future', takeaway:"Rendering candidate action outcomes makes a VLM's visual judgment usable as the scoring function inside model-predictive control.", year:2025, date:'Jun 2025', domain:'Robotics', input:'Handheld video scan plus a language task', representation:'2DGS/TSDF hybrid twin + segmented movable objects + simulated futures', output:'VLM-selected MPC actions', simulator:'Rigid mesh simulator + Gaussian renderer; engine not named', embodiments:'Fixed-base robot arm; exact SKU not disclosed', summary:'Renders action-conditioned futures from a reconstructed scene and asks a VLM to score them inside a model-predictive-control loop.', metric:'8 tasks; 47/80 real successes (58.75%) versus strongest baseline 22/80', stages:['Geometry','Appearance','Physics','Policy'], open:'Open', paper:'https://www.roboticsproceedings.org/rss21/p145.pdf', code:'https://github.com/prompting-with-the-future/pwtf', project:'https://prompting-with-the-future.github.io/', caveat:'Thin trials and task-specific movable-object segmentation; no isolated reality-alignment score.' },
  { name:'Gibson Env', takeaway:"Scanned indoor spaces provide realistic embodied-training environments, with static geometry defining the boundary of supported interaction.", year:2018, date:'Jun 2018', domain:'Cross-domain', input:'Scans of real buildings', representation:'Reconstructed indoor meshes plus Goggles realism transformation', output:'Navigation and locomotion training environments', simulator:'Bullet3D + Gym + ROS', embodiments:'Husky, TurtleBot, JackRabbot; simulated Minitaur/Ant/Humanoid', summary:'A foundational scan-to-simulator platform that trained embodied agents inside hundreds of real spaces.', metric:'>1,400 floors from 572 buildings; faster than real time; +160% navigation and +72.9% surface complexity', stages:['Geometry','Appearance','Physics','Policy'], open:'Open', paper:'https://openaccess.thecvf.com/content_cvpr_2018/papers/Xia_Gibson_Env_Real-World_CVPR_2018_paper.pdf', code:'https://github.com/StanfordVL/GibsonEnv', project:'https://gibsonenv.github.io/', caveat:'Static legacy indoor twins with no object articulation; scan/data licensing applies.' },
  { name:'Agile Locomotion Sim-to-Real', takeaway:"System identification anchors nominal robot dynamics while randomization teaches the policy to tolerate the remaining simulation uncertainty.", year:2018, date:'Jun 2018', domain:'Robotics', input:'Real Minitaur measurements plus a reference gait', representation:'Calibrated rigid-body, actuator, latency, and randomized dynamics model', output:'Zero-shot physical trot and gallop policies', simulator:'Bullet-family rigid-body simulator', embodiments:'Ghost Robotics Minitaur', summary:'An historical real2sim2real ancestor: system identification and dynamics randomization ground the simulator before deep-RL transfer.', metric:'Trot and gallop transferred successfully; aggregate physical-trial count/rate not reported in the official abstract', stages:['Physics','Policy'], open:'Paper only', paper:'https://roboticsproceedings.org/rss14/p10.pdf', project:'https://roboticsproceedings.org/rss14/p10.html', caveat:'Calibrates embodiment dynamics rather than reconstructing environment geometry or appearance.' },
  { name:'Dynamic Imitation', takeaway:"Combining kinematic targets with learned balance and forward dynamics makes feasible robot actions the unit of imitation.", year:2006, date:'Aug 2006', domain:'Robotics', input:'Marker-based human motion capture', representation:'Kinematic motion prior + learned sensor-conditioned balance prior', output:'Dynamically feasible humanoid actions', simulator:'Custom humanoid simulator; engine unnamed', embodiments:'Fujitsu HOAP-2', summary:'Fuses kinematic imitation with learned balance and forward dynamics, then searches for feasible actions through probabilistic inference.', metric:'2 physical behaviors—squat and one-legged balance—succeed in simulation and on HOAP-2', stages:['Physics','Retargeting','Policy'], open:'Paper only', paper:'https://www.roboticsproceedings.org/rss02/p26.pdf', project:'https://www.roboticsproceedings.org/rss02/p26.html', caveat:'Foundational controlled-motion result with marker mocap, only two behaviors, and no visual scene reconstruction.' },
  { name:'Nonparametric Motion Retargeting', takeaway:"Local learned correspondences handle nonlinear embodiment differences while graph search assembles smooth collision-aware transitions.", year:2020, date:'Jul 2020', domain:'Robotics', input:'OptiTrack human motion plus paired human/robot poses', representation:'Locally weighted shared latent space + collision-aware transition graph', output:'Collision-free humanoid joint poses and live puppeteering', simulator:'ThorMang and COMAN simulation environments', embodiments:'ThorMang, COMAN, and physical Theo humanoid', summary:'Learns local nonlinear human–robot correspondences and graph-searches smooth collision-aware transitions.', metric:'5 live physical motions: left/right wave, both hands up, head scratch, arms crossed', stages:['Retargeting'], open:'Paper only', paper:'https://www.roboticsproceedings.org/rss16/p071.pdf', project:'https://www.roboticsproceedings.org/rss16/p071.html', caveat:'Needs paired robot poses and does not learn dynamics or an autonomous task policy.' },
  { name:'Robotic Telekinesis', takeaway:"Internet-pretrained hand perception and collision-aware retargeting turn monocular video into live dexterous commands without instrumented capture.", year:2022, date:'Jun 2022', domain:'Robotics', input:'Uncalibrated monocular RGB human-hand video', representation:'Estimated hand pose + learned collision-aware retargeter', output:'Real-time arm and dexterous-hand commands', simulator:'No simulator', embodiments:'xArm6 + 16-DoF Allegro hand', summary:'Pretrains monocular hand perception from internet video and maps it to a robot using neural retargeting, adversarial self-collision, and arm IK.', metric:'10 tasks; better than single-camera DexPilot on 7/10; user study 10 people × 3 tasks × 7 trials', stages:['Retargeting'], open:'Paper only', paper:'https://www.roboticsproceedings.org/rss18/p023.pdf', project:'https://robotic-telekinesis.github.io/', caveat:'Teleoperation rather than autonomous policy learning; no simulator world is built.' },
  { name:'Human Motion Control of Quadrupeds', takeaway:"Task-semantic experts bridge human–quadruped morphology differences before curriculum reinforcement learning makes the mapped motions executable.", year:2022, date:'Jun 2022', domain:'Robotics', input:'Azure Kinect human skeleton motion', representation:'Task-semantic quadruped references + transition graph', output:'Real-time quadruped control policies', simulator:'RaiSim', embodiments:'Unitree A1', summary:'Maps human motion through supervised semantic experts, corrects inconsistent references, and trains curriculum-RL controllers with domain randomization.', metric:'6 task families; 76–522 paired examples/task and ≈1.2B RaiSim samples per expert', stages:['Physics','Retargeting','Policy'], open:'Paper only', paper:'https://www.roboticsproceedings.org/rss18/p021.pdf', project:'https://sites.google.com/view/humanconquad', caveat:'Mappings are task-specific and require curated paired human/robot examples.' },
];

export const expansionVenues: Record<string, PublicationVenue> = {
  SIM1:{ label:'arXiv Apr 2026 · ECCV 2026 announced by authors; archival record not verified', verified:false, href:'https://github.com/InternRobotics/SIM1' },
  nvdiffrec:{ label:'CVPR 2022', verified:true, href:'https://nvlabs.github.io/nvdiffrec/' },
  IRIS:{ label:'CVPR 2025', verified:true, href:'https://irisldr.github.io/' },
  GIR:{ label:'IEEE TPAMI 2025', verified:true, href:'https://3dgir.github.io/' },
  'Real2Sim · Approximate State': { label:'CoRL 2020', verified:true, href:'https://corlconf.github.io/corl2020/paper_59/' },
  'DiSECt': { label:'Robotics: Science and Systems (RSS) 2021 · Best Student Paper', verified:true, href:'https://www.roboticsproceedings.org/rss17/p067.html' },
  'Ditto': { label:'IEEE/CVF CVPR 2022 · Oral', verified:true, href:'https://openaccess.thecvf.com/content/CVPR2022/papers/Jiang_Ditto_Building_Digital_Twins_of_Articulated_Objects_From_Interaction_CVPR_2022_paper.pdf' },
  'Approximate Differentiable Physics': { label:'IEEE/RSJ IROS 2022', verified:true, href:'https://data.ciirc.cvut.cz/public/projects/2022Real2SimPhysics/' },
  'NeuPhysics': { label:'NeurIPS 2022', verified:true, href:'https://proceedings.neurips.cc/paper_files/paper/2022/file/53d3f45797970d323bd8a0d379c525aa-Paper-Conference.pdf' },
  'PAC-NeRF': { label:'ICLR 2023', verified:true, href:'https://openreview.net/forum?id=tVkrbkz42vc' },
  'ACDC Digital Cousins': { label:'CoRL 2024 / PMLR 270', verified:true, href:'https://proceedings.mlr.press/v270/dai25a.html' },
  'URDFormer': { label:'Robotics: Science and Systems (RSS) 2024', verified:true, href:'https://www.roboticsproceedings.org/rss20/p124.html' },
  'DiffTactile': { label:'ICLR 2024', verified:true, href:'https://proceedings.iclr.cc/paper_files/paper/2024/file/1cc70be9fb6a83bc46cf4ac21a91e0b0-Paper-Conference.pdf' },
  'PhysDreamer': { label:'ECCV 2024 · Oral', verified:true, href:'https://physdreamer.github.io/' },
  'PhysGaussian': { label:'IEEE/CVF CVPR 2024 · Highlight', verified:true, href:'https://openaccess.thecvf.com/content/CVPR2024/papers/Xie_PhysGaussian_Physics-Integrated_3D_Gaussians_for_Generative_Dynamics_CVPR_2024_paper.pdf' },
  'Real2Code': { label:'ICLR 2025', verified:true, href:'https://proceedings.iclr.cc/paper_files/paper/2025/file/028fcbcf85435d39a40c4d61b42c99a4-Paper-Conference.pdf' },
  'Articulate-Anything': { label:'ICLR 2025', verified:true, href:'https://proceedings.iclr.cc/paper_files/paper/2025/file/2c8047bf3ed8ef6905351608d641f02f-Paper-Conference.pdf' },
  'Vid2Sim · Physics': { label:'IEEE/CVF CVPR 2025', verified:true, href:'https://openaccess.thecvf.com/content/CVPR2025/papers/Chen_Vid2Sim_Generalizable_Video-based_Reconstruction_of_Appearance_Geometry_and_Physics_for_CVPR_2025_paper.pdf' },
  'Vid2Sim · Urban Navigation': { label:'IEEE/CVF CVPR 2025', verified:true, href:'https://openaccess.thecvf.com/content/CVPR2025/html/Xie_Vid2Sim_Realistic_and_Interactive_Simulation_from_Video_for_Urban_Navigation_CVPR_2025_paper.html' },
  'PolaRiS': { label:'Robotics: Science and Systems (RSS) 2026', verified:true, href:'https://www.roboticsproceedings.org/rss22/p062.html' },
  'D-REX': { label:'ICLR 2026', verified:true, href:'https://openreview.net/forum?id=13jshGCK9i' },
  'IGen': { label:'IEEE/CVF CVPR 2026', verified:true, href:'https://openaccess.thecvf.com/content/CVPR2026/papers/Gu_IGen_Scalable_Data_Generation_for_Robot_Learning_from_Open-World_Images_CVPR_2026_paper.pdf' },
  'SIMPACT': { label:'IEEE/CVF CVPR 2026', verified:true, href:'https://openaccess.thecvf.com/content/CVPR2026/papers/Liu_SIMPACT_Simulation-Enabled_Action_Planning_using_Vision-Language_Models_CVPR_2026_paper.pdf' },
  'CASHER': { label:'Robotics: Science and Systems (RSS) 2025', verified:true, href:'https://www.roboticsproceedings.org/rss21/p025.html' },
  'PIN-WM': { label:'Robotics: Science and Systems (RSS) 2025', verified:true, href:'https://www.roboticsproceedings.org/rss21/p153.html' },
  'Prompting with the Future': { label:'Robotics: Science and Systems (RSS) 2025', verified:true, href:'https://www.roboticsproceedings.org/rss21/p145.html' },
  'Gibson Env': { label:'IEEE/CVF CVPR 2018', verified:true, href:'https://openaccess.thecvf.com/content_cvpr_2018/papers/Xia_Gibson_Env_Real-World_CVPR_2018_paper.pdf' },
  'Agile Locomotion Sim-to-Real': { label:'Robotics: Science and Systems (RSS) 2018', verified:true, href:'https://roboticsproceedings.org/rss14/p10.html' },
  'Dynamic Imitation': { label:'Robotics: Science and Systems (RSS) 2006', verified:true, href:'https://www.roboticsproceedings.org/rss02/p26.html' },
  'Nonparametric Motion Retargeting': { label:'Robotics: Science and Systems (RSS) 2020', verified:true, href:'https://www.roboticsproceedings.org/rss16/p071.html' },
  'Robotic Telekinesis': { label:'Robotics: Science and Systems (RSS) 2022', verified:true, href:'https://www.roboticsproceedings.org/rss18/p023.html' },
  'Human Motion Control of Quadrupeds': { label:'Robotics: Science and Systems (RSS) 2022', verified:true, href:'https://www.roboticsproceedings.org/rss18/p021.html' },
};

const moduleNames: Record<string, [string, string, string, string]> = {
  SIM1:['Garment scan + URDF import','Textured scene meshes','Expert-calibrated Newton / AVBD','Diffusion trajectories → filtering → Cycles → policy'],
  nvdiffrec:['Posed multi-view images','Differentiable mesh extraction','Material + environment optimization','Relightable mesh export'],
  IRIS:['Posed LDR images + geometry','BRDF + emitter initialization','HDR recovery + shading + camera response','Relighting / object insertion'],
  GIR:['Multi-view images','Gaussian geometry + normals','Material / illumination factorization','Novel-view rendering / relighting'],
  'Real2Sim · Approximate State':['Mask R-CNN + 100DOH','Coarse neural inverse graphics','PyPhysX physical losses','rlpyt RL + numerical IK'],
  'DiSECt':['Real cutting-force traces','FEM + SDF contact + damage springs','Differentiable parameter inference','Force-aware trajectory optimization'],
  'Ditto':['Before/after RealSense point clouds','PointNet++ implicit occupancy','Part/joint estimator','robosuite articulated replay'],
  'Approximate Differentiable Physics':['STCN + 100DOH','PyTorch3D state reconstruction','TorchDiffEq contact dynamics','Panda trajectory + IK'],
  'NeuPhysics':['Monocular video','Neural SDF + deformation fields','Neural↔hexahedral conversion','Warp differentiable simulation'],
  'PAC-NeRF':['Calibrated multiview video','Voxel NeRF + particles','Taichi MLS-MPM','Constitutive parameter fitting'],
  'ACDC Digital Cousins':['Grounded-SAM2 + Depth Anything V2','DINOv2/CLIP asset retrieval','BEHAVIOR + OmniGibson cousins','robomimic policy training'],
  'URDFormer':['GroundingDINO boxes','Transformer image-to-URDF','PartNet meshes + PyBullet','Reality Gym policy transfer'],
  'DiffTactile':['Real tactile observations','FEM elastomer + neural renderer','Taichi MLS-MPM/PBD contact','Gradient skill optimization'],
  'PhysDreamer':['Static 3DGS','Stable Video Diffusion prior','Material-field identification','Differentiable MPM'],
  'PhysGaussian':['Pretrained 3DGS','Gaussian-to-particle initialization','Continuum material assignment','GPU MPM rollout'],
  'Real2Code':['DUSt3R + SAM fusion','Part completion + OBBs','CodeLlama articulation code','MJCF compilation'],
  'Articulate-Anything':['Text/image/video prompt','PartNet asset retrieval','VLM actor–critic URDF repair','SAPIEN / MuJoCo policy training'],
  'Vid2Sim · Physics':['Sparse multiview video','LGM 3DGS initialization','LBS + Simplicits dynamics','Short physics refinement'],
  'Vid2Sim · Urban Navigation':['Monocular depth + DEVA','3DGS + TSDF collision extraction','Unity environment augmentation','ML-Agents navigation policy'],
  'PolaRiS':['ChArUco scan calibration','2DGS + collision extraction','TRELLIS assets + Isaac Sim','Policy ranking + co-training'],
  'D-REX':['RGB-D/interaction capture','Gaussian scene + collision mesh','Differentiable MJX system ID','MANO retargeting + force-aware RL'],
  'IGen':['Single image + task text','Image-to-3D point cloud + keypoints','VLM plan + SE(3) synthesis','Dynamic rendering + π0 fine-tune'],
  'SIMPACT':['RGB-D segmentation + image-to-3D','VLM physical-property inference','MuJoCo / PD / MPM futures','VLM action sampler–evaluator'],
  'CASHER':['Crowdsourced video scans','Interactive twin assembly','Human-demo bootstrap + RL','Generalist self-generated demonstrations'],
  'PIN-WM':['Multiview capture + real pushes','2DGS reconstruction','Differentiable LCP system ID','Digital cousins + PPO'],
  'Prompting with the Future':['Handheld video scan','2DGS + TSDF mesh','Rigid simulated futures + CEM','VLM future scoring'],
  'Gibson Env':['Real building scans','Mesh reconstruction + Goggles','Bullet3D environments','Gym/ROS navigation RL'],
  'Agile Locomotion Sim-to-Real':['Real robot measurements','Actuator + latency system ID','Dynamics randomization','Deep-RL gait transfer'],
  'Dynamic Imitation':['Marker mocap','Skeleton fit + kinematic prior','GP dynamics + balance prior','Probabilistic constrained search'],
  'Nonparametric Motion Retargeting':['OptiTrack + paired poses','Shared latent LWL² mapping','Collision transition graph','Live humanoid puppeteering'],
  'Robotic Telekinesis':['Monocular hand video','Pretrained hand-pose recovery','Collision-aware neural retargeter','Arm IK + Allegro control'],
  'Human Motion Control of Quadrupeds':['Azure Kinect skeleton','Semantic expert mapping','RaiSim curriculum RL','Domain-randomized A1 deployment'],
};

export const expansionModules: Record<string, PipelineModule[]> = Object.fromEntries(expansionPipelines.map((pipeline) => {
  const names = moduleNames[pipeline.name];
  return [pipeline.name, names.map((name, index) => ({
    name,
    phase:(pipeline.topics?.includes('Inverse rendering') ? ['Capture / input','Reconstruct / represent','Appearance','Render / edit'] : ['Capture / input','Reconstruct / represent','Simulate / align','Learn / deploy'])[index],
    role:[pipeline.input, pipeline.representation, pipeline.simulator, pipeline.output][index],
    href:pipeline.project,
  }))];
}));

const sceneAmounts: Record<string, { amount:string; status:PipelineSceneReport['status']; detail?:string }> = {
  'Real2Sim · Approximate State':{ amount:'N/A · 54 videos / 9 actions', status:'not-applicable' },
  'DiSECt':{ amount:'Not reported', status:'not-reported' }, 'Ditto':{ amount:'Not reported', status:'not-reported' },
  'Approximate Differentiable Physics':{ amount:'N/A · 54 videos / 9 actions', status:'not-applicable' },
  'NeuPhysics':{ amount:'Not reported', status:'not-reported' }, 'PAC-NeRF':{ amount:'9 synthetic instances', status:'reported' },
  'ACDC Digital Cousins':{ amount:'5 real kitchens', status:'reported' }, 'URDFormer':{ amount:'54 kitchen scenes', status:'reported' },
  'DiffTactile':{ amount:'N/A · 4 tasks', status:'not-applicable' }, 'PhysDreamer':{ amount:'8 gallery objects', status:'bounded' },
  'PhysGaussian':{ amount:'Not reported', status:'not-reported' }, 'Real2Code':{ amount:'Not reported', status:'not-reported' },
  'Articulate-Anything':{ amount:'N/A · 4 robot tasks', status:'not-applicable' }, 'Vid2Sim · Physics':{ amount:'15 objects', status:'reported', detail:'12 synthetic and three real deformable objects.' },
  'Vid2Sim · Urban Navigation':{ amount:'30 environments', status:'reported', detail:'Built from nine web videos.' },
  'PolaRiS':{ amount:'21 reconstructed scenes', status:'bounded', detail:'Six paired evaluation plus 15 extra co-training scenes; appendix grouping may count 18 environments.' },
  'D-REX':{ amount:'At least 8 object setups', status:'bounded' }, 'IGen':{ amount:'N/A · 1 image → 1,000 demos', status:'not-applicable' },
  'SIMPACT':{ amount:'7 real task setups', status:'bounded' }, 'CASHER':{ amount:'Not reported · 3 tasks', status:'not-reported' },
  'PIN-WM':{ amount:'2 objects / 3 real task setups', status:'bounded' }, 'Prompting with the Future':{ amount:'Not reported · 8 tasks', status:'not-reported' },
  'Gibson Env':{ amount:'>1,400 floor spaces / 572 buildings', status:'reported' }, 'Agile Locomotion Sim-to-Real':{ amount:'N/A · embodiment model', status:'not-applicable' },
  'Dynamic Imitation':{ amount:'N/A · 2 motions', status:'not-applicable' }, 'Nonparametric Motion Retargeting':{ amount:'N/A · 5 live motions', status:'not-applicable' },
  'Robotic Telekinesis':{ amount:'N/A · 10 tasks', status:'not-applicable' }, 'Human Motion Control of Quadrupeds':{ amount:'N/A · 6 task families', status:'not-applicable' },
};

export const expansionSceneReports: Record<string, PipelineSceneReport> = Object.fromEntries(expansionPipelines.map((pipeline) => {
  const record = sceneAmounts[pipeline.name] ?? { amount:'Not reported', status:'not-reported' as const };
  return [pipeline.name, { amount:record.amount, status:record.status, detail:record.detail ?? `Primary-source audit: ${pipeline.metric}`, href:pipeline.project }];
}));
