export type PipelineInstitution = {
  label: string;
  verified: boolean;
};

// Concise author-affiliation rollups from official project pages, paper front
// matter, or publisher records. Missing records deliberately remain unresolved.
export const pipelineInstitutions: Record<string, PipelineInstitution> = {
  'AdaRoboVLG':{ label:'HUST · Peking University · BIGAI · KEENON Robotics · ByteDance · collaborators', verified:true },
  'SPARK':{ label:'UCLA · USC · University of Utah', verified:true },
  'SoMA':{ label:'CUHK · Shanghai AI Laboratory', verified:true },
  'MicroDuck':{ label:'Pollen Robotics', verified:true },
  'ReaDy-Go':{ label:'Seoul National University · KAIST', verified:true },
  'Ego2Robot':{ label:'Anonymous submission · affiliation withheld', verified:false },
  'RLDX-1':{ label:'RLWRLD', verified:true },
  'World Labs Atlas':{ label:'World Labs', verified:true },
  'GenRec':{ label:'ETH Zürich · KAIST · Google · Microsoft', verified:true },
  'EgoTrack3D':{ label:'ETH Zürich · Microsoft Spatial AI Lab', verified:true },
  'SiMDex':{ label:'University of Tokyo · ByteDance Seed · HKU · SJTU · Tsinghua University', verified:true },
  'VidMap':{ label:'ETH Zürich · Microsoft Spatial AI Lab', verified:true },
  'World Labs R2S2R':{ label:'World Labs', verified:true },
  'Masked Visual Actions':{ label:'World Labs · Stanford University', verified:true },
  'World from Motion':{ label:'NVIDIA Research · Stanford University', verified:true },
  'WAM-TTT':{ label:'Peking University · Galbot · CASIA · Tsinghua University', verified:true },
  'Wh0':{ label:'Shanghai Innovation Institute · Nanjing University · SJTU', verified:true },
  'GenHOI':{ label:'HKUST (Guangzhou) · USTC · HKU · NUS', verified:true },
  'EgoScale':{ label:'University of Maryland · NVIDIA', verified:true },
  'EgoHumanoid':{ label:'HKU · Shanghai Innovation Institute · Beihang University', verified:true },
  'DexImit':{ label:'Shanghai AI Laboratory · Tsinghua University · CUHK · NVIDIA', verified:true },
  'Lucida':{ label:'ByteDance Seed · Peking University · Zhejiang University', verified:true },
  'Zero-WAM':{ label:'Ant Group · Robbyant Research', verified:true },
  'Agentic Real2Sim':{ label:'UBC · Johns Hopkins · FAU · NUS · Columbia · UCLA · Style3D', verified:true },
  'RoboSnap':{ label:'Shanghai AI Laboratory', verified:true },
  'SimFoundry':{ label:'NVIDIA GEAR · UT Austin', verified:true },
  'μ₀':{ label:'University of Maryland · Furong Huang Lab', verified:true },
  'Qwen-RobotManip':{ label:'Alibaba Cloud · Qwen', verified:true },
  'EgoEngine':{ label:'Georgia Institute of Technology · Tsinghua University', verified:true },
  'WorldComposer':{ label:'Peking University · Lightwheel', verified:true },
  'EgoSim':{ label:'SJTU · Shanghai AI Laboratory · HKU', verified:true },
  'ExoGS':{ label:'Shanghai Jiao Tong University', verified:true },
  'GSWorld':{ label:'ETH Zürich', verified:true },
  'RobotArena∞':{ label:'Carnegie Mellon University · National Taiwan University', verified:true },
  'VITRA':{ label:'Microsoft Research', verified:true },
  'GaussGym':{ label:'UC Berkeley · Covariant', verified:true },
  'Real2Sim Soft Bodies':{ label:'Columbia University · RoboPIL', verified:true },
  'TraceGen':{ label:'University of Maryland · Furong Huang Lab', verified:true },
  'HDMI':{ label:'Carnegie Mellon University · LeCAR Lab', verified:true },
  'VideoMimic':{ label:'Georgia Institute of Technology', verified:true },
  'Scalable Real2Sim':{ label:'MIT · Amazon Robotics', verified:true },
  'ReBot':{ label:'UC Berkeley', verified:true },
  'X-Sim':{ label:'Cornell University', verified:true },
  'Re³Sim':{ label:'SJTU · Shanghai AI Laboratory · HKU', verified:true },
  'SplatSim':{ label:'Carnegie Mellon University', verified:true },
  'RialTo':{ label:'MIT CSAIL', verified:true },
  'Immediate3DGS':{ label:'Inria · GraphDeco', verified:true },
  'AnyRecon':{ label:'CUHK · Shanghai AI Laboratory', verified:true },
  'M³':{ label:'CUHK · Shanghai AI Laboratory', verified:true },
  'LiteReality-Agent':{ label:'University of Cambridge', verified:true },
  'LiteReality':{ label:'University of Cambridge', verified:true },
  'On-the-fly NVS':{ label:'Inria · GraphDeco', verified:true },
  'Teaching by Showing':{ label:'Massachusetts Institute of Technology', verified:true },
  'One-Demonstration Learning':{ label:'Georgia Institute of Technology', verified:true },
  'Gleicher Motion Retargeting':{ label:'University of Wisconsin–Madison', verified:true },
  'Schaal Imitation Framework':{ label:'USC · ATR', verified:true },
  'Choi–Ko Online Retargeting':{ label:'Seoul National University', verified:true },
  'Dynamic Movement Primitives':{ label:'USC · ATR', verified:true },
  'Nakaoka Dance Transfer':{ label:'AIST', verified:true },
  'Dariush Markerless Transfer':{ label:'Honda Research Institute USA', verified:true },
  'Argall LfD Design Space':{ label:'Carnegie Mellon University', verified:true },
  'SMPL':{ label:'Max Planck Institute for Intelligent Systems', verified:true },
  'DeepMimic':{ label:'UC Berkeley', verified:true },
  'AnyTeleop':{ label:'UC San Diego · NVIDIA', verified:true },
  'H2O':{ label:'Carnegie Mellon University · NVIDIA', verified:true },
  'OmniH2O':{ label:'Carnegie Mellon University · NVIDIA', verified:true },
  'HumanPlus':{ label:'Stanford University', verified:true },
  'GMR Retargeting':{ label:'Carnegie Mellon University · LeCAR Lab', verified:true },
  'SPIDER Retargeting':{ label:'Carnegie Mellon University · LeCAR Lab', verified:true },
  'UMR':{ label:'HKUST (Guangzhou) · Noitom Robotics · Hanyang University · HKUST · HKU', verified:true },
  'EmbodMocap':{ label:'University of Hong Kong', verified:true },
  'HumanX':{ label:'Galbot · Shanghai AI Laboratory', verified:true },
  'AINA':{ label:'New York University · Meta', verified:true },
  'HumanEgo':{ label:'University of Maryland · Furong Huang Lab', verified:true },
  'OmniRetarget':{ label:'Stanford University', verified:true },
  'FunREC':{ label:'ETH Zürich · MPI for Informatics', verified:true },
  'REACT3D':{ label:'ETH Zürich · MPI for Informatics', verified:true },
  'i-Sim2Real':{ label:'Google Research', verified:true },
  'XIRL':{ label:'Google Research · UC Berkeley', verified:true },
  'Animal-to-Laikago Imitation':{ label:'Google Research · UC Berkeley', verified:true },
  'Real2Sim · Approximate State':{ label:'CIIRC, Czech Technical University in Prague · Inria', verified:true },
  'DiSECt':{ label:'NVIDIA · ETH Zürich', verified:true },
  'Ditto':{ label:'University of Texas at Austin', verified:true },
  'Approximate Differentiable Physics':{ label:'CIIRC, Czech Technical University in Prague · IIIT Hyderabad', verified:true },
  'NeuPhysics':{ label:'MIT CSAIL', verified:true },
  'PAC-NeRF':{ label:'UCLA · University of Maryland · MIT · Columbia · UMass Amherst · MIT-IBM Watson AI Lab', verified:true },
  'ACDC Digital Cousins':{ label:'Stanford University · Stanford HAI', verified:true },
  'URDFormer':{ label:'University of Washington · NVIDIA', verified:true },
  'DiffTactile':{ label:'CMU · SJTU · Tsinghua University · MIT · UMass Amherst · MIT-IBM Watson AI Lab', verified:true },
  'PhysDreamer':{ label:'Stanford University · NVIDIA', verified:true },
  'PhysGaussian':{ label:'UCLA · Zhejiang University · University of Utah', verified:true },
  'Real2Code':{ label:'Stanford University · Columbia University', verified:true },
  'Articulate-Anything':{ label:'University of Pennsylvania', verified:true },
  'Vid2Sim · Physics':{ label:'University of Pennsylvania · HKU · Zhejiang University', verified:true },
  'Vid2Sim · Urban Navigation':{ label:'UCLA · UIUC', verified:true },
  'PolaRiS':{ label:'Stanford University', verified:true },
  'D-REX':{ label:'UC Berkeley · Covariant', verified:true },
  'IGen':{ label:'Tsinghua University · HKU · BUCT · SJTU · Shenzhen University of Information Technology', verified:true },
  'SIMPACT':{ label:'University of Maryland · UIUC · Harvard University · Amazon FAR · University of Pennsylvania', verified:true },
  'CASHER':{ label:'MIT · University of Washington · Stanford University', verified:true },
  'PIN-WM':{ label:'National University of Defense Technology · Wuhan University · Shenzhen University · Guangdong AI and Digital Economy Lab', verified:true },
  'Prompting with the Future':{ label:'Cornell University', verified:true },
  'Gibson Env':{ label:'Stanford University', verified:true },
  'Agile Locomotion Sim-to-Real':{ label:'ETH Zürich', verified:true },
  'Dynamic Imitation':{ label:'University of Washington', verified:true },
  'Nonparametric Motion Retargeting':{ label:'Disney Research · UIUC', verified:true },
  'Robotic Telekinesis':{ label:'Carnegie Mellon University', verified:true },
  'Human Motion Control of Quadrupeds':{ label:'Seoul National University · Georgia Institute of Technology', verified:true },
};

export const institutionFor = (name:string):PipelineInstitution => pipelineInstitutions[name] ?? { label:'Affiliation not verified', verified:false };
