import { expansionModules } from './pipeline-expansion';

export type PipelineModule = {
  name: string;
  phase: string;
  role: string;
  href: string;
  capability?: string;
  contributesTo?: ('Geometry' | 'Appearance' | 'Physics' | 'Retargeting' | 'Policy')[];
};

const corePipelineModules: Record<string, PipelineModule[]> = {
  SPARK: [
    { name:'GPT-4o structural reasoning', phase:'Structure', role:'Predicts part labels and initial URDF metadata.', href:'https://arxiv.org/html/2512.01629v2#S3.SS1', contributesTo:['Geometry','Physics'] },
    { name:'Gemini part / open-state guidance', phase:'Guidance', role:'Synthesizes reference images for reconstruction and articulation fitting.', href:'https://arxiv.org/html/2512.01629v2#S3.SS1', contributesTo:['Geometry','Physics'] },
    { name:'Part-aware diffusion transformer', phase:'Geometry', role:'Generates coherent part meshes using image and hierarchy conditioning.', href:'https://arxiv.org/html/2512.01629v2#S3.SS2', contributesTo:['Geometry'] },
    { name:'Meshy texture generation', phase:'Appearance', role:'Textures the generated geometry in the released implementation.', href:'https://github.com/YumengHe/SPARK', contributesTo:['Appearance'] },
    { name:'Differentiable URDF optimization', phase:'Articulation', role:'Refines joints through forward kinematics and differentiable rendering.', href:'https://arxiv.org/html/2512.01629v2#S3.SS3', contributesTo:['Physics'] },
    { name:'Isaac Sim drawer-opening demo', phase:'Policy', role:'Demonstrates robot learning on a generated asset; no real transfer result.', href:'https://arxiv.org/html/2512.01629v2#S4.SS4', contributesTo:['Policy'] },
  ],
  SoMA: [
    { name:'Three-camera RGB + joint-state capture', phase:'Capture', role:'Records synchronized 640×480 views and ARX-Lift joint / gripper states at 30 FPS.', href:'https://arxiv.org/html/2602.02402v2#S5.SS1' },
    { name:'Multi-view camera estimation', phase:'Pose', role:'Recovers camera poses and aligns observations before Gaussian reconstruction.', href:'https://arxiv.org/html/2602.02402v2#S4.SS2.SSS1' },
    { name:'Metric Gaussian initialization', capability:'3D Gaussian Splatting', phase:'Geometry / appearance', role:'Reconstructs the deformable object and registers it to the robot and gravity frame.', href:'https://arxiv.org/html/2602.02402v2#S4.SS2.SSS1' },
    { name:'Forward-kinematic robot conditioning', phase:'Action interface', role:'Maps joint configuration and gripper opening into the shared Gaussian simulation frame.', href:'https://arxiv.org/html/2602.02402v2#S4.SS2.SSS1' },
    { name:'Robot interaction graph', phase:'Contact', role:'Predicts robot-induced latent forces between control points and nearby splats.', href:'https://arxiv.org/html/2602.02402v2#S4.SS2.SSS2' },
    { name:'Hierarchical force-driven GS dynamics', capability:'SoMA neural GS simulator', phase:'Dynamics', role:'Propagates robot and environment effects across Gaussian clusters and predicts deformation.', href:'https://arxiv.org/html/2602.02402v2#S4.SS2.SSS2' },
    { name:'Coarse-to-fine temporal training', phase:'Train', role:'Balances long-horizon stability with fine contact and deformation detail.', href:'https://arxiv.org/html/2602.02402v2#S4.SS2.SSS3' },
    { name:'Occlusion + physics-consistency losses', phase:'Verify', role:'Uses visible-image supervision and hierarchical mass consistency for hidden regions.', href:'https://arxiv.org/html/2602.02402v2#S4.SS2.SSS4' },
    { name:'Open-loop action-conditioned rollout', phase:'Simulate', role:'Tests supplied unseen robot trajectories and contacts; no learned control policy is evaluated.', href:'https://arxiv.org/html/2602.02402v2#S5.SS1' },
  ],
  'ReaDy-Go': [
    { name:'PGSR static Gaussian reconstruction', capability:'3D Gaussian Splatting', phase:'Geometry', role:'Builds the photoreal static background from a short real capture.', href:'https://syeon-yoo.github.io/ready-go-site/' },
    { name:'HUGS animatable human Gaussians', phase:'4D appearance', role:'Represents controllable dynamic pedestrians as articulated Gaussian avatars.', href:'https://syeon-yoo.github.io/ready-go-site/' },
    { name:'PriorMDM motion synthesis', phase:'Motion', role:'Generates human motion sequences for the inserted avatars.', href:'https://arxiv.org/abs/2602.11575' },
    { name:'Hybrid-A* robot planner', phase:'Plan', role:'Produces collision-avoiding mobile-robot reference trajectories.', href:'https://arxiv.org/abs/2602.11575' },
    { name:'Pedestrian trajectory planner', phase:'Script dynamics', role:'Coordinates time-varying avatar paths; motion is kinematic rather than contact-simulated.', href:'https://arxiv.org/abs/2602.11575' },
    { name:'Gaussian rollout renderer', phase:'Render', role:'Produces onboard-view observations with dynamic visual occluders.', href:'https://syeon-yoo.github.io/ready-go-site/' },
    { name:'Imitation policy', phase:'Policy', role:'Learns navigation from the generated dynamic-scene trajectories.', href:'https://arxiv.org/abs/2602.11575' },
  ],
  Ego2Robot: [
    { name:'Ego corpus / raw video', capability:'Ego2Robot conversion engine', phase:'Capture', role:'Accepts annotated ego datasets or estimates hand motion and subtasks from ordinary video.', href:'https://arxiv.org/html/2608.02580#S3' },
    { name:'WiLoR + DynHaMR', phase:'Hand recon', role:'Recovers per-frame hand pose and temporally optimizes it for raw-video inputs.', href:'https://arxiv.org/html/2608.02580#A1' },
    { name:'Hand-to-gripper mapping', phase:'Retarget', role:'Converts 21-keypoint hand geometry into camera-frame TCP pose and gripper width, then smooths and speed-aligns it.', href:'https://arxiv.org/html/2608.02580#S3.SS1' },
    { name:'SAM 3 + ProPainter', capability:'SAM 3', phase:'Appearance', role:'Segments and removes the human arm with temporally consistent video inpainting.', href:'https://arxiv.org/html/2608.02580#S3.SS2' },
    { name:'MuJoCo base search + IK', phase:'Kinematics', role:'Finds a feasible base placement and solves each morphology frame-by-frame.', href:'https://arxiv.org/html/2608.02580#S3.SS2' },
    { name:'Depth-aware robot rendering', phase:'Compose', role:'Places the target embodiment into the original viewpoint with scene-depth ordering.', href:'https://arxiv.org/html/2608.02580#S3.SS2' },
    { name:'Three-level quality curation', phase:'Filter', role:'Rejects IK, collision, action, discontinuity, and VLM semantic-consistency failures.', href:'https://arxiv.org/html/2608.02580#S3.SS3' },
    { name:'Ego2R + robot VLA pretraining', phase:'Policy', role:'Mixes synthesized and robot frames to test visual, scene, embodiment, and task generalization.', href:'https://arxiv.org/html/2608.02580#S5' },
  ],
  'RLDX-1': [
    { name:'Bare-hand + object capture', capability:'RLWRLD human-data engine', phase:'Capture', role:'Records dexterous behavior without fitting a physical teleoperation device to the hand.', href:'https://www.rlwrld.ai/ko/insight/blog/14' },
    { name:'3D Gaussian Splatting', capability:'3D Gaussian Splatting', phase:'Reconstruct', role:'Builds the workspace representation used by the human-data conversion route.', href:'https://www.rlwrld.ai/ko/insight/blog/14' },
    { name:'Five-finger retargeter', phase:'Retarget', role:'Closes the human–robot morphology gap in software for dexterous hands.', href:'https://www.rlwrld.ai/ko/insight/blog/14' },
    { name:'Simulation rollout', phase:'Simulate', role:'Executes retargeted trajectories to produce robot-format VLA demonstrations; engine is not named.', href:'https://www.rlwrld.ai/ko/insight/blog/14' },
    { name:'Cosmos video augmentation', phase:'Generate', role:'Separately expands seed robot data with scene and trajectory variations.', href:'https://www.rlwrld.ai/ko/insight/blog/14' },
    { name:'Inverse dynamics + consistency filter', phase:'Label / filter', role:'Adds actions to generated video and retains instruction-following, motion-consistent samples.', href:'https://www.rlwrld.ai/ko/insight/blog/14' },
    { name:'MSAT multimodal VLA', phase:'Policy', role:'Fuses vision/language, proprioception, action, memory, tactile, and torque streams.', href:'https://arxiv.org/abs/2605.03269' },
    { name:'DAgger + progress-aware RL', phase:'Post-train', role:'Collects recovery corrections and uses a VLM progress estimator for dense reward.', href:'https://www.rlwrld.ai/ko/insight/blog/14' },
  ],
  SiMDex: [
    { name:'Robot task query', phase:'Specify', role:'Defines target semantics and embodiment-relevant motion evidence.', href:'https://arxiv.org/abs/2608.04196' },
    { name:'Large-scale recall', phase:'Recall', role:'Finds candidate clips in roughly 32 million egocentric samples.', href:'https://lin-nie.github.io/SiMDex/' },
    { name:'Semantic + motion ranking', phase:'Rank', role:'Scores task similarity and manipulation-motion usefulness.', href:'https://arxiv.org/abs/2608.04196' },
    { name:'Cross-embodiment re-ranking', phase:'Retarget', role:'Keeps samples whose interaction structure survives morphology change.', href:'https://arxiv.org/abs/2608.04196' },
    { name:'VLA post-training', phase:'Policy', role:'Learns from the mined 1.49M-sample subset.', href:'https://lin-nie.github.io/SiMDex/' },
  ],
  'WAM-TTT': [
    { name:'Unlabelled human play', phase:'Observe', role:'Provides task-relevant visual experience at deployment time.', href:'https://arxiv.org/abs/2607.06988' },
    { name:'Self-supervised video prediction', phase:'Adapt', role:'Turns the deployment clip into a test-time learning signal.', href:'https://arxiv.org/abs/2607.06988' },
    { name:'Adaptive memory', phase:'Memory', role:'Stores the inferred human-play context without updating the frozen backbone.', href:'https://arxiv.org/abs/2607.06988' },
    { name:'Paired human–robot meta-training', phase:'Align', role:'Teaches the memory mechanism how human evidence should steer robot action.', href:'https://arxiv.org/abs/2607.06988' },
    { name:'Frozen world–action model', phase:'Policy', role:'Predicts and executes robot actions under the adapted context.', href:'https://arxiv.org/abs/2607.06988' },
  ],
  Wh0: [
    { name:'Qwen image editing', capability:'Qwen-Image 2.0', phase:'Compose', role:'Aligns scene and hand appearance before video synthesis.', href:'https://arxiv.org/abs/2606.22136' },
    { name:'Egocentric video generation', phase:'Generate', role:'Produces 50k language- and scene-conditioned human-hand demonstrations.', href:'https://arxiv.org/abs/2606.22136' },
    { name:'HaWoR', capability:'HaWoR', phase:'Hand recon', role:'Recovers world-grounded hand motion from generated egocentric video.', href:'https://arxiv.org/abs/2606.22136' },
    { name:'MANO action interface', phase:'Retarget', role:'Expresses generated hand motion in a unified representation for robot co-training.', href:'https://arxiv.org/abs/2606.22136' },
    { name:'Human + robot co-training', phase:'Policy', role:'Combines generated human evidence with 400 teleoperated robot demonstrations.', href:'https://arxiv.org/abs/2606.22136' },
    { name:'G1 + Inspire deployment', phase:'Deploy', role:'Evaluates the resulting policy across 18 physical tasks.', href:'https://arxiv.org/abs/2606.22136' },
  ],
  GenHOI: [
    { name:'Robot–object scene twin', phase:'Scene', role:'Provides geometry, camera, robot, and object context for generation.', href:'https://arxiv.org/abs/2606.12995' },
    { name:'First-frame renderer', phase:'Render', role:'Anchors the video generator to the intended robot–object state.', href:'https://arxiv.org/abs/2606.12995' },
    { name:'Language + image video generation', phase:'Generate', role:'Synthesizes a candidate humanlike interaction trajectory.', href:'https://arxiv.org/abs/2606.12995' },
    { name:'Contact event + region inference', phase:'Physics', role:'Extracts when and where the robot should contact the object.', href:'https://arxiv.org/abs/2606.12995' },
    { name:'Object-centric constraint optimizer', phase:'Retarget', role:'Converts video evidence into a feasible robot reference motion.', href:'https://arxiv.org/abs/2606.12995' },
    { name:'Closed-loop tracking policy', phase:'Policy', role:'Tracks the optimized reference in simulation and on hardware.', href:'https://arxiv.org/abs/2606.12995' },
  ],
  EgoScale: [
    { name:'Egocentric human corpus', phase:'Data', role:'Supplies 20,854 hours of diverse manipulation experience.', href:'https://arxiv.org/abs/2602.16710' },
    { name:'Human hand / wrist recovery', phase:'Recover', role:'Extracts scalable action evidence from egocentric video.', href:'https://arxiv.org/abs/2602.16710' },
    { name:'22-DoF shared action space', phase:'Retarget', role:'Maps human motion into a morphology-aware robot control interface.', href:'https://arxiv.org/abs/2602.16710' },
    { name:'Egocentric VLA pretraining', phase:'Policy', role:'Learns transferable visual-manipulation structure at scale.', href:'https://arxiv.org/abs/2602.16710' },
    { name:'Aligned human–robot mid-training', phase:'Align', role:'Uses a small target-embodiment mixture to ground actions.', href:'https://arxiv.org/abs/2602.16710' },
    { name:'Embodiment adapter', phase:'Deploy', role:'Transfers the pretrained policy to Sharpa and Unitree hardware.', href:'https://arxiv.org/abs/2602.16710' },
  ],
  EgoHumanoid: [
    { name:'Egocentric human capture', phase:'Capture', role:'Records manipulation from a human head-camera viewpoint.', href:'https://arxiv.org/abs/2602.10106' },
    { name:'MoGe', capability:'MoGe', phase:'Geometry', role:'Estimates geometry for human-to-robot view reprojection.', href:'https://arxiv.org/abs/2602.10106' },
    { name:'Reprojection + diffusion inpainting', phase:'Appearance', role:'Synthesizes a G1-aligned observation while removing human-view artifacts.', href:'https://arxiv.org/abs/2602.10106' },
    { name:'Delta EE + grasp + locomotion interface', phase:'Retarget', role:'Compresses human behavior into an executable whole-body action contract.', href:'https://arxiv.org/abs/2602.10106' },
    { name:'IK + low-level locomotion', phase:'Control', role:'Turns high-level task-space commands into robot motion.', href:'https://arxiv.org/abs/2602.10106' },
    { name:'Human–robot VLA co-training', phase:'Policy', role:'Combines human video with limited G1 demonstrations.', href:'https://arxiv.org/abs/2602.10106' },
  ],
  DexImit: [
    { name:'Monocular bimanual video', phase:'Capture', role:'Provides hands, objects, timing, and task evidence from one demonstration.', href:'https://arxiv.org/abs/2602.10105' },
    { name:'4D hand–object reconstruction', phase:'Geometry', role:'Recovers time-varying hand and object interaction state.', href:'https://arxiv.org/abs/2602.10105' },
    { name:'Subtask decomposition + scheduling', phase:'Plan', role:'Separates bimanual phases and preserves their dependencies.', href:'https://arxiv.org/abs/2602.10105' },
    { name:'Robot grasp + trajectory synthesis', phase:'Retarget', role:'Maps reconstructed interaction constraints to two UR5e arms and XHands.', href:'https://arxiv.org/abs/2602.10105' },
    { name:'Physics replay + filtering', phase:'Physics', role:'Rejects or repairs trajectories that do not execute plausibly.', href:'https://arxiv.org/abs/2602.10105' },
    { name:'Demonstration augmentation', phase:'Policy', role:'Expands the generated robot data for imitation learning.', href:'https://arxiv.org/abs/2602.10105' },
  ],
  Lucida: [
    { name:'Multi-view evidence parser', capability:'Lucida evidence graph', phase:'Scene graph', role:'Deduplicated instances, masks, partial point clouds, boxes, and typed spatial relations.', href:'https://arxiv.org/html/2608.30821#S2.SS1' },
    { name:'SAM 3', capability:'SAM 3', phase:'Segment', role:'Instance masks and manual mask filtering in the reported pipeline.', href:'https://arxiv.org/html/2608.30821#S3.SS2' },
    { name:'Pi3X', phase:'Geometry', role:'Depth estimates for the R2S object and scene splits.', href:'https://arxiv.org/html/2608.30821#S3.SS2' },
    { name:'Seed3D 2.0', phase:'Generate', role:'Completed object image to editable 3D asset.', href:'https://arxiv.org/html/2608.30821#S2.SS2' },
    { name:'GizmoAct', phase:'Place', role:'Closed-loop VLM pose, orientation, and scale refinement.', href:'https://arxiv.org/html/2608.30821#S2.SS3' },
    { name:'Physical plausibility pass', phase:'Physics', role:'Post-processes composed assets for simulation readiness.', href:'https://lucida-r2s.github.io/' },
  ],
  'Zero-WAM': [
    { name:'VLM task parser', phase:'Interpret', role:'Extracts task semantics and a human-scene prompt from robot demonstrations.', href:'https://arxiv.org/abs/2608.26103' },
    { name:'Qwen-Image 2.0', capability:'Qwen-Image 2.0', phase:'Translate', role:'Edits the initial robot observation into a human-view starting frame for HumanGen.', href:'https://arxiv.org/abs/2608.26103' },
    { name:'Wan 2.7 / Kling 3.0', phase:'Generate', role:'Produces candidate human demonstration videos for paired training data.', href:'https://robbyant-research.github.io/Zero-WAM/' },
    { name:'VLM plausibility filter', phase:'Filter', role:'Rejects videos that violate task semantics or basic physical plausibility.', href:'https://arxiv.org/abs/2608.26103' },
    { name:'HumanGen pairs', phase:'Data', role:'Pairs accepted human videos with the source robot actions across 8.6K tasks.', href:'https://robbyant-research.github.io/Zero-WAM/' },
    { name:'Wan2.2-TI2V-5B', capability:'Wan2.2-TI2V-5B', phase:'World–action', role:'Becomes a causal model that predicts future robot video and actions.', href:'https://arxiv.org/abs/2608.26103' },
    { name:'In-context future prediction', phase:'Policy', role:'Uses a human video prompt to infer an unseen robot task without parameter updates.', href:'https://robbyant-research.github.io/Zero-WAM/' },
  ],
  'Agentic Real2Sim': [
    { name:'SAM 3', capability:'SAM 3', phase:'Segment', role:'Open-vocabulary object discovery, masks, and tracking.', href:'https://arxiv.org/html/2607.19190#S3.SS2' },
    { name:'SAM 3D Objects', capability:'SAM 3D Objects', phase:'Geometry', role:'Recovers object meshes from accepted keyframe evidence.', href:'https://arxiv.org/html/2607.19190#S3.SS2' },
    { name:'FoundationStereo', capability:'FoundationStereo', phase:'Geometry', role:'Stereo depth for metric scaling and scene preparation.', href:'https://arxiv.org/html/2607.19190#S2.SS4' },
    { name:'FoundationPose', capability:'FoundationPose', phase:'Pose', role:'Tracks novel-object 6-DoF trajectories.', href:'https://arxiv.org/html/2607.19190#S3.SS2' },
    { name:'VLM physical-prior agent', phase:'Physics', role:'Infers material class, mass hints, and contact-relevant attributes.', href:'https://arxiv.org/html/2607.19190#S3.SS1' },
    { name:'MuJoCo grasp sweep', phase:'Physics', role:'Simulator-in-the-loop object placement and replay refinement.', href:'https://arxiv.org/html/2607.19190#S3.SS2' },
    { name:'PhysTwin adapter', capability:'PhysTwin', phase:'Physics', role:'Extends the episode contract to deformable interaction.', href:'https://arxiv.org/html/2607.19190#S3.SS3' },
    { name:'Humanoid BFM adapter', capability:'Humanoid Behavior Foundation Model', phase:'Retarget', role:'Extends replay to G1 whole-body motion context.', href:'https://arxiv.org/html/2607.19190#S4.SS4' },
  ],
  RoboSnap: [
    { name:'SAM 3', capability:'SAM 3', phase:'Segment', role:'Parses the interaction region into object instances.', href:'https://arxiv.org/html/2607.06699#S3.SS1' },
    { name:'SAM 3D Objects', capability:'SAM 3D Objects', phase:'Generate', role:'Produces textured foreground meshes with initial pose and scale.', href:'https://arxiv.org/html/2607.06699#S3.SS1' },
    { name:'VGGT', capability:'VGGT', phase:'Geometry', role:'Predicts camera geometry and a dense point map from the input image.', href:'https://arxiv.org/html/2607.06699#S3.SS1' },
    { name:'Mask-guided ICP', phase:'Pose', role:'Registers generated meshes to high-confidence foreground points.', href:'https://arxiv.org/html/2607.06699#S3.SS1' },
    { name:'3D Gaussian Splatting', capability:'3D Gaussian Splatting', phase:'Appearance', role:'Preserves the re-renderable visual background.', href:'https://robosnap.github.io/' },
    { name:'Collision refinement', phase:'Physics', role:'Stabilizes foreground assets for interaction and trajectory replay.', href:'https://arxiv.org/html/2607.06699#S3' },
    { name:'π0 / π0.5 policy eval', phase:'Policy', role:'Tests synthetic augmentation and sim–real ranking.', href:'https://robosnap.github.io/' },
  ],
  SimFoundry: [
    { name:'SAM 3', capability:'SAM 3', phase:'Segment', role:'Extracts task-relevant instances from video.', href:'https://github.com/NVlabs/SimFoundry' },
    { name:'Depth Anything 3', capability:'Depth Anything 3', phase:'Geometry', role:'Dense depth for reconstruction and placement.', href:'https://github.com/NVlabs/SimFoundry/blob/main/docs/INSTALL.md' },
    { name:'Hunyuan3D 2.1', capability:'Hunyuan3D 2.1', phase:'Generate', role:'Creates complete visual meshes and digital cousins.', href:'https://github.com/NVlabs/SimFoundry/blob/main/PATCH_PROVENANCE.md' },
    { name:'FoundationPose', capability:'FoundationPose', phase:'Pose', role:'Initial object alignment and pose recovery.', href:'https://github.com/NVlabs/SimFoundry/blob/main/PATCH_PROVENANCE.md' },
    { name:'NVIDIA 3DGRUT', capability:'NVIDIA 3DGRUT', phase:'Appearance', role:'Optional Gaussian background conversion to USDZ.', href:'https://github.com/NVlabs/SimFoundry/blob/main/docs/INSTALL.md' },
    { name:'VLM physical annotation', phase:'Physics', role:'Assigns material and task-relevant physical parameters.', href:'https://research.nvidia.com/labs/gear/simfoundry/' },
    { name:'OmniGibson', phase:'Physics', role:'Compiles and sanity-checks the interactive scene.', href:'https://github.com/NVlabs/SimFoundry' },
    { name:'OpenPI / π0.5 / GR00T', phase:'Policy', role:'Policy training, evaluation, and real-world transfer.', href:'https://research.nvidia.com/labs/gear/simfoundry/' },
  ],
  'Qwen-RobotManip': [
    { name:'Hand + head pose recovery', phase:'Recover', role:'Extracts egocentric human motion and camera-relative action evidence.', href:'https://arxiv.org/abs/2606.17846' },
    { name:'Camera-frame action alignment', phase:'Retarget', role:'Maps human hand motion into target-robot action coordinates and smooths trajectories.', href:'https://github.com/QwenLM/Qwen-RobotManip' },
    { name:'SAM 3', capability:'SAM 3', phase:'Segment', role:'Segments human hands before visual embodiment conversion.', href:'https://arxiv.org/abs/2606.17846' },
    { name:'ProPainter', capability:'ProPainter', phase:'Inpaint', role:'Removes hands while preserving the recorded scene and interaction context.', href:'https://arxiv.org/abs/2606.17846' },
    { name:'Mink / MuJoCo IK + base search', capability:'Mink', phase:'Align', role:'Finds feasible robot placement and joint trajectories for the retargeted action.', href:'https://arxiv.org/html/2606.17846#S2.SS3' },
    { name:'Depth-guided robot compositing', phase:'Render', role:'Renders the target morphology into the real video with visibility reasoning.', href:'https://arxiv.org/abs/2606.17846' },
    { name:'Pinocchio FK consistency', capability:'Pinocchio', phase:'Validate', role:'Checks logged joints against end-effector poses and corrects frame, sign, and TCP inconsistencies.', href:'https://arxiv.org/html/2606.17846#S2.SS4.SSS0.Px4' },
    { name:'Qwen-RobotManip', capability:'Qwen-RobotManip', phase:'Policy', role:'Learns a generalist VLA from synthesized and native robot demonstrations.', href:'https://github.com/QwenLM/Qwen-RobotManip' },
  ],
  EgoEngine: [
    { name:'FoundationStereo', capability:'FoundationStereo', phase:'Geometry', role:'Estimates absolute depth from Aria RGB frames.', href:'https://arxiv.org/html/2606.12604#S3.SS1' },
    { name:'SAM 2.1', capability:'SAM 2.1', phase:'Segment', role:'Tracks human arm–hand and task-object masks.', href:'https://arxiv.org/html/2606.12604#S3.SS1' },
    { name:'FoundationPose', capability:'FoundationPose', phase:'Pose', role:'Recovers the task object’s 6-DoF trajectory.', href:'https://arxiv.org/html/2606.12604#S3.SS1' },
    { name:'Mink', capability:'Mink', phase:'Retarget', role:'Maps human fingertip and wrist poses to robot configurations.', href:'https://arxiv.org/html/2606.12604#S3.SS2.SSS1' },
    { name:'SPIDER-style MPC', capability:'SPIDER', phase:'Refine', role:'Locally repairs infeasible object-centric trajectory chunks.', href:'https://arxiv.org/html/2606.12604#S4.SS3' },
    { name:'PPO residual RL', phase:'Refine', role:'Handles difficult contact-rich chunks after replay and MPC fail.', href:'https://arxiv.org/html/2606.12604#S3.SS2.SSS2' },
    { name:'Inpaint Anything v2', phase:'Appearance', role:'Removes human limbs before occlusion-aware robot compositing.', href:'https://arxiv.org/html/2606.12604#S3.SS3' },
    { name:'HPT', capability:'HPT', phase:'Policy', role:'Distills synchronized robot observation–action demonstrations.', href:'https://arxiv.org/html/2606.12604#S3.SS4' },
  ],
  WorldComposer: [
    { name:'World reconstruction export', phase:'Geometry', role:'Initial panorama-to-world geometry and camera state.', href:'https://github.com/jaber628/WorldComposer' },
    { name:'Gaussian point scene', capability:'3D Gaussian Splatting', phase:'Appearance', role:'Photoreal world representation and rendering.', href:'https://stubborn111.github.io/WorldComposer/' },
    { name:'Mesh + USD composition', phase:'Geometry', role:'Editable objects, collision surfaces, and multi-room layout.', href:'https://github.com/jaber628/WorldComposer' },
    { name:'Physical annotation', phase:'Physics', role:'Attaches interaction and simulator properties to assets.', href:'https://arxiv.org/abs/2604.15805' },
    { name:'Isaac Sim / Isaac Lab', phase:'Physics', role:'Runs manipulation and navigation demonstrations.', href:'https://github.com/jaber628/WorldComposer' },
    { name:'Manipulation + navigation agents', phase:'Policy', role:'Demonstrates downstream embodied use of composed worlds.', href:'https://stubborn111.github.io/WorldComposer/' },
  ],
  EgoSim: [
    { name:'GeoCalib', capability:'GeoCalib', phase:'Calibrate', role:'Recovers camera intrinsics, focal properties, and gravity cues.', href:'https://arxiv.org/abs/2604.01001' },
    { name:'Depth Anything 3', capability:'Depth Anything 3', phase:'Geometry', role:'Initializes dense scene structure from egocentric observations.', href:'https://arxiv.org/abs/2604.01001' },
    { name:'HaMeR', capability:'HaMeR', phase:'Action', role:'Recovers hand meshes and keypoint actions from human interaction video.', href:'https://arxiv.org/abs/2604.01001' },
    { name:'SAM 3', capability:'SAM 3', phase:'Segment', role:'Tracks interaction regions and manipulated objects.', href:'https://arxiv.org/abs/2604.01001' },
    { name:'Grounding DINO', capability:'Grounding DINO', phase:'Detect', role:'Grounds task objects for semantic masks and state updates.', href:'https://arxiv.org/abs/2604.01001' },
    { name:'DROID-SLAM + aligned depth', phase:'Fuse', role:'Builds the metric, camera-aligned initial world state.', href:'https://egosimulator.github.io/' },
    { name:'Wan2.1-Fun-14B-InP', capability:'Wan2.1-Fun-14B-InP', phase:'Generate', role:'Rolls out action- and geometry-conditioned egocentric video.', href:'https://arxiv.org/abs/2604.01001' },
    { name:'Interaction-aware point update + TSDF', phase:'Update', role:'Reconstructs changed regions and fuses them into persistent 3D state.', href:'https://egosimulator.github.io/' },
  ],
  ExoGS: [
    { name:'AirExo-3', phase:'Capture', role:'Robot-isomorphic passive exoskeleton records aligned trajectories.', href:'https://arxiv.org/abs/2601.18629' },
    { name:'Editable 4D Gaussians', capability:'3D Gaussian Splatting', phase:'Appearance', role:'Represents captured robot, object, and scene appearance.', href:'https://github.com/zaixiabalala/ExoGS' },
    { name:'Robot-isomorphic retargeting', phase:'Retarget', role:'Transfers captured joints to the Flexiv target arm.', href:'https://arxiv.org/abs/2601.18629' },
    { name:'GaussianSim', phase:'Physics', role:'Replays and edits articulated Gaussian demonstrations.', href:'https://github.com/zaixiabalala/ExoGS' },
    { name:'Visuomotor policy training', phase:'Policy', role:'Learns from captured and augmented demonstrations.', href:'https://arxiv.org/abs/2601.18629' },
  ],
  GSWorld: [
    { name:'3D Gaussian Splatting', capability:'3D Gaussian Splatting', phase:'Appearance', role:'Captures photoreal scene appearance.', href:'https://3dgsworld.github.io/' },
    { name:'GSDF', phase:'Geometry', role:'Binds Gaussians to editable mesh surfaces.', href:'https://arxiv.org/abs/2510.20813' },
    { name:'Physics + GS renderer', phase:'Physics', role:'Runs closed-loop manipulation with rendered observations.', href:'https://3dgsworld.github.io/' },
    { name:'ACT', capability:'ACT', phase:'Policy', role:'Imitation-policy benchmark and DAgger adaptation.', href:'https://3dgsworld.github.io/' },
    { name:'π0', phase:'Policy', role:'Generalist-policy simulation benchmarking.', href:'https://3dgsworld.github.io/' },
    { name:'SAC', phase:'Policy', role:'Zero-shot sim-to-real visual reinforcement learning.', href:'https://3dgsworld.github.io/' },
  ],
  'RobotArena∞': [
    { name:'Scene reconstruction', phase:'Geometry', role:'Calibrates task layouts from demonstrations or user video.', href:'https://robotarenainf.github.io/' },
    { name:'Generated perturbation assets', phase:'Generate', role:'Creates controllable scene and object variations.', href:'https://arxiv.org/abs/2510.23571' },
    { name:'Genesis', phase:'Physics', role:'Executes perturbable evaluation arenas.', href:'https://github.com/offjangir/RobotArena' },
    { name:'Automated progress scorer', phase:'Evaluate', role:'Measures task progress without only binary success.', href:'https://robotarenainf.github.io/' },
    { name:'VLA policy suite', phase:'Policy', role:'Compares robustness, preferences, and sim–real ranking.', href:'https://arxiv.org/abs/2510.23571' },
  ],
  GaussGym: [
    { name:'Phone / dataset / generated-video ingestion', phase:'Capture', role:'Normalizes scans, posed datasets, handheld videos, and generated videos into one scene-building route.', href:'https://arxiv.org/html/2510.15352#S3' },
    { name:'VGGT', capability:'VGGT', phase:'Geometry', role:'Recovers cameras, dense points, depth, and normals from image sequences.', href:'https://arxiv.org/html/2510.15352#S3' },
    { name:'NKSR collision reconstruction', phase:'Collision geometry', role:'Converts oriented point evidence into the mesh used by the physics engine.', href:'https://arxiv.org/html/2510.15352#S3' },
    { name:'3D Gaussian Splatting', capability:'3D Gaussian Splatting', phase:'Appearance', role:'Represents terrain and visual semantics.', href:'https://arxiv.org/abs/2510.15352' },
    { name:'Aligned Gaussian / mesh world', phase:'Register', role:'Keeps the visual and collision representations in the same frame.', href:'https://arxiv.org/html/2510.15352#S3' },
    { name:'Vectorized Gaussian renderer', phase:'Appearance', role:'Renders 640×480 photoreal observations while thousands of environments step in parallel.', href:'https://github.com/escontra/gauss_gym' },
    { name:'Isaac Gym / Isaac Sim', phase:'Physics', role:'Runs 4,096 parallel locomotion environments synchronized with the renderer.', href:'https://arxiv.org/html/2510.15352#S3' },
    { name:'Pixel-based RL', phase:'Policy', role:'Learns locomotion and semantic navigation from RGB or depth.', href:'https://gauss-gym.com/' },
  ],
  VITRA: [
    { name:'Unscripted egocentric video pool', phase:'Capture', role:'Draws raw, unannotated activity video from Ego4D, EPIC-KITCHENS, EgoExo4D, and Something-Something-V2.', href:'https://arxiv.org/html/2510.21571#S3.SS4' },
    { name:'DroidCalib + MoGe-2 + DeepCalib', capability:'MoGe', phase:'Calibration', role:'Estimates camera intrinsics, detects moving/static-camera cases, and undistorts footage.', href:'https://arxiv.org/html/2510.21571#S3.SS1' },
    { name:'HaWoR + MANO', capability:'HaWoR', phase:'Hand recon', role:'Recovers per-frame wrist 6D pose and 15-joint articulated hand state.', href:'https://arxiv.org/html/2510.21571#S3.SS1' },
    { name:'Modified MegaSAM + MoGe-2', capability:'MegaSaM', phase:'Camera motion', role:'Recovers metric moving-camera poses and transforms hands into a stable world frame.', href:'https://arxiv.org/html/2510.21571#S3.SS1' },
    { name:'3D speed-minimum segmentation', phase:'Action segmentation', role:'Cuts long videos into atomic single- or dual-hand manipulation episodes without text labels.', href:'https://arxiv.org/html/2510.21571#S3.SS2' },
    { name:'GPT-4.1 trajectory captioning', phase:'Language', role:'Filters non-actions and produces imperative task labels from sampled frames with projected hand trajectories.', href:'https://arxiv.org/html/2510.21571#S3.SS3' },
    { name:'Camera-frame MANO action space', phase:'Retarget', role:'Represents wrist deltas and hand joints in a common 102-D two-hand interface, then maps the closest supported DoFs to XHand.', href:'https://arxiv.org/html/2510.21571#S4.SS1.SSS2' },
    { name:'PaliGemma-2 + causal DiT action expert', phase:'Policy', role:'Pretrains a 3B VLA on 1.22M human-hand episodes and fine-tunes it on embodiment-specific robot demonstrations.', href:'https://arxiv.org/html/2510.21571#S4.SS1.SSS1' },
    { name:'RealMan RM75 + XHand deployment', phase:'Deploy', role:'Executes camera-frame wrist and 12-DoF dexterous-hand action chunks on the physical robot.', href:'https://github.com/microsoft/VITRA#4-deployment-in-the-real-world' },
  ],
  'Real2Sim Soft Bodies': [
    { name:'3D Gaussian Splatting', capability:'3D Gaussian Splatting', phase:'Appearance', role:'Reconstructs the visual environment and camera domain.', href:'https://real2sim-eval.github.io/' },
    { name:'Color alignment', phase:'Appearance', role:'Fits simulator renders to real-camera color statistics.', href:'https://real2sim-eval.github.io/' },
    { name:'PhysTwin', capability:'PhysTwin', phase:'Physics', role:'Reconstructs deformable geometry and material parameters.', href:'https://real2sim-eval.github.io/' },
    { name:'Closed-loop policy evaluation', phase:'Policy', role:'Replays visuomotor checkpoints on plush, rope, and T-block tasks.', href:'https://real2sim-eval.github.io/' },
  ],
  VideoMimic: [
    { name:'SAM 2.1', capability:'SAM 2.1', phase:'Segment', role:'Produces sequential human masks.', href:'https://github.com/hongsukchoi/VideoMimic/blob/main/real2sim/docs/sequential_processing.md' },
    { name:'VIMO + ViTPose', phase:'Body recon', role:'Recovers human mesh and 2D keypoints.', href:'https://github.com/hongsukchoi/VideoMimic/blob/main/real2sim/docs/sequential_processing.md' },
    { name:'MegaSaM', capability:'MegaSaM', phase:'Geometry', role:'Reconstructs dynamic-camera world depth and trajectory.', href:'https://github.com/hongsukchoi/VideoMimic/blob/main/real2sim/docs/commands.md' },
    { name:'GeoCalib', capability:'GeoCalib', phase:'Pose', role:'Aligns gravity and camera calibration.', href:'https://github.com/hongsukchoi/VideoMimic/blob/main/real2sim/docs/sequential_processing.md' },
    { name:'BSTRO contact', phase:'Physics', role:'Estimates body–scene contact constraints.', href:'https://github.com/hongsukchoi/VideoMimic/blob/main/real2sim/docs/sequential_processing.md' },
    { name:'Robot motion retargeter', phase:'Retarget', role:'Fits reconstructed motion to Unitree G1.', href:'https://github.com/hongsukchoi/VideoMimic/blob/main/real2sim/docs/commands.md' },
    { name:'Physics-based imitation', phase:'Policy', role:'Learns a context-aware whole-body control policy.', href:'https://www.videomimic.net/' },
  ],
  'Scalable Real2Sim': [
    { name:'BundleSDF', phase:'Geometry', role:'Object-centric photometric reconstruction from robot capture.', href:'https://scalable-real2sim.github.io/' },
    { name:'Alpha-transparent reconstruction', phase:'Appearance', role:'Separates foreground occlusion from background.', href:'https://arxiv.org/abs/2503.00370' },
    { name:'CoACD', phase:'Geometry', role:'Produces simplified collision geometry from the visual mesh.', href:'https://scalable-real2sim.github.io/' },
    { name:'Joint-torque system ID', phase:'Physics', role:'Recovers mass, center of mass, and rotational inertia.', href:'https://scalable-real2sim.github.io/' },
    { name:'Drake + solver', phase:'Physics', role:'Builds and validates the simulation-ready asset.', href:'https://scalable-real2sim.github.io/' },
  ],
  ReBot: [
    { name:'Real robot trajectories', phase:'Capture', role:'Provide executable motion and camera-aligned task context.', href:'https://yuffish.github.io/rebot/' },
    { name:'Simulator trajectory replay', phase:'Physics', role:'Replays the source motion against new digital-cousin objects.', href:'https://arxiv.org/abs/2503.14526' },
    { name:'Object diversification', phase:'Generate', role:'Changes object geometry and appearance while preserving task structure.', href:'https://yuffish.github.io/rebot/' },
    { name:'Motion rendering + inpainting', phase:'Appearance', role:'Composites simulated robot/object changes into a real background.', href:'https://arxiv.org/abs/2503.14526' },
    { name:'Octo / OpenVLA post-training', capability:'Octo', phase:'Policy', role:'Learns from native and synthesized robot demonstrations.', href:'https://yuffish.github.io/rebot/' },
  ],
  'X-Sim': [
    { name:'RGB-D human demonstration', phase:'Capture', role:'Provides scene geometry and task-relevant object motion.', href:'https://portal-cornell.github.io/X-Sim/' },
    { name:'Photoreal simulator reconstruction', phase:'Geometry', role:'Builds a controllable scene and camera domain from the real video.', href:'https://arxiv.org/abs/2505.07096' },
    { name:'Object-tracking reward', phase:'Specify', role:'Translates observed task progress into a simulator reward.', href:'https://arxiv.org/abs/2505.07096' },
    { name:'Reinforcement learning', phase:'Policy', role:'Searches for actions under the reconstructed task constraints.', href:'https://portal-cornell.github.io/X-Sim/' },
    { name:'Diffusion-policy distillation', capability:'Diffusion Policy', phase:'Distil', role:'Compresses the simulator-trained behavior into a deployable visuomotor policy.', href:'https://arxiv.org/abs/2505.07096' },
    { name:'Online domain adaptation', phase:'Deploy', role:'Corrects residual appearance and dynamics mismatch on hardware.', href:'https://portal-cornell.github.io/X-Sim/' },
  ],
  'Re³Sim': [
    { name:'OpenMVS', phase:'Geometry', role:'Builds the collision and background scene mesh.', href:'https://github.com/InternRobotics/Re3Sim' },
    { name:'3D Gaussian Splatting', capability:'3D Gaussian Splatting', phase:'Appearance', role:'Provides the calibrated photoreal renderer.', href:'https://github.com/InternRobotics/Re3Sim' },
    { name:'Isaac Sim + PhysX', phase:'Physics', role:'Generates privileged manipulation trajectories.', href:'https://github.com/InternRobotics/Re3Sim' },
    { name:'ACT', capability:'ACT', phase:'Policy', role:'Trains visuomotor policies on synthetic trajectories.', href:'https://github.com/InternRobotics/Re3Sim' },
    { name:'DINOv2 encoder', phase:'Policy', role:'Encodes image observations for the ACT policy.', href:'https://xshenhan.github.io/Re3Sim/re3sim.pdf' },
  ],
  SplatSim: [
    { name:'3D Gaussian Splatting', capability:'3D Gaussian Splatting', phase:'Appearance', role:'Captures scene, object, and robot-link appearance.', href:'https://splatsim.github.io/' },
    { name:'Articulated splat transforms', phase:'Geometry', role:'Moves robot links and objects at simulator poses.', href:'https://splatsim.github.io/assets/splatsim_paper.pdf' },
    { name:'PyBullet', phase:'Physics', role:'Collects expert trajectories through planning or GELLO.', href:'https://splatsim.github.io/assets/splatsim_paper.pdf' },
    { name:'Diffusion Policy', capability:'Diffusion Policy', phase:'Policy', role:'Learns RGB-conditioned manipulation from rendered demonstrations.', href:'https://splatsim.github.io/assets/splatsim_paper.pdf' },
  ],
  RialTo: [
    { name:'Phone scan', phase:'Capture', role:'Builds task-specific scene geometry and object assets.', href:'https://real-to-sim-to-real.github.io/RialTo/' },
    { name:'Interactive digital twin', phase:'Physics', role:'Instantiates the scanned scene for resettable policy learning.', href:'https://arxiv.org/abs/2403.03949' },
    { name:'Real demonstrations', phase:'Data', role:'Supply sparse task examples on the physical robot.', href:'https://real-to-sim-to-real.github.io/RialTo/' },
    { name:'Inverse distillation', phase:'Retarget', role:'Maps real demonstration behavior into simulator supervision.', href:'https://arxiv.org/abs/2403.03949' },
    { name:'Robustifying RL', phase:'Policy', role:'Explores perturbations and learns recovery in the twin.', href:'https://real-to-sim-to-real.github.io/RialTo/' },
    { name:'Real deployment', phase:'Deploy', role:'Transfers the robustified policy back to hardware.', href:'https://real-to-sim-to-real.github.io/RialTo/' },
  ],
  Immediate3DGS: [
    { name:'Unordered image ingestion', phase:'Capture', role:'Accepts casual, unordered captures rather than requiring a single clean trajectory.', href:'https://github.com/graphdeco-inria/i3dgs' },
    { name:'Place-recognition matching', phase:'Match', role:'Finds fast cross-view correspondences and revisited regions.', href:'https://github.com/graphdeco-inria/i3dgs' },
    { name:'Cluster loop closure', phase:'Pose', role:'Detects and repairs drift across local reconstruction clusters.', href:'https://github.com/graphdeco-inria/i3dgs' },
    { name:'Graph-propagated correction', phase:'Fuse', role:'Distributes camera and scene corrections globally.', href:'https://github.com/graphdeco-inria/i3dgs' },
    { name:'Progressive Gaussian hierarchy', capability:'Immediate3DGS', phase:'Appearance', role:'Builds a scalable 3DGS scene with immediate viewing feedback.', href:'https://github.com/graphdeco-inria/i3dgs' },
  ],
  AnyRecon: [
    { name:'Sparse unordered captures', phase:'Capture', role:'Provide real anchor views with flexible cardinality and large viewpoint gaps.', href:'https://yutian10.github.io/AnyRecon/' },
    { name:'Persistent 3D geometry memory', capability:'AnyRecon', phase:'Geometry', role:'Stores the current global reconstruction across iterations.', href:'https://yutian10.github.io/AnyRecon/' },
    { name:'Geometry-driven view selection', phase:'Select', role:'Retrieves captured references relevant to the next region of the trajectory.', href:'https://yutian10.github.io/AnyRecon/' },
    { name:'Unordered contextual video diffusion', phase:'Generate', role:'Synthesizes consistent missing views conditioned on captures and rendered point clouds.', href:'https://yutian10.github.io/AnyRecon/' },
    { name:'Geometry memory update', phase:'Fuse', role:'Integrates generated evidence back into the persistent 3D state.', href:'https://yutian10.github.io/AnyRecon/' },
  ],
  'M³': [
    { name:'Monocular video', phase:'Capture', role:'Supplies an uncalibrated indoor or outdoor camera stream.', href:'https://city-super.github.io/M3/' },
    { name:'Pi3X dense matching', phase:'Match', role:'Processes historical keyframes with new frames to estimate dense correspondences.', href:'https://city-super.github.io/M3/' },
    { name:'Factor graph + keyframes', phase:'Track', role:'Selects informative frames and establishes pose constraints.', href:'https://city-super.github.io/M3/' },
    { name:'Joint global pose optimization', phase:'Pose', role:'Refines camera poses and cross-inference intrinsics consistently.', href:'https://arxiv.org/abs/2603.16844' },
    { name:'Motion Map', phase:'Filter', role:'Excludes dynamic regions from the static reconstruction.', href:'https://city-super.github.io/M3/' },
    { name:'Neural Gaussian / LOD mapper', capability:'M³', phase:'Appearance', role:'Initializes and jointly optimizes hierarchical Gaussians with camera poses.', href:'https://city-super.github.io/M3/' },
  ],
  'LiteReality-Agent': [
    { name:'LiteReality iOS scanner', phase:'Capture', role:'Exports posed RGB, LiDAR depth, ARKit cameras, and RoomPlan layout.', href:'https://litereality.github.io/Litereality-agent-site/' },
    { name:'Deterministic room initializer', phase:'Geometry', role:'Rebuilds walls, openings, and cameras into a blank room.', href:'https://litereality.github.io/Litereality-agent-site/' },
    { name:'Room.py scene program', capability:'LiteReality-Agent', phase:'World state', role:'Keeps geometry, materials, and articulation explicit and replayable in code.', href:'https://litereality.github.io/Litereality-agent-site/' },
    { name:'Edit → render → compare → critique', phase:'Author', role:'Lets the agent refine the program against captured evidence.', href:'https://litereality.github.io/Litereality-agent-site/' },
    { name:'Automatic quality gates', phase:'Validate', role:'Checks the authored result before export.', href:'https://litereality.github.io/Litereality-agent-site/' },
    { name:'Blender / glTF / simulator export', phase:'Export', role:'Ships an interactive, articulated graphics asset.', href:'https://litereality.github.io/Litereality-agent-site/' },
  ],
  LiteReality: [
    { name:'RGB-D indoor scan', phase:'Capture', role:'Provides room geometry, camera observations, and object evidence.', href:'https://litereality.github.io/' },
    { name:'Scene perception + parsing', phase:'Parse', role:'Detects room layout and object bounding boxes.', href:'https://litereality.github.io/' },
    { name:'Structured scene graph', capability:'LiteReality', phase:'World state', role:'Builds a coherent and physically plausible object arrangement.', href:'https://litereality.github.io/' },
    { name:'Identical-object clustering', phase:'Group', role:'Avoids reconstructing repeated assets independently.', href:'https://litereality.github.io/' },
    { name:'Hierarchical artistic-mesh retrieval', phase:'Geometry', role:'Matches compact, editable, articulated assets from a curated database.', href:'https://litereality.github.io/' },
    { name:'PBR material painting', phase:'Appearance', role:'Retrieves and optimizes spatially varying materials against observations.', href:'https://litereality.github.io/' },
    { name:'Procedural assembly + basic physics', phase:'Physics', role:'Instantiates an interactive graphics-ready environment.', href:'https://arxiv.org/abs/2507.02861' },
  ],
  'On-the-fly NVS': [
    { name:'Sequential unposed images', phase:'Capture', role:'Streams ordered photos or experimental phone video into reconstruction.', href:'https://github.com/graphdeco-inria/on-the-fly-nvs' },
    { name:'Fast pose initialization', phase:'Pose', role:'Bootstraps each incoming camera without offline COLMAP reconstruction.', href:'https://github.com/graphdeco-inria/on-the-fly-nvs' },
    { name:'Direct Gaussian sampling', phase:'Geometry', role:'Initializes scene primitives from the current visual evidence.', href:'https://github.com/graphdeco-inria/on-the-fly-nvs' },
    { name:'Scalable clustering + merging', capability:'On-the-fly NVS', phase:'Fuse', role:'Extends the Gaussian map over arbitrarily long sequences.', href:'https://github.com/graphdeco-inria/on-the-fly-nvs' },
    { name:'Optional fine-tuning', phase:'Refine', role:'Improves final appearance after the live reconstruction pass.', href:'https://github.com/graphdeco-inria/on-the-fly-nvs' },
    { name:'Local / network / web viewer', phase:'Inspect', role:'Provides capture-time feedback and post-reconstruction navigation.', href:'https://github.com/graphdeco-inria/on-the-fly-nvs' },
  ],
  'Teaching by Showing': [
    { name:'Human demonstration', phase:'Teach', role:'Replaces part of hand-written robot programming with observed examples.', href:'https://doi.org/10.1016/S1474-6670(17)45311-0' },
    { name:'Intention interpretation', capability:'Teaching by Showing', phase:'Interpret', role:'Infers which demonstrated elements specify the task.', href:'https://doi.org/10.1016/S1474-6670(17)45311-0' },
    { name:'Skill / feedback-law construction', phase:'Program', role:'Converts the interpretation into reusable robot behavior.', href:'https://doi.org/10.1016/S1474-6670(17)45311-0' },
    { name:'Execution + correction', phase:'Refine', role:'Uses feedback to repair the demonstrated program.', href:'https://doi.org/10.1016/S1474-6670(17)45311-0' },
  ],
  'One-Demonstration Learning': [
    { name:'Single demonstration', phase:'Observe', role:'Provides a trajectory and an initial hypothesis about task intent.', href:'https://doi.org/10.1109/ROBOT.1997.614389' },
    { name:'Task criterion', phase:'Infer', role:'Separates the desired outcome from literal trajectory copying.', href:'https://doi.org/10.1109/ROBOT.1997.614389' },
    { name:'Robot execution model', phase:'Model', role:'Predicts how the target embodiment will realize candidate motions.', href:'https://doi.org/10.1109/ROBOT.1997.614389' },
    { name:'Performance optimization', capability:'One-Demonstration Learning', phase:'Learn', role:'Improves the motion for the physical robot and objective.', href:'https://doi.org/10.1109/ROBOT.1997.614389' },
  ],
  'Gleicher Motion Retargeting': [
    { name:'Source motion', phase:'Input', role:'Provides the original character animation.', href:'https://graphics.cs.wisc.edu/Papers/1998/Gle98/' },
    { name:'Spacetime constraints', capability:'Constraint-based retargeting', phase:'Specify', role:'Marks positions, contacts, and timing that must survive morphology change.', href:'https://graphics.cs.wisc.edu/Papers/1998/Gle98/' },
    { name:'Whole-motion optimization', phase:'Retarget', role:'Adapts joint motion to the target proportions while preserving selected invariants.', href:'https://graphics.cs.wisc.edu/Papers/1998/Gle98/' },
  ],
  'Schaal Imitation Framework': [
    { name:'Action perception', phase:'Observe', role:'Extracts behaviorally relevant evidence from a demonstrator.', href:'https://pubmed.ncbi.nlm.nih.gov/10354577/' },
    { name:'Correspondence', capability:'Schaal Imitation Framework', phase:'Align', role:'Relates observed biological action to robot coordinates.', href:'https://pubmed.ncbi.nlm.nih.gov/10354577/' },
    { name:'Movement representation', phase:'Encode', role:'Stores reusable motion structure instead of raw samples alone.', href:'https://pubmed.ncbi.nlm.nih.gov/10354577/' },
    { name:'Motor learning', phase:'Policy', role:'Turns the representation into executable and improvable behavior.', href:'https://pubmed.ncbi.nlm.nih.gov/10354577/' },
  ],
  'Choi–Ko Online Retargeting': [
    { name:'Source skeleton motion', phase:'Input', role:'Supplies target end-effector trajectories over time.', href:'https://doi.org/10.1002/1099-1778(200012)11:5%3C223::AID-VIS236%3E3.0.CO;2-5' },
    { name:'Anthropometric mapping', phase:'Align', role:'Relates source and target bodies with different proportions.', href:'https://doi.org/10.1002/1099-1778(200012)11:5%3C223::AID-VIS236%3E3.0.CO;2-5' },
    { name:'Inverse-rate controller', capability:'Online motion retargeting', phase:'Retarget', role:'Solves target joint velocities online to preserve motion detail.', href:'https://doi.org/10.1002/1099-1778(200012)11:5%3C223::AID-VIS236%3E3.0.CO;2-5' },
  ],
  'Dynamic Movement Primitives': [
    { name:'Demonstrated trajectory', phase:'Observe', role:'Provides the motion to be encoded.', href:'https://doi.org/10.1109/ROBOT.2002.1014739' },
    { name:'Stable attractor', phase:'Encode', role:'Defines convergence and supports perturbation recovery.', href:'https://doi.org/10.1109/ROBOT.2002.1014739' },
    { name:'Learned forcing term', capability:'Dynamic Movement Primitives', phase:'Shape', role:'Captures the demonstrated movement profile.', href:'https://doi.org/10.1109/ROBOT.2002.1014739' },
    { name:'Goal / timing modulation', phase:'Adapt', role:'Reuses the primitive at new goals and speeds.', href:'https://doi.org/10.1109/ROBOT.2002.1014739' },
  ],
  'Nakaoka Dance Transfer': [
    { name:'Dance motion capture', phase:'Capture', role:'Records human whole-body and foot motion.', href:'https://s-nakaoka.github.io/' },
    { name:'Motion segmentation', phase:'Parse', role:'Decomposes the dance into transferable movement units.', href:'https://s-nakaoka.github.io/' },
    { name:'Leg / whole-body primitives', capability:'Nakaoka dance transfer', phase:'Retarget', role:'Maps symbolic dance structure to the humanoid.', href:'https://s-nakaoka.github.io/' },
    { name:'Balance + contact adjustment', phase:'Physics', role:'Repairs center-of-mass and foot constraints for biped execution.', href:'https://s-nakaoka.github.io/' },
    { name:'Physical humanoid execution', phase:'Deploy', role:'Performs the transferred dance on hardware.', href:'https://s-nakaoka.github.io/' },
  ],
  'Dariush Markerless Transfer': [
    { name:'Markerless human tracking', phase:'Perceive', role:'Produces online motion descriptors from vision.', href:'https://doi.org/10.1109/IROS.2008.4651104' },
    { name:'Task-space correspondence', phase:'Align', role:'Maps human motion evidence to humanoid objectives.', href:'https://doi.org/10.1109/IROS.2008.4651104' },
    { name:'Joint / collision / balance constraints', capability:'Dariush constrained transfer', phase:'Constrain', role:'Keeps online imitation within robot-safe limits.', href:'https://doi.org/10.1109/IROS.2008.4651104' },
    { name:'Whole-body controller', phase:'Deploy', role:'Executes the feasible imitation on the humanoid.', href:'https://doi.org/10.1109/IROS.2008.4651104' },
  ],
  'Argall LfD Design Space': [
    { name:'Demonstration source + recording', phase:'Acquire', role:'Defines who teaches and which signals the robot observes.', href:'https://www.cs.cmu.edu/~mmv/papers/09ras-survey.pdf' },
    { name:'Correspondence choice', phase:'Align', role:'Locates embodiment mismatch in data or representation.', href:'https://www.cs.cmu.edu/~mmv/papers/09ras-survey.pdf' },
    { name:'Policy derivation', capability:'Argall LfD Taxonomy', phase:'Learn', role:'Organizes mapping, model, and policy-learning approaches.', href:'https://www.cs.cmu.edu/~mmv/papers/09ras-survey.pdf' },
    { name:'Refinement + evaluation', phase:'Assess', role:'Separates initial imitation from improvement and validation.', href:'https://www.cs.cmu.edu/~mmv/papers/09ras-survey.pdf' },
  ],
  SMPL: [
    { name:'Shape parameters', phase:'Shape', role:'Represent subject-specific human morphology.', href:'https://smpl.is.tue.mpg.de/' },
    { name:'Pose parameters', phase:'Pose', role:'Drive the articulated human skeleton.', href:'https://smpl.is.tue.mpg.de/' },
    { name:'Pose blend shapes + skinning', capability:'SMPL', phase:'Mesh', role:'Produce an animatable human surface for reconstruction and retargeting.', href:'https://is.mpg.de/ps/en/publications/smpl-2015' },
    { name:'Robot correspondence downstream', phase:'Retarget', role:'Supplies human joints and surface anchors to later transfer methods.', href:'https://human2humanoid.com/' },
  ],
  DeepMimic: [
    { name:'Reference motion clips', phase:'Motion', role:'Define the style and phase of the desired skill.', href:'https://xbpeng.github.io/projects/DeepMimic/' },
    { name:'Bullet physics character', phase:'Physics', role:'Provides contacts, perturbations, and actuation constraints.', href:'https://github.com/xbpeng/DeepMimic' },
    { name:'Imitation + task rewards', phase:'Objective', role:'Trade off motion fidelity with task completion.', href:'https://arxiv.org/abs/1804.02717' },
    { name:'PPO skill policy', capability:'DeepMimic', phase:'Policy', role:'Learns robust control from the reference and simulated dynamics.', href:'https://github.com/xbpeng/DeepMimic' },
  ],
  AnyTeleop: [
    { name:'Camera / glove hand tracking', phase:'Capture', role:'Streams human wrist and finger motion.', href:'https://yzqin.github.io/anyteleop/' },
    { name:'Arm task-space mapping', phase:'Arm IK', role:'Converts human wrist pose to a target robot arm command.', href:'https://yzqin.github.io/anyteleop/' },
    { name:'Vector-based hand retargeting', capability:'dex-retargeting', phase:'Hand IK', role:'Preserves fingertip relations across different hand morphologies.', href:'https://github.com/dexsuite/dex-retargeting' },
    { name:'Cross-embodiment adapter', capability:'AnyTeleop', phase:'Interface', role:'Normalizes multiple robot, camera, and simulator configurations.', href:'https://yzqin.github.io/anyteleop/' },
  ],
  H2O: [
    { name:'AMASS SMPL corpus', capability:'SMPL', phase:'Human motion', role:'Supplies roughly 13k already reconstructed human motion sequences; H2O does not begin from raw scene video.', href:'https://arxiv.org/html/2403.04436#S3.SS2' },
    { name:'12-joint SMPL–H1 correspondence', phase:'Correspondence', role:'Pairs shared shoulders, elbows, wrists, hips, knees, and ankles across the two kinematic trees.', href:'https://arxiv.org/html/2403.04436#S4.SS1' },
    { name:'SMPL shape fitting', phase:'Morphology fit', role:'Optimizes one SMPL body shape whose rest-pose proportions resemble H1, reducing foot and end-effector artifacts.', href:'https://arxiv.org/html/2403.04436#S4.SS1' },
    { name:'Position-based IK optimization', capability:'H2O / OmniH2O', phase:'Kinematic retarget', role:'Uses Adam to minimize the 12 corresponding world-position errors while preserving end-effector motion patterns.', href:'https://arxiv.org/html/2403.04436#S4.SS1' },
    { name:'Heuristic safety filtering', phase:'Filter', role:'Removes clearly unsafe source clips such as ground-sitting before simulation.', href:'https://arxiv.org/html/2403.04436#S4.SS1' },
    { name:'Privileged imitation policy', phase:'Sim-to-data', role:'Attempts all roughly 10k retargeted motions in simulation with full rigid-body state and no domain randomization.', href:'https://arxiv.org/html/2403.04436#S4.SS2' },
    { name:'Trackability filter', phase:'Dynamic feasibility', role:'Keeps about 8.5k motions that the privileged controller can physically track; failure is used as a feasibility label.', href:'https://arxiv.org/html/2403.04436#S4.SS2' },
    { name:'Real-observable PPO tracker', phase:'Policy', role:'Learns 19 joint-position targets from proprioception and eight sparse human keypoints with sim-to-real randomization.', href:'https://arxiv.org/html/2403.04436#S5' },
    { name:'RGB pose → H1 deployment', phase:'Deploy', role:'An off-the-shelf human pose estimator supplies live keypoint goals to the physical H1 controller.', href:'https://arxiv.org/html/2403.04436#S6.SS2' },
  ],
  OmniH2O: [
    { name:'Large human-motion corpus', phase:'Data', role:'Supplies diverse whole-body behaviors.', href:'https://omni.human2humanoid.com/' },
    { name:'Retarget + feasibility filter', capability:'H2O / OmniH2O', phase:'Retarget', role:'Maps motions and rejects references the robot cannot track.', href:'https://omni.human2humanoid.com/' },
    { name:'Privileged teacher distillation', phase:'Policy', role:'Trains a general controller from simulated full-state supervision.', href:'https://arxiv.org/abs/2406.08858' },
    { name:'Sparse real-time command', phase:'Deploy', role:'Controls the real humanoid from limited human pose signals.', href:'https://omni.human2humanoid.com/' },
  ],
  HumanPlus: [
    { name:'Human video / shadowing', phase:'Capture', role:'Collects whole-body task demonstrations from people.', href:'https://humanoid-ai.github.io/' },
    { name:'Motion retargeting', capability:'HumanPlus', phase:'Retarget', role:'Maps observed behavior to the H1 body and hands.', href:'https://arxiv.org/abs/2406.10454' },
    { name:'Physics-based tracking policy', phase:'Policy', role:'Learns robust execution under simulated dynamics.', href:'https://github.com/MarkFzp/humanplus' },
    { name:'Autonomous skill learning', phase:'Deploy', role:'Uses the collected robot experience for downstream task policies.', href:'https://humanoid-ai.github.io/' },
  ],
  'GMR Retargeting': [
    { name:'SMPL / BVH / XR motion', phase:'Input', role:'Accepts common human-motion formats and live tracking.', href:'https://github.com/YanjieZe/GMR' },
    { name:'Configurable keypoint map', phase:'Align', role:'Selects human and robot anchors plus task weights.', href:'https://github.com/YanjieZe/GMR' },
    { name:'Multi-objective IK', capability:'GMR', phase:'Retarget', role:'Solves target robot joints at interactive CPU rates.', href:'https://github.com/YanjieZe/GMR' },
    { name:'MuJoCo validation', phase:'Inspect', role:'Visualizes and checks the resulting robot motion.', href:'https://github.com/YanjieZe/GMR' },
  ],
  'SPIDER Retargeting': [
    { name:'Initial motion correspondence', capability:'GMR', phase:'Seed', role:'Creates a kinematic starting trajectory.', href:'https://github.com/facebookresearch/spider' },
    { name:'Physics-informed sampling', capability:'SPIDER', phase:'Search', role:'Explores trajectory variations under robot and contact dynamics.', href:'https://github.com/facebookresearch/spider' },
    { name:'Feasibility scoring + refinement', phase:'Physics', role:'Rejects or repairs dynamically invalid demonstrations.', href:'https://arxiv.org/abs/2511.09484' },
    { name:'Policy-ready motion set', phase:'Policy', role:'Exports feasible trajectories for imitation and deployment.', href:'https://github.com/facebookresearch/spider' },
  ],
  UMR: [
    { name:'Human + robot point clouds', phase:'Geometry', role:'Represent both morphologies without a shared skeleton.', href:'https://arxiv.org/abs/2609.02134' },
    { name:'Dense learned correspondence', capability:'UMR', phase:'Align', role:'Predicts cross-morphology matches instead of hand-authored sparse keypoints.', href:'https://arxiv.org/abs/2609.02134' },
    { name:'Motion optimization', phase:'Retarget', role:'Uses correspondence to fit robot motion to human behavior.', href:'https://arxiv.org/abs/2609.02134' },
    { name:'Physical plausibility evaluation', phase:'Validate', role:'Checks the output under reported robot constraints.', href:'https://arxiv.org/abs/2609.02134' },
  ],
  EmbodMocap: [
    { name:'Single-iPhone RGB-D + IMU scan', phase:'Scene capture', role:'Establishes a metric, gravity-aligned reference environment.', href:'https://arxiv.org/html/2602.23205v2#S3.SS1' },
    { name:'SpectacularAI + refined depth + TSDF', phase:'Geometry', role:'Selects keyframes and fuses a dense global scene mesh.', href:'https://arxiv.org/html/2602.23205v2#S3.SS1' },
    { name:'Dual synchronized iPhone RGB-D', phase:'Motion capture', role:'Records the human from two moving viewpoints in the same environment.', href:'https://arxiv.org/html/2602.23205v2#S3.SS2' },
    { name:'YOLO + ViTPose + SAM2 + VIMO', phase:'Human recon', role:'Extracts people, keypoints, masks, depth, and initial SMPL state.', href:'https://arxiv.org/html/2602.23205v2#S3.SS2' },
    { name:'COLMAP + multi-view calibration', phase:'Align', role:'Registers both camera trajectories into the metric scene world frame.', href:'https://arxiv.org/html/2602.23205v2#S3.SS3' },
    { name:'World-space SMPLify', capability:'EmbodMocap', phase:'Motion', role:'Triangulates keypoints and optimizes temporally coherent world-aligned SMPL motion.', href:'https://arxiv.org/html/2602.23205v2#S3.SS4' },
    { name:'Isaac Gym / BeyondMimic RL', phase:'Policy', role:'Trains scene-aware character skills and a domain-randomized robot tracker.', href:'https://arxiv.org/html/2602.23205v2#S5.SS3' },
    { name:'High Torque Hi humanoid', phase:'Deploy', role:'Executes captured locomotion and ground-contact-rich cartwheels on hardware.', href:'https://arxiv.org/html/2602.23205v2#S5.SS3' },
  ],
  HumanX: [
    { name:'Monocular iPhone interaction video', phase:'Capture', role:'Provides one task example with body and object interaction evidence.', href:'https://arxiv.org/html/2602.02473v1#S3' },
    { name:'GVHMR', phase:'Body recon', role:'Recovers world-space SMPL root and joint motion from the human video.', href:'https://arxiv.org/html/2602.02473v1#S3.SS1' },
    { name:'GMR keypoints + scaling + IK', capability:'GMR', phase:'Retarget', role:'Maps human motion to the target humanoid joint trajectory.', href:'https://arxiv.org/html/2602.02473v1#S3.SS1' },
    { name:'SAM 3D object asset', capability:'SAM 3D Objects', phase:'Object', role:'Recovers the interacting object mesh and initial anchor-relative pose.', href:'https://arxiv.org/html/2602.02473v1#S3.SS2' },
    { name:'Contact anchors + force closure', capability:'HumanX', phase:'Physics', role:'Preserves cross-embodiment interaction semantics and repairs contact poses.', href:'https://arxiv.org/html/2602.02473v1#S3.SS2' },
    { name:'Isaac Gym non-contact rollout', phase:'Dynamics', role:'Synthesizes plausible pre- and post-contact object trajectories.', href:'https://arxiv.org/html/2602.02473v1#S3.SS2' },
    { name:'XGen object / trajectory augmentation', phase:'Augment', role:'Expands each demonstration across object states and geometry.', href:'https://arxiv.org/html/2602.02473v1#S3.SS3' },
    { name:'XMimic teacher → BC student', phase:'Policy', role:'Learns interaction imitation with privileged state, then distils to deployable observations.', href:'https://arxiv.org/html/2602.02473v1#S4' },
    { name:'Unitree G1', phase:'Deploy', role:'Runs ten zero-shot interaction skills across five domains.', href:'https://wyhuai.github.io/human-x/' },
  ],
  FunREC: [
    { name:'Egocentric RGB-D interaction video', phase:'Capture', role:'Records real human manipulation and articulated state changes in the wild.', href:'https://functionalscenes.github.io/' },
    { name:'Part discovery + segmentation', phase:'Segment', role:'Finds movable components without CAD priors or controlled multi-state capture.', href:'https://arxiv.org/abs/2604.05621' },
    { name:'Kinematics + 4D tracking', phase:'Motion', role:'Estimates joint parameters and the pose of each part at every time step.', href:'https://functionalscenes.github.io/' },
    { name:'Canonical geometry completion', phase:'Geometry', role:'Reconstructs static and moving meshes, including newly exposed interiors.', href:'https://functionalscenes.github.io/' },
    { name:'Functional scene state', capability:'FunREC', phase:'World state', role:'Binds parts, joints, trajectories, contacts, and affordances into one digital twin.', href:'https://functionalscenes.github.io/' },
    { name:'URDF / USD → Isaac Sim', phase:'Simulate', role:'Exports articulated assets that can be force-tested in a physics engine.', href:'https://functionalscenes.github.io/' },
    { name:'Contact-guided Spot transfer', phase:'Deploy', role:'Maps the human interaction trajectory to a Boston Dynamics Spot with Arm.', href:'https://functionalscenes.github.io/' },
  ],
  REACT3D: [
    { name:'Static reconstructed 3D scene', phase:'Input', role:'Starts from abundant but non-interactive indoor geometry.', href:'https://react3d.github.io/' },
    { name:'Openable-object detection', phase:'Detect', role:'Uses open-vocabulary evidence to locate candidate articulated objects.', href:'https://react3d.github.io/' },
    { name:'Movable-part segmentation', phase:'Segment', role:'Extracts doors, drawers, and other moving submeshes.', href:'https://react3d.github.io/' },
    { name:'Joint + hidden-geometry recovery', capability:'REACT3D', phase:'Articulate', role:'Infers kinematic type/axis and completes surfaces occluded in the closed state.', href:'https://github.com/troyehuang/REACT3D' },
    { name:'Interactive scene assembly', phase:'Compile', role:'Reintegrates articulated assets into consistent background geometry.', href:'https://react3d.github.io/' },
    { name:'ROS / Isaac Sim / PyBullet', phase:'Simulate', role:'Exports widely supported interactive representations for downstream tasks.', href:'https://react3d.github.io/' },
  ],
  GenRec: [
    { name:'Sparse posed images', phase:'Input', role:'Provides observed appearance, source cameras, and target viewpoints.', href:'https://arxiv.org/abs/2608.17832' },
    { name:'Monocular depth + reprojection', phase:'Geometry', role:'Warps RGB and scene coordinates into each target camera.', href:'https://arxiv.org/abs/2608.17832' },
    { name:'Observation mask', phase:'Route', role:'Separates pixels supported by evidence from pixels requiring plausible completion.', href:'https://arxiv.org/abs/2608.17832' },
    { name:'Reconstruct / generate split', capability:'GenRec', phase:'Synthesize', role:'Gates losses and gradient flow between deterministic fidelity and generative uncertainty.', href:'https://arxiv.org/abs/2608.17832' },
    { name:'Pixel-space refinement', phase:'Refine', role:'Restores high-frequency detail in evidence-backed regions.', href:'https://arxiv.org/abs/2608.17832' },
  ],
  EgoTrack3D: [
    { name:'Egocentric RGB + 2D masks', phase:'Observe', role:'Supplies moving-camera object observations under occlusion.', href:'https://arxiv.org/abs/2608.08016' },
    { name:'3D lifting', phase:'Geometry', role:'Places segmented evidence into a shared global coordinate frame.', href:'https://arxiv.org/abs/2608.08016' },
    { name:'Point motion scoring', phase:'Motion', role:'Separates static from moving object evidence.', href:'https://arxiv.org/abs/2608.08016' },
    { name:'Voxel association + merging', capability:'EgoTrack3D', phase:'Fuse', role:'Maintains persistent identities and scene state over time.', href:'https://arxiv.org/abs/2608.08016' },
    { name:'Dynamic 3D object map', phase:'Output', role:'Exposes a structured state for downstream reasoning or real2sim authoring.', href:'https://arxiv.org/abs/2608.08016' },
  ],
  VidMap: [
    { name:'Long uncalibrated video', phase:'Input', role:'Accepts unconstrained sequences and extracted frame directories.', href:'https://github.com/cvg/vidmap' },
    { name:'Dense temporal tracks', phase:'Match', role:'Propagates correspondences through adjacent keyframes and extreme motion.', href:'https://github.com/cvg/vidmap' },
    { name:'Loop closure', phase:'Associate', role:'Uses temporal order and wide-baseline matching to reject visual aliases.', href:'https://github.com/cvg/vidmap' },
    { name:'Metric depth prior', phase:'Scale', role:'Anchors the otherwise scale-ambiguous video reconstruction.', href:'https://arxiv.org/abs/2607.27194' },
    { name:'Global COLMAP optimization', capability:'VidMap', phase:'Solve', role:'Jointly estimates intrinsics, metric poses, and a sparse 3D map.', href:'https://github.com/cvg/vidmap' },
  ],
  AINA: [
    { name:'Aria Gen 2 demonstrations', capability:'Project Aria Tools', phase:'Capture', role:'Records RGB, stereo views, head pose, and onboard 3D hand pose anywhere.', href:'https://github.com/facebookresearch/AINA' },
    { name:'Object tracking + FoundationStereo', phase:'Geometry', role:'Lifts prompted 2D object tracks into scene-aligned 3D points.', href:'https://aina-robot.github.io/' },
    { name:'One in-scene human anchor', phase:'Align', role:'Maps demonstrations from arbitrary worlds into the robot deployment frame.', href:'https://github.com/facebookresearch/AINA' },
    { name:'Object + fingertip point tokens', phase:'Represent', role:'Provides a compact human/robot-shared interaction interface.', href:'https://aina-robot.github.io/' },
    { name:'Point trajectory policy', capability:'AINA', phase:'Learn', role:'Predicts future fingertip motion from point histories with no robot data or simulation.', href:'https://github.com/facebookresearch/AINA' },
    { name:'Kinova + Ability Hand', phase:'Deploy', role:'Executes nine multi-finger manipulation tasks on real hardware.', href:'https://aina-robot.github.io/' },
  ],
  HDMI: [
    { name:'Monocular human HOI video', phase:'Capture', role:'Provides unconstrained body and object interaction motion.', href:'https://hdmi-humanoid.github.io/' },
    { name:'GVHMR → GMR / LocoMujoco', phase:'Retarget', role:'Converts human motion into G1 body and joint states.', href:'https://github.com/LeCAR-Lab/HDMI' },
    { name:'Object trajectory extraction', phase:'Object', role:'Appends synchronized object pose and velocity to the robot reference.', href:'https://github.com/LeCAR-Lab/HDMI' },
    { name:'Unified robot–object tracking', capability:'HDMI', phase:'Physics', role:'Uses residual actions and general interaction rewards to co-track both entities.', href:'https://github.com/LeCAR-Lab/HDMI' },
    { name:'Isaac Sim / Isaac Lab RL', phase:'Learn', role:'Trains teacher and deployable policies under simulated contacts.', href:'https://github.com/LeCAR-Lab/HDMI' },
    { name:'Unitree G1', phase:'Deploy', role:'Runs six zero-shot real-world loco-manipulation tasks.', href:'https://hdmi-humanoid.github.io/' },
  ],
  'World Labs Atlas': [
    { name:'Text / images / video / 3D', phase:'Context', role:'Combines heterogeneous observations in one spatial context.', href:'https://www.worldlabs.ai/blog/atlas' },
    { name:'Omni diffusion transformer', capability:'World Labs Atlas', phase:'Model', role:'Autoregressively generates spatially consistent 2D, depth, video, and explicit 3D outputs.', href:'https://www.worldlabs.ai/blog/atlas' },
    { name:'Spatial reconstruction', phase:'Geometry', role:'Builds explicit point-cloud or 3DGS worlds from sparse captures.', href:'https://www.worldlabs.ai/blog/atlas' },
    { name:'Robot-view RGB + depth', phase:'Simulate', role:'Renders body-mounted sensor observations along robot trajectories.', href:'https://www.worldlabs.ai/blog/atlas' },
    { name:'Space-time variation', phase:'Dynamics', role:'Synthesizes rigid, articulated, and deformable interaction variations in the preview.', href:'https://www.worldlabs.ai/blog/atlas' },
  ],
  'World Labs R2S2R': [
    { name:'Physical task capture', phase:'Real', role:'Records robots, sensors, environments, objects, and interactions.', href:'https://www.worldlabs.ai/blog/real-to-sim-to-real' },
    { name:'Task-aligned reconstruction', phase:'Real2Sim', role:'Preserves observations and dynamics relevant to the target policy.', href:'https://www.worldlabs.ai/blog/real-to-sim-to-real' },
    { name:'Controllable world variants', capability:'World Labs R2S2R', phase:'Scale', role:'Varies physics, clutter, appearance, camera, object state, and robot state.', href:'https://www.worldlabs.ai/blog/real-to-sim-to-real' },
    { name:'Policy train + evaluate', phase:'Sim', role:'Uses generated experience to learn policies and map failures before hardware tests.', href:'https://www.worldlabs.ai/blog/real-to-sim-to-real' },
    { name:'Hardware validation loop', phase:'Sim2Real', role:'Checks transfer and policy ranking, then feeds real outcomes back into the world model.', href:'https://www.worldlabs.ai/blog/real-to-sim-to-real' },
  ],
  'Masked Visual Actions': [
    { name:'Reference image', phase:'Scene', role:'Defines the appearance and initial state for rollout.', href:'https://masked-visual-actions.github.io/' },
    { name:'Masked entity motion', capability:'Masked Visual Actions', phase:'Action', role:'Encodes robot or desired object trajectories directly in pixel space.', href:'https://masked-visual-actions.github.io/' },
    { name:'Video world model', phase:'Forward', role:'Predicts the scene response to a revealed robot-motion action.', href:'https://arxiv.org/abs/2607.19343' },
    { name:'Inverse motion synthesis', phase:'Inverse', role:'Generates robot behavior consistent with a desired object-motion mask.', href:'https://masked-visual-actions.github.io/' },
    { name:'Planning + policy evaluation', phase:'Decide', role:'Ranks candidates and predicts execution outcomes without running every policy in reality.', href:'https://masked-visual-actions.github.io/' },
  ],
  'World from Motion': [
    { name:'Monocular dynamic video', phase:'Capture', role:'Provides an incomplete moving-camera view of a dynamic scene.', href:'https://arxiv.org/abs/2607.01202' },
    { name:'Initial dynamic 3DGS', phase:'Scaffold', role:'Stores persistent geometry, appearance, and estimated scene motion.', href:'https://research.nvidia.com/labs/amri/projects/world-from-motion/' },
    { name:'Camera-controlled video prior', phase:'Generate', role:'Samples consistent observations from new dynamic viewpoints.', href:'https://research.nvidia.com/labs/amri/projects/world-from-motion/' },
    { name:'Reconstruction guidance', phase:'Constrain', role:'Conditions generation on dense scaffold renderings to limit drift and hallucination.', href:'https://arxiv.org/abs/2607.01202' },
    { name:'Distil into persistent 4DGS', capability:'World from Motion', phase:'Fuse', role:'Writes completed appearance and improved 3D motion back into one renderable representation.', href:'https://research.nvidia.com/labs/amri/projects/world-from-motion/' },
  ],
  OmniRetarget: [
    { name:'Human + object / terrain motion', phase:'Input', role:'Provides contact-rich behavior and its surrounding geometry.', href:'https://omniretarget.github.io/' },
    { name:'Interaction mesh', phase:'Represent', role:'Encodes spatial and contact relations among agent, terrain, and objects.', href:'https://arxiv.org/abs/2509.26633' },
    { name:'Laplacian + kinematic optimization', capability:'OmniRetarget', phase:'Retarget', role:'Preserves interaction while preventing penetration and foot skating.', href:'https://omniretarget.github.io/' },
    { name:'Embodiment / scene augmentation', phase:'Scale', role:'Changes robot, terrain, object pose, and object size from each source motion.', href:'https://omniretarget.github.io/' },
    { name:'Shared-reward physics RL', phase:'Policy', role:'Tracks diverse outputs with five rewards and simple domain randomization.', href:'https://omniretarget.github.io/' },
    { name:'Unitree G1', phase:'Deploy', role:'Executes parkour and loco-manipulation skills up to 30 seconds.', href:'https://omniretarget.github.io/' },
  ],
  'μ₀': [
    { name:'Action-free human + robot video', phase:'Pretrain data', role:'Supplies cross-embodiment interaction without low-level action labels.', href:'https://mu0-wm.github.io/' },
    { name:'Semantic trace extraction', phase:'Represent', role:'Tracks task-relevant hands, objects, tools, and contact regions in 3D.', href:'https://mu0-wm.github.io/' },
    { name:'3D trace world model', capability:'μ₀', phase:'Forecast', role:'Predicts embodiment-agnostic future interaction motion.', href:'https://github.com/Yoonkyo/mu0' },
    { name:'Action expert', phase:'Decode', role:'Turns the forecast trace into controls for a target robot.', href:'https://mu0-wm.github.io/' },
    { name:'RoboCasa365 + UR3', phase:'Evaluate', role:'Tests eight simulated and three physical manipulation tasks.', href:'https://mu0-wm.github.io/' },
  ],
  HumanEgo: [
    { name:'Aria egocentric demonstrations', capability:'Project Aria Tools', phase:'Capture', role:'Provides RGB, calibrated SLAM, and 3D hand poses from minutes of human data.', href:'https://humanego-ai.github.io/' },
    { name:'Arm inpainting + object pose', phase:'Perception', role:'Reduces the visual embodiment gap and identifies task entities.', href:'https://humanego-ai.github.io/' },
    { name:'Interaction-Centric Tokens', phase:'Represent', role:'Expresses hand/object 6D poses relative to other entities, not the camera or robot.', href:'https://humanego-ai.github.io/' },
    { name:'Flow matching + auxiliary futures', capability:'HumanEgo', phase:'Learn', role:'Predicts actions, object motion, image traces, and latent scene evolution.', href:'https://arxiv.org/abs/2605.24934' },
    { name:'Parallel-jaw robot transfer', phase:'Deploy', role:'Generalizes zero-shot across robots, cameras, scenes, and object placements.', href:'https://humanego-ai.github.io/' },
  ],
  TraceGen: [
    { name:'Heterogeneous video pool', phase:'Data', role:'Mixes humans and robots across tasks, scenes, and bodies.', href:'https://tracegen.github.io/' },
    { name:'TraceForge-123K', phase:'Normalize', role:'Converts 123k videos into 1.8M observation–trace–language triplets.', href:'https://tracegen.github.io/' },
    { name:'3D trace-space world model', capability:'TraceGen', phase:'Pretrain', role:'Learns a compact appearance-independent motion prior.', href:'https://github.com/Yoonkyo/TraceGen' },
    { name:'Five target videos', phase:'Adapt', role:'Warms the prior for a new robot or uses five human phone demonstrations.', href:'https://tracegen.github.io/' },
    { name:'Real robot policy', phase:'Deploy', role:'Executes four garment, insertion, sweeping, and placement tasks.', href:'https://tracegen.github.io/' },
  ],
  MicroDuck: [
    { name:'Onshape-to-robot export', phase:'Model', role:'Converts the designed mechanism into an MJCF robot model; geometry originates in CAD, not a real-scene scan.', href:'https://github.com/pollen-robotics/microduck_rl' },
    { name:'BAM actuator model', phase:'Identify / engineer', role:'Models Dynamixel XL330 voltage, back-EMF, Coulomb, Stribeck, and load-dependent friction behavior.', href:'https://github.com/pollen-robotics/microduck_rl' },
    { name:'Backlash + latency model', phase:'Align', role:'Adds configurable ±1° joint backlash, delayed commands, and encoder readings after backlash.', href:'https://github.com/pollen-robotics/microduck_rl' },
    { name:'Dynamics randomization', phase:'Robustify', role:'Varies battery voltage, voltage sag, latency, and contact/friction parameters to reduce sensitivity to model error.', href:'https://github.com/pollen-robotics/microduck_rl' },
    { name:'mjlab / MuJoCo Warp', phase:'Simulate', role:'Runs 4,096 parallel environments for contact-rich whole-body task learning.', href:'https://github.com/pollen-robotics/microduck_rl' },
    { name:'PPO policy training', phase:'Policy', role:'Learns velocity, standing, recovery, pickup, kick, roll, and roller behaviors from a 61-D observation to 14-D action interface.', href:'https://github.com/pollen-robotics/microduck_rl' },
    { name:'ONNX export + normalizer', phase:'Compile', role:'Packages the learned policy and its observation normalization for hardware inference.', href:'https://github.com/pollen-robotics/microduck_rl' },
    { name:'MicroDuck 50 Hz runtime', phase:'Deploy', role:'Loads and hot-swaps ONNX policies on the RK3566 onboard computer while commanding the physical servos.', href:'https://github.com/pollen-robotics/microduck' },
  ],
};

export const pipelineModules: Record<string, PipelineModule[]> = { ...corePipelineModules, ...expansionModules };
