import { expansionVenues } from './pipeline-expansion';

export type PublicationVenue = {
  label: string;
  verified: boolean;
  href?: string;
};

// `verified` is deliberately narrow: true means that a primary proceedings,
// publisher, or official author/project record identifies an archival,
// peer-reviewed conference or journal publication. A project page, workshop,
// submission, or announced future venue is not treated as archival evidence.
const corePublicationVenues: Record<string, PublicationVenue> = {
  'AdaRoboVLG': { label:'arXiv preprint (Sep 2026) · archival venue not verified', verified:false, href:'https://arxiv.org/abs/2609.04096v1' },
  'SPARK': { label:'IEEE/CVF CVPR 2026 · Oral', verified:true, href:'https://openaccess.thecvf.com/content/CVPR2026/papers/He_SPARK_Sim-ready_Part-level_Articulated_Reconstruction_with_VLM_Knowledge_CVPR_2026_paper.pdf' },
  'SoMA': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'MicroDuck': { label: 'Software/project release · no archival paper verified', verified: false },
  'ReaDy-Go': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'Ego2Robot': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'RLDX-1': { label: 'arXiv preprint + company disclosure (2026) · archival venue not verified', verified: false },
  'World Labs Atlas': { label: 'Company disclosure / early-access product release (2026)', verified: false },
  'GenRec': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'EgoTrack3D': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'SiMDex': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'VidMap': { label: 'arXiv preprint + software release (2026) · archival venue not verified', verified: false },
  'World Labs R2S2R': { label: 'Company disclosure / project release (2026)', verified: false },
  'Masked Visual Actions': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'World from Motion': { label: 'arXiv preprint / NVIDIA project release (2026) · archival venue not verified', verified: false },
  'WAM-TTT': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'Wh0': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'GenHOI': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'EgoScale': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'EgoHumanoid': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'DexImit': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'Lucida': { label: 'arXiv preprint / project release (2026) · archival venue not verified', verified: false },
  'Zero-WAM': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'Agentic Real2Sim': { label: 'arXiv preprint / project release (2026) · archival venue not verified', verified: false },
  'RoboSnap': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'SimFoundry': { label: 'arXiv preprint / NVIDIA project release (2026) · archival venue not verified', verified: false },
  'μ₀': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'Qwen-RobotManip': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'EgoEngine': { label: 'arXiv preprint / project release (2026) · archival venue not verified', verified: false },
  'WorldComposer': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'EgoSim': { label: 'arXiv preprint / project release (2026) · archival venue not verified', verified: false },
  'ExoGS': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'GSWorld': { label: 'IEEE ICRA 2026', verified: true, href: 'https://3dgsworld.github.io/' },
  'RobotArena∞': { label: 'ICLR 2026', verified: true, href: 'https://openreview.net/forum?id=OutljIofvS' },
  'GaussGym': { label: 'arXiv preprint (2025) · ICLR 2026 submission, not an archival publication', verified: false, href: 'https://arxiv.org/abs/2510.15352' },
  'VITRA': { label: 'IEEE ICRA 2026', verified: true, href: 'https://microsoft.github.io/VITRA/' },
  'Real2Sim Soft Bodies': { label: 'IEEE ICRA 2026', verified: true, href: 'https://real2sim-eval.github.io/' },
  'TraceGen': { label: 'IEEE/CVF CVPR 2026', verified: true, href: 'https://furong-huang.com/news/' },
  'HDMI': { label: 'arXiv preprint (2025) · under review / archival venue not verified', verified: false, href: 'https://github.com/LeCAR-Lab/HDMI' },
  'VideoMimic': { label: 'CoRL 2025', verified: true, href: 'https://github.com/hongsukchoi/VideoMimic' },
  'Scalable Real2Sim': { label: 'IEEE/RSJ IROS 2025', verified: true, href: 'https://github.com/nepfaff/scalable-real2sim' },
  'ReBot': { label: 'IEEE/RSJ IROS 2025', verified: true, href: 'https://yuffish.github.io/rebot/' },
  'X-Sim': { label: 'CoRL 2025', verified: true, href: 'https://proceedings.mlr.press/v305/dan25a.html' },
  'Re³Sim': { label: 'IEEE ICRA 2026', verified: true, href: 'https://re3sim.github.io/' },
  'SplatSim': { label: 'IEEE ICRA 2025', verified: true, href: 'https://splatsim.github.io/' },
  'RialTo': { label: 'Robotics: Science and Systems (RSS) 2024', verified: true, href: 'https://www.roboticsproceedings.org/rss20/p015.html' },
  'Immediate3DGS': { label: 'ACM SIGGRAPH Conference Papers 2026', verified: true, href: 'https://repo-sam.inria.fr/nerphys/i3dgs/' },
  'AnyRecon': { label: 'arXiv preprint (2026) · SIGGRAPH Asia 2026 acceptance reported; archival proceedings not yet verified', verified: false, href: 'https://yutian10.github.io/' },
  'M³': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false, href: 'https://city-super.github.io/' },
  'LiteReality-Agent': { label: 'Software/project release · technical report and archival venue not verified', verified: false },
  'LiteReality': { label: 'arXiv preprint (2025) · archival venue not verified', verified: false, href: 'https://litereality.github.io/' },
  'On-the-fly NVS': { label: 'ACM Transactions on Graphics 44(4) / SIGGRAPH 2025', verified: true, href: 'https://repo-sam.inria.fr/nerphys/on-the-fly-nvs/' },
  'Teaching by Showing': { label: 'Archival venue not verified for the linked DOI', verified: false },
  'One-Demonstration Learning': { label: 'IEEE ICRA 1997', verified: true, href: 'https://is.mpg.de/ics/publications/atkeson_iicra_1997' },
  'Gleicher Motion Retargeting': { label: 'ACM SIGGRAPH 1998', verified: true, href: 'https://graphics.cs.wisc.edu/Papers/1998/Gle98/' },
  'Schaal Imitation Framework': { label: 'Trends in Cognitive Sciences 3(6), 1999', verified: true, href: 'https://pubmed.ncbi.nlm.nih.gov/10354577/' },
  'Choi–Ko Online Retargeting': { label: 'The Journal of Visualization and Computer Animation 11(5), 2000', verified: true, href: 'https://onlinelibrary.wiley.com/doi/10.1002/1099-1778%28200012%2911%3A5%3C223%3A%3AAID-VIS236%3E3.0.CO%3B2-5' },
  'Dynamic Movement Primitives': { label: 'IEEE ICRA 2002', verified: true, href: 'https://doi.org/10.1109/ROBOT.2002.1014739' },
  'Nakaoka Dance Transfer': { label: 'IEEE ICRA 2003', verified: true, href: 'https://doi.org/10.1109/ROBOT.2003.1242196' },
  'Dariush Markerless Transfer': { label: 'IEEE/RSJ IROS 2008', verified: true, href: 'https://doi.org/10.1109/IROS.2008.4651104' },
  'Argall LfD Design Space': { label: 'Robotics and Autonomous Systems 57(5), 2009', verified: true, href: 'https://www.sciencedirect.com/science/article/pii/S0921889008001772' },
  'SMPL': { label: 'ACM Transactions on Graphics 34(6) / SIGGRAPH Asia 2015', verified: true, href: 'https://is.mpg.de/en/publications/smpl-2015' },
  'DeepMimic': { label: 'ACM Transactions on Graphics 37(4) / SIGGRAPH 2018', verified: true, href: 'https://xbpeng.github.io/projects/DeepMimic/' },
  'AnyTeleop': { label: 'Robotics: Science and Systems (RSS) 2023', verified: true, href: 'https://roboticsproceedings.org/rss19/p015.html' },
  'H2O': { label: 'IEEE/RSJ IROS 2024', verified: true, href: 'https://github.com/LeCAR-Lab/human2humanoid' },
  'OmniH2O': { label: 'CoRL 2024', verified: true, href: 'https://omni.human2humanoid.com/' },
  'HumanPlus': { label: 'CoRL 2024', verified: true, href: 'https://proceedings.mlr.press/v270/fu25a.html' },
  'GMR Retargeting': { label: 'Software/project release · no archival paper verified', verified: false },
  'SPIDER Retargeting': { label: 'arXiv preprint (2025) · IROS 2026 acceptance reported; archival proceedings not yet verified', verified: false, href: 'https://lecar-lab.github.io/publications.html' },
  'UMR': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'EmbodMocap': { label: 'IEEE/CVF CVPR 2026', verified: true, href: 'https://github.com/WenjiaWang0312/EmbodMocap' },
  'HumanX': { label: 'arXiv preprint (2026) · archival venue not verified', verified: false },
  'AINA': { label: 'IEEE ICRA 2026', verified: true, href: 'https://aina-robot.github.io/' },
  'HumanEgo': { label: 'arXiv preprint + non-archival RSS 2026 workshop paper', verified: false, href: 'https://furong-huang.com/research/embodied-ai/' },
  'OmniRetarget': { label: 'IEEE ICRA 2026', verified: true, href: 'https://omniretarget.github.io/' },
  'FunREC': { label: 'IEEE/CVF CVPR 2026', verified: true, href: 'https://openaccess.thecvf.com/content/CVPR2026/papers/Delitzas_FUN_REC__Reconstructing_Functional_3D_Scenes_from_Egocentric_Interaction_CVPR_2026_paper.pdf' },
  'REACT3D': { label: 'IEEE Robotics and Automation Letters 11(5), 2026', verified: true, href: 'https://github.com/troyehuang/REACT3D' },
  'i-Sim2Real': { label: 'CoRL 2022', verified: true, href: 'https://proceedings.mlr.press/v205/abeyruwan23a.html' },
  'XIRL': { label: 'CoRL 2021', verified: true, href: 'https://proceedings.mlr.press/v164/zakka22a.html' },
  'Animal-to-Laikago Imitation': { label: 'Robotics: Science and Systems (RSS) 2020', verified: true, href: 'https://roboticsproceedings.org/rss16/p064.html' },
};

export const publicationVenues: Record<string, PublicationVenue> = { ...corePublicationVenues, ...expansionVenues };
