import type { Metadata } from 'next';
import Link from 'next/link';
import { actuatorConcepts, calibrationLayers, communityLenses, controlArchitectureTerms, glossary, googleRoboticsAudit, mocapModes, rlRoles, scientificQuestions, sim2RealGapDimensions, simulationDirections, surveyRadar, transferPaths, unitreeVideoTransfer, worldLabsR2S2R } from '../data';
import { SiteFooter, SiteHeader } from '../site-chrome';

const simulatorAssetLayers = [
  { name:'World frame + scale', tag:'metric contract', detail:'Meters versus centimeters, handedness, up axis, gravity direction, object origins, and camera/robot frames. A beautiful asset at the wrong scale is a wrong physical hypothesis.' },
  { name:'Visual geometry', tag:'what sensors render', detail:'Detailed triangles, normals, UVs, textures, PBR material channels, splats or radiance fields. This layer serves RGB/depth sensing and need not be the contact geometry.' },
  { name:'Collision geometry', tag:'what can touch', detail:'Primitives, a decimated mesh, convex hull, or convex decomposition used by broad- and narrow-phase contact queries. It should preserve task-critical handles, rims, gaps and support surfaces without visual-only detail.' },
  { name:'Rigid-body properties', tag:'what accelerates', detail:'Static, kinematic or dynamic state; mass or density; center of mass; inertia tensor; initial pose and velocity. Geometry alone cannot predict how an object moves.' },
  { name:'Contact material', tag:'how surfaces interact', detail:'Static/dynamic friction, restitution, compliance or stiffness/damping, rolling/torsional resistance, contact margins, and collision-filter groups. Names and solver meanings vary across engines.' },
  { name:'Articulation + actuation', tag:'what may move', detail:'Link tree, joint type/axis/origin, limits, damping, mimic/tendon constraints, transmissions, actuator mode and gains. A segmented drawer is not interactive until its allowed motion is encoded.' },
  { name:'Sensors + timing', tag:'what policy observes', detail:'Camera intrinsics/extrinsics, depth and segmentation channels, joint/force/tactile sensors, noise, latency, update rates, control period and physics substeps.' },
  { name:'Task / MDP contract', tag:'what counts', detail:'Reset distribution, action and observation spaces, commands, reward or cost, success predicates, termination, randomization and logging. These usually live outside the mesh file.' },
];

const simulationFormats = [
  { format:'OBJ · PLY · STL', class:'Geometry payload', carries:'Triangles/points; OBJ can reference MTL textures.', misses:'No standard rigid bodies, joints, actuators, sensors, solver, reset or task semantics.', use:'Useful mesh dependency—not a simulator-ready scene by itself.' },
  { format:'glTF · GLB', class:'Visual scene asset', carries:'Node hierarchy, meshes, PBR materials, textures, cameras, skins and keyframe animation.', misses:'Core glTF does not define runtime physics or how an animation controls a simulator.', use:'Strong delivery format for appearance; pair with physics metadata or convert.' },
  { format:'URDF · Xacro', class:'Robot description · XML', carries:'Tree of links/joints, visual and collision geometry, mass/inertia, joint limits; Xacro generates URDF.', misses:'Limited world/task semantics and simulator-specific contact/actuator behavior often needs extensions.', use:'ROS-centric robots and articulated assets; broad importer support.' },
  { format:'MJCF · XML · MJZ', class:'MuJoCo model', carries:'Bodies, geoms, joints, inertials, actuators, tendons, sensors, contact rules and global solver options.', misses:'MuJoCo-native semantics; conversion can lose engine-specific features.', use:'Compact executable model for contact-rich control and policy learning.' },
  { format:'SDF · .sdf / .world', class:'World + robot description · XML', carries:'Worlds, nested models, links, collisions, inertials, joints, sensors, lights, physics and plugins.', misses:'Plugin/engine behavior may not transfer identically beyond the Gazebo ecosystem.', use:'Complete multi-model scenes and ROS/Gazebo simulation.' },
  { format:'USD · USDA · USDC · USDZ', class:'Layered scene + physics schema', carries:'Composition, variants, instancing, geometry, materials, articulation, colliders, rigid bodies, mass and joints.', misses:'USD core is broad; engine support for particular schemas and approximations still varies.', use:'Large editable scenes, Isaac Sim, Omniverse and cross-tool asset pipelines.' },
  { format:'YAML · JSON · Python', class:'Experiment / task config', carries:'Asset paths, poses, solver and device settings, controllers, MDP terms, seeds, randomization and evaluation suites.', misses:'Usually project-specific rather than portable; the schema matters more than the suffix.', use:'The orchestration layer around a scene description and policy.' },
  { format:'HDF5 · Zarr · NPZ · RLDS', class:'Trajectory / dataset container', carries:'Timestamped observations, actions, states, rewards, episode boundaries and metadata.', misses:'Does not make an asset executable and may omit controller/simulator versioning.', use:'Replay, imitation learning, offline RL and reality-alignment analysis.' },
];

const rolloutSteps = [
  { n:'01', title:'Compile + validate', detail:'Resolve mesh and texture paths; check units, frames, inertias, joint limits, self-collision and penetrations; then compile the scene for the target engine.' },
  { n:'02', title:'Reset', detail:'Set robot q/q̇, object poses and velocities, controller integrators, sensor buffers, random seed and task goal. A reproducible rollout starts from an explicit state distribution.' },
  { n:'03', title:'Issue a command', detail:'Read a timestamped joint trajectory q*(t), end-effector pose T*(t), velocity, torque, gripper command or learned action. End-effector trajectories require IK before or inside control.' },
  { n:'04', title:'Close the loop', detail:'At each control tick, observe state, interpolate the reference, run the policy/controller, clamp limits, and convert the command through position/velocity/torque or impedance actuation.' },
  { n:'05', title:'Step physics', detail:'Advance several smaller physics substeps per control tick, solving constraints and contacts. Keep control dt, simulation dt and timestamps explicit; mismatched rates silently change the task.' },
  { n:'06', title:'Observe + adjudicate', detail:'Render sensors, log state/contact/action, evaluate success or termination, then compare rollout statistics and failure modes with synchronized real trials—not only a plausible video.' },
];

const controlRateLayers = [
  { name:'Physics / integration rate', symbol:'fₚₕᵧₛ = 1 / dt', typical:'Often 120–2,000+ Hz', meaning:'How frequently the simulator advances dynamics and resolves constraints. Smaller dt can improve stiff-contact stability but costs more compute.', boundary:'A physics step is not necessarily a new policy action, sensor frame, render, or motor command.' },
  { name:'Solver substep rate', symbol:'fₛᵤᵦ = nₛᵤᵦ / dt', typical:'Engine- and task-specific', meaning:'Extra numerical iterations or integration substeps inside one physics step. This is an internal accuracy/stability choice.', boundary:'Do not report substeps as environment or policy frequency.' },
  { name:'Sensor rate', symbol:'fₛₑₙₛₒᵣ', typical:'Camera ≈15–90 Hz · IMU ≈100–1,000 Hz', meaning:'How often a physical or simulated sensor produces a new measurement. Each modality can have a different clock, exposure, delay, and buffer.', boundary:'Reading a camera tensor at 50 Hz does not create 50 distinct frames if the camera updates at 30 Hz.' },
  { name:'State-estimation rate', symbol:'fₑₛₜ', typical:'Often 50–1,000+ Hz', meaning:'How often raw measurements are fused into pose, velocity, object state, contacts, or a latent observation.', boundary:'Estimator output rate can exceed sensor rate through prediction; freshness and uncertainty still matter.' },
  { name:'Policy rate', symbol:'fπ = 1 / Tπ', typical:'Often 5–100 Hz', meaning:'How frequently the learned policy or planner consumes an observation and emits a new high-level or low-level action.', boundary:'A 10 Hz waypoint policy and a 50 Hz torque policy solve different control problems even if both are called “the policy.”' },
  { name:'Controller / command rate', symbol:'fctrl', typical:'Often 50–1,000+ Hz', meaning:'How often the feedback controller recomputes and sends position, velocity, torque, impedance, or motor targets.', boundary:'A slow policy can feed a fast controller that interpolates or tracks its held reference.' },
  { name:'Actuator / servo rate', symbol:'fservo', typical:'Often hundreds of Hz to several kHz', meaning:'The embedded drive’s internal current, torque, velocity, or position loop. It may be hidden below the robot API.', boundary:'Sending commands faster than the bus or servo accepts them does not increase physical bandwidth.' },
];

const timingTerms = [
  { term:'Period', definition:'Wall-clock or simulated time between updates: T = 1/f. A 50 Hz policy has a nominal 20 ms period.' },
  { term:'Decimation', definition:'Number of physics steps per policy/environment step: N = Tπ/dt = fₚₕᵧₛ/fπ when rates divide evenly.' },
  { term:'Action hold', definition:'What happens between policy updates—commonly zero-order hold, interpolation, or tracking by a faster controller.' },
  { term:'Latency', definition:'Delay from measurement exposure to applied physical effect. Include capture, transfer, preprocessing, inference, queueing, command transport, and actuation.' },
  { term:'Jitter', definition:'Variation in update time or latency. Mean 50 Hz is insufficient if deadlines are irregular or commands arrive in bursts.' },
  { term:'Throughput', definition:'Work completed per second across batches or environments. High training throughput does not imply real-time single-robot latency.' },
  { term:'Real-time factor', definition:'Simulated seconds divided by wall-clock seconds. 2× real time means two simulated seconds are produced per wall-clock second.' },
  { term:'Bandwidth', definition:'How quickly the physical closed loop can respond—not the same as sample rate. Mechanics, filters, delay, and gains all limit bandwidth.' },
];

const robotLearningStack = [
  { layer:'01–02', plane:'Data', name:'Task evidence', detail:'Specify behavior, embodiment and success; collect, synchronize, calibrate and normalize robot demonstrations, human video, simulation, language and failure data with provenance.' },
  { layer:'03–04', plane:'Learning', name:'Model + training system', detail:'Choose BC, diffusion or flow policy, VLA, world model, RL or a hybrid; connect objectives to scalable data loading, simulator workers, experiment tracking, evaluation and reproducible checkpoints.' },
  { layer:'05–07', plane:'Online decision', name:'Perceive, plan, control', detail:'State estimation, task and motion planning, learned policies, IK, trajectory optimization and feedback control convert calibrated sensor streams into stable, constraint-aware commands.' },
  { layer:'08', plane:'Hardware', name:'Robot runtime', detail:'Mechanism, sensors, actuators, embedded compute, clocks, buses, drivers, gains, latency budgets and watchdogs define what the policy can actually observe and execute.' },
  { layer:'09–10', plane:'Assurance', name:'Safety + evidence loop', detail:'Constraints, monitors, recovery and human override bound failures; held-out simulation and physical trials measure success, sim–real correlation and what data to collect next.' },
];

export const metadata: Metadata = {
  title: 'Foundations — Real2Sim Frontier',
  description: 'Taxonomy, terminology, scientific questions, surveys, and evidence methodology for real-to-sim and human-to-robot systems.',
};

export default function FoundationsPage() {
  return <main id="top" className="foundations-page">
    <SiteHeader active="foundations" />
    <section className="subpage-hero foundations-subpage-hero">
      <div><p className="eyebrow">FOUNDATIONS · A WORKING GRAMMAR</p><h1>Understand the <em>whole loop.</em></h1></div>
      <div className="subpage-intro"><p>A compact reference for the directions, system contracts, human evidence, learning loops, terminology, surveys, and evaluation rules behind real2sim.</p><nav className="foundation-chapter-links" aria-label="Foundation chapters"><a href="#directions"><b>01</b> Core loop</a><a href="#control-architecture"><b>02</b> Executable stack</a><a href="#mocap"><b>03</b> Human evidence</a><a href="#survey"><b>04</b> Research map</a></nav><nav className="foundation-hero-links"><a className="button secondary" href="#directions">Start reading ↓</a><Link className="button secondary" href="/evolution/">Evolution ↗</Link><Link className="button secondary" href="/pipelines/">← Technical atlas</Link></nav></div>
    </section>

    <section className="direction-section" id="directions">
      <div className="section-heading"><div><p className="eyebrow">DIRECTION MATTERS</p><h2>Real2Sim, Sim2Real, and the closed loop.</h2></div><p>These names describe the direction of evidence and intervention—not three levels of visual quality. Keeping them separate makes it clear what a paper has built, what it has transferred, and what reality has actually verified.</p></div>
      <div className="direction-grid">{simulationDirections.map((item, index) => <article key={item.term} className={item.term === 'Real2Sim2Real' ? 'direction-loop' : ''}><header><span>{String(index + 1).padStart(2, '0')}</span><h3>{item.term}</h3><b>{item.direction}</b></header><dl><div><dt>Problem</dt><dd>{item.problem}</dd></div><div><dt>Produces</dt><dd>{item.produces}</dd></div><div><dt>Decisive test</dt><dd>{item.test}</dd></div></dl><blockquote>{item.boundary}</blockquote><nav aria-label={`${item.term} examples`}>{item.examples.map((example) => <a href={example.href} target="_blank" rel="noreferrer" key={example.label}>{example.label} ↗</a>)}</nav></article>)}</div>
      <div className="direction-loop-strip"><span>REAL EVIDENCE</span><b>→</b><span>SIMULATOR HYPOTHESIS</span><b>→</b><span>TRAIN / TEST / INTERVENE</span><b>→</b><span>PHYSICAL OUTCOME</span><b>↺</b><span>RECALIBRATE</span></div>

      <article className="worldlabs-case" id="world-labs-r2s2r">
        <header><div><p className="eyebrow">CASE FILE · {worldLabsR2S2R.date}</p><h2>{worldLabsR2S2R.title}</h2></div><p>{worldLabsR2S2R.thesis}</p></header>
        <div className="worldlabs-stages">{worldLabsR2S2R.stages.map((stage) => <section key={stage.number}><span>{stage.number}</span><h3>{stage.title}</h3><p>{stage.detail}</p></section>)}</div>
        <div className="worldlabs-evidence">{worldLabsR2S2R.evidence.map((item) => <section key={item.label}><span>{item.label}</span><strong>{item.value}</strong><p>{item.detail}</p></section>)}</div>
        <footer><div><span>DISCLOSURE BOUNDARY</span><p>{worldLabsR2S2R.boundary}</p></div><a href={worldLabsR2S2R.href} target="_blank" rel="noreferrer">Read the World Labs post ↗</a></footer>
      </article>
    </section>

    <details className="foundation-module" id="control-architecture"><summary><span>02 · EXECUTABLE STACK</span><strong>Planning, control, and timing</strong><p>Planner/controller roles, multi-rate systems, policy rate, latency, and the GaussGym throughput example.</p><i>＋</i></summary>
    <section className="control-architecture-section">
      <div className="section-heading"><div><p className="eyebrow">ROBOT ARCHITECTURE · DELIBERATION × FEEDBACK</p><h2>A planner chooses a future. A controller survives the present.</h2></div><p>These labels describe roles, not fixed algorithms. Classical optimization, learned policies, VLMs, and hybrid systems can occupy the same box—but their inputs, outputs, timescales, and guarantees remain different.</p></div>
      <div className="control-loop-map" aria-label="Planning and control architecture">
        <div className="slow-system"><small>SLOW / DELIBERATIVE</small><b>Goal + world state</b><i>→</i><b>Task planner</b><i>→</i><b>Motion planner / trajectory optimizer</b></div>
        <span>↓ reference / waypoint / skill / trajectory</span>
        <div className="fast-system"><small>FAST / REACTIVE</small><b>State estimator</b><i>→</i><b>IK / whole-body mapping</b><i>→</i><b>Controller / policy</b><i>→</i><b>Actuators</b><i>→</i><b>World</b><em>↺ sensor feedback</em></div>
      </div>
      <div className="control-term-grid">{controlArchitectureTerms.map((item, index) => <article key={item.term}><header><span>{String(index + 1).padStart(2,'0')} · {item.kind}</span><h3>{item.term}</h3></header><p>{item.question}</p><dl><div><dt>Produces</dt><dd>{item.output}</dd></div><div><dt>Typical timescale</dt><dd>{item.timescale}</dd></div><div><dt>Do not conflate</dt><dd>{item.boundary}</dd></div></dl><nav>{item.refs.map((ref) => <a href={ref.href} target="_blank" rel="noreferrer" key={ref.label}>{ref.label} ↗</a>)}</nav></article>)}</div>
      <div className="control-real2sim"><header><span>WHY THIS MATTERS FOR REAL2SIM</span><strong>The downstream module defines which reality must be reconstructed.</strong></header><div><p><b>Task planner</b> needs persistent entities, affordances, relations, and change state.</p><p><b>Motion planner / IK</b> needs metric frames, robot kinematics, collision geometry, and joint limits.</p><p><b>Controller / policy</b> needs action timing, sensor response, actuator and contact dynamics, disturbances, and latency.</p><p><b>Evaluation</b> needs resets, success predicates, coverage, and evidence that simulator rankings survive on hardware.</p></div></div>

      <div className="rate-heading" id="control-rates"><div><p className="eyebrow">MULTI-RATE SYSTEMS · WHAT “HZ” MEANS</p><h2>Policy rate is only one clock.</h2></div><p><b>Rate</b> is how often a layer updates; <b>period</b> is the time between updates. A robot stack is normally asynchronous or multi-rate: cameras, IMUs, estimators, policies, controllers, actuator servos, rendering, and physics do not share one universal tick.</p></div>
      <div className="rate-equation" aria-label="Relationship among simulation timestep, policy period, and decimation"><span>PHYSICS DT<small>0.002 s</small></span><b>×</b><span>DECIMATION<small>10 steps / action</small></span><b>=</b><span>POLICY PERIOD<small>0.020 s</small></span><b>→</b><span>POLICY RATE<small>50 Hz</small></span></div>
      <div className="rate-stack" aria-label="Example multi-rate robot control stack"><span><b>CAMERA</b><i>30 Hz</i></span><span><b>POLICY</b><i>50 Hz</i></span><span><b>STATE ESTIMATOR</b><i>200 Hz</i></span><span><b>CONTROLLER</b><i>500 Hz</i></span><span><b>PHYSICS / PLANT</b><i>500 Hz</i></span><span><b>EMBEDDED SERVO</b><i>1 kHz</i></span></div>
      <p className="rate-caution"><b>Illustrative rates—not recommendations.</b> The right values depend on sensing, action space, robot dynamics, contact stiffness, network and compute budget. Always report the exact clock, timestamp convention, hold/interpolation rule, and measured latency.</p>
      <div className="rate-layer-grid">{controlRateLayers.map((item, index) => <article key={item.name}><header><span>{String(index + 1).padStart(2,'0')}</span><code>{item.symbol}</code></header><h3>{item.name}</h3><strong>{item.typical}</strong><p>{item.meaning}</p><blockquote>{item.boundary}</blockquote></article>)}</div>

      <div className="timing-heading"><div><p className="eyebrow">TIMING TERMS</p><h2>Do not collapse these into “FPS.”</h2></div><p>Frames per second may describe rendering, camera acquisition, dataset playback, or visual display. None alone establishes closed-loop control frequency or deadline performance.</p></div>
      <div className="timing-term-grid">{timingTerms.map((item) => <article key={item.term}><h3>{item.term}</h3><p>{item.definition}</p></article>)}</div>
      <article className="gaussgym-timing-case" id="gaussgym-timing">
        <header><div><span>CASE STUDY · GAUSSGYM</span><h3>One system, three different speed claims.</h3></div><a href="https://arxiv.org/html/2510.15352#S3.SS3" target="_blank" rel="noreferrer">Primary evidence ↗</a></header>
        <div className="gaussgym-timing-stats"><p><b>50 Hz</b><small>CONTROL UPDATE<br />SIMULATED TIME</small></p><p><b>10 Hz</b><small>CAMERA / 3DGS RENDER<br />SIMULATED TIME</small></p><p><b>25 steps/s</b><small>PER ENVIRONMENT<br />REPORTED TABLE</small></p><p><b>100K+</b><small>AGGREGATE STEPS/S<br />4,096 ENVS · RTX 4090</small></p></div>
        <div className="gaussgym-timing-reading"><section><strong>WHAT IT DOES</strong><p>GaussGym deliberately decouples the camera render clock from the faster proprioceptive control and physics clocks. A 10 Hz RGB/depth frame is therefore reused across several 50 Hz control decisions while vectorized Isaac Gym / Isaac Sim contact physics continues underneath.</p></section><section><strong>WHY PROMISING</strong><p>It makes photorealistic pixel-based RL computationally plausible: batched 3D Gaussian rasterization supplies RGB and depth, while a separately reconstructed NKSR collision mesh supplies contact. This joins graphics fidelity to GPU-parallel robot learning without ray-tracing every control tick.</p></section><section><strong>WHY IMPORTANT</strong><p>The design exposes a reusable systems principle: spend rendering compute at the real sensor rate, not at the fastest loop. That can preserve the temporal contract seen by the deployed policy while increasing training throughput and scene diversity.</p></section><section className="gaussgym-timing-caution"><strong>EVIDENCE BOUNDARY</strong><p><b>100K steps/s is throughput, not 100 kHz control.</b> The paper does not report the physics timestep in this timing passage. Its real A1 staircase result is an initial transfer test; unseen-stair generalization declined, image latency remains a challenge, and scene friction is uniform rather than reconstructed.</p></section></div>
      </article>
      <div className="rate-example"><header><span>WORKED EXAMPLE</span><strong>A 50 Hz policy inside a 500 Hz simulation</strong></header><div><p><b>Every 20 ms</b> the policy receives the newest assembled observation and emits one action.</p><p><b>For 10 × 2 ms physics steps</b> that action is held or tracked by the controller before the next policy inference.</p><p><b>A 30 Hz camera</b> produces a genuinely new image every 33.3 ms, so some policy steps reuse the previous frame while proprioception may refresh.</p><p><b>Latency changes action age.</b> If sensing-to-command latency is 35 ms, the action is already based on evidence older than one 20 ms policy period when it is applied.</p></div><footer><strong>LOG AT MINIMUM</strong><span>measurement timestamp</span><span>observation assembly time</span><span>inference start/end</span><span>command send/accept</span><span>physics + controller tick</span></footer></div>
      <nav className="rate-references" aria-label="Control timing references"><a href="https://arxiv.org/html/2510.15352#S3.SS3" target="_blank" rel="noreferrer">GaussGym · decoupled clocks ↗</a><a href="https://gauss-gym.com/" target="_blank" rel="noreferrer">GaussGym · project ↗</a><a href="https://isaac-sim.github.io/IsaacLab/develop/source/api/lab/isaaclab.envs.html" target="_blank" rel="noreferrer">Isaac Lab · dt + decimation ↗</a><a href="https://isaac-sim.github.io/IsaacLab/develop/source/how-to/transfer_policies_between_physx_and_newton.html" target="_blank" rel="noreferrer">Isaac Lab · timing parity ↗</a><a href="https://isaac-sim.github.io/IsaacLab/develop/source/features/isaac_teleop.html" target="_blank" rel="noreferrer">Isaac Teleop · render rate ↗</a><a href="https://github.com/pollen-robotics/microduck_rl" target="_blank" rel="noreferrer">MicroDuck · 50 Hz deployment ↗</a></nav>
    </section>
    </details>

    <details className="foundation-module" id="simulation-ready"><summary><span>03 · SIMULATION CONTRACT</span><strong>From visible mesh to executable world</strong><p>Collision geometry, physical properties, formats, configuration, and reproducible trajectory rollout.</p><i>＋</i></summary>
    <section className="sim-ready-section">
      <div className="section-heading"><div><p className="eyebrow">SIMULATION-READY · ASSET CONTRACT × ROLLOUT</p><h2>A mesh is visible. A model is executable.</h2></div><p>Putting a reconstructed object or scene into a simulator is a packaging problem and a scientific-modeling problem. The engine needs geometry for sensing, geometry for contact, physical and kinematic properties, time and control semantics, and a task definition. No single file suffix guarantees those contracts are complete.</p></div>

      <div className="collision-mesh-explainer">
        <article><span>RENDER PATH</span><strong>Visual mesh</strong><div className="mesh-glyph mesh-visual" aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /><i /></div><p>High-detail surface for RGB/depth rendering: texture seams, thin ornament, normals and material detail are welcome.</p></article>
        <b>≠</b>
        <article><span>CONTACT PATH</span><strong>Collision mesh</strong><div className="mesh-glyph mesh-collision" aria-hidden="true"><i /><i /><i /></div><p>A cheaper closed approximation queried by the physics engine to generate contacts, normals and penetration depths.</p></article>
        <b>→</b>
        <article className="mesh-verdict"><span>DESIGN RULE</span><strong>Simple enough to step; faithful where action depends on it.</strong><p>Use primitives or convex hulls for dynamic bodies; convex decomposition for concavity; a simplified triangle mesh mainly for static terrain. Preserve handles, cavities, rims and support surfaces that change feasibility.</p></article>
      </div>
      <div className="collision-cautions"><p><b>Watertight is useful, not universally mandatory.</b> It enables stable volume, mass and inertia estimation; open or non-manifold meshes can produce ambiguous inside/outside tests.</p><p><b>Convex hull is not convex decomposition.</b> One hull fills every cavity; multiple convex parts can preserve a mug handle or drawer gap at higher contact cost.</p><p><b>Collider accuracy is task-relative.</b> A coarse tabletop is fine; a coarse peg, fingertip, blade or socket can invalidate the trajectory.</p><p><b>Never infer “physics-ready” from `.obj` alone.</b> Verify collider assignment, scale, body type, mass properties, material and engine import behavior.</p></div>

      <div className="sim-ready-subheading"><div><p className="eyebrow">THE MINIMUM EXECUTABLE PACKAGE</p><h2>Eight layers from pixels to interventions.</h2></div><p>The first six describe a world and embodiment. Sensors and the task/MDP contract turn that world into a closed-loop robot-learning environment.</p></div>
      <div className="asset-layer-grid">{simulatorAssetLayers.map((item, index) => <article key={item.name}><span>{String(index + 1).padStart(2,'0')} · {item.tag}</span><h3>{item.name}</h3><p>{item.detail}</p></article>)}</div>

      <div className="sim-ready-subheading"><div><p className="eyebrow">FORMAT MAP</p><h2>Payload, model, world, config, log.</h2></div><p>Formats occupy different layers. A common package is <code>scene.usd</code> or <code>robot.urdf</code> plus referenced meshes/textures, a task config, policy checkpoint, and timestamped rollout data.</p></div>
      <div className="format-table-shell"><table className="format-table"><thead><tr><th>Format / suffix</th><th>Role</th><th>What it carries</th><th>What it does not guarantee</th><th>Best use</th></tr></thead><tbody>{simulationFormats.map((item) => <tr key={item.format}><td><strong>{item.format}</strong></td><td>{item.class}</td><td>{item.carries}</td><td>{item.misses}</td><td>{item.use}</td></tr>)}</tbody></table></div>

      <div className="sim-ready-subheading rollout-heading"><div><p className="eyebrow">TRAJECTORY ROLLOUT</p><h2>Reset, command, step, observe, judge.</h2></div><p>A trajectory is a time-indexed reference—not a video. At minimum store timestamps, frame names, units, command type and controller rate. For reproducibility, bind the trajectory to the exact asset, simulator, controller, solver and random seed.</p></div>
      <div className="rollout-contract" aria-label="Trajectory rollout loop"><span>MODEL + CONFIG</span><b>→</b><span>RESET STATE</span><b>→</b><span>ACTION / REFERENCE</span><b>→</b><span>CONTROLLER</span><b>→</b><span>PHYSICS SUBSTEPS</span><b>→</b><span>OBSERVATION + LOG</span><b>↺</b></div>
      <div className="rollout-grid">{rolloutSteps.map((step) => <article key={step.n}><span>{step.n}</span><h3>{step.title}</h3><p>{step.detail}</p></article>)}</div>
      <div className="config-anatomy"><header><span>MAJOR CONFIG BLOCKS</span><strong>The suffix is secondary; these fields are the contract.</strong></header><div><p><b>scene</b><code>assets · transforms · units · gravity</code></p><p><b>physics</b><code>engine · dt · substeps · solver · contacts</code></p><p><b>robot</b><code>model · actuator mode · gains · limits</code></p><p><b>sensors</b><code>frames · rates · noise · latency</code></p><p><b>task / MDP</b><code>reset · action · observation · reward · termination</code></p><p><b>evaluation</b><code>seeds · trials · success · logging · real pairing</code></p></div></div>
      <nav className="sim-ready-references" aria-label="Simulation asset and format references"><a href="https://openusd.org/release/api/usd_physics_page_front.html" target="_blank" rel="noreferrer">OpenUSD Physics schema ↗</a><a href="https://docs.ros.org/en/humble/Tutorials/URDF/Adding-Physical-and-Collision-Properties-to-a-URDF-Model.html" target="_blank" rel="noreferrer">ROS · URDF collision + inertial ↗</a><a href="https://mujoco.readthedocs.io/en/stable/XMLreference.html" target="_blank" rel="noreferrer">MuJoCo · MJCF reference ↗</a><a href="https://sdformat.org/spec/1.12/link/" target="_blank" rel="noreferrer">SDFormat · link specification ↗</a><a href="https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html" target="_blank" rel="noreferrer">Khronos · glTF 2.0 ↗</a><a href="https://arxiv.org/abs/2511.04831" target="_blank" rel="noreferrer">Isaac Lab · environment step anatomy ↗</a></nav>
    </section>
    </details>

    <details className="foundation-module" id="full-stack"><summary><span>04 · ROBOT-LEARNING STACK</span><strong>Data, learning, runtime, hardware, assurance</strong><p>What “full stack” means—and where a real2sim pipeline stops unless it closes the physical evidence loop.</p><i>＋</i></summary>
    <section className="full-stack-section">
      <div className="section-heading light"><div><p className="eyebrow">FULL STACK · ROBOT LEARNING</p><h2>From task evidence to safe physical behavior.</h2></div><p>In robot learning, <b>full stack</b> means owning or integrating the dependent layers required to collect evidence, learn behavior, execute it on hardware, measure failure, and feed that evidence back. It is a systems-scope claim—not a model architecture and not a synonym for end-to-end.</p></div>
      <div className="full-stack-test"><strong>A PRACTICAL COMPLETENESS TEST</strong><p>Can the team change a task definition, collect or synthesize the missing evidence, retrain, deploy through the real control path, detect unsafe or incorrect behavior, reproduce the evaluation, and use failures to decide the next data or model change?</p><b>If any hand-off is assumed rather than implemented, name the boundary.</b></div>
      <div className="stack-planes" aria-label="Robot learning full stack planes"><span>DATA</span><b>→</b><span>LEARNING</span><b>→</b><span>ONLINE DECISION</span><b>→</b><span>HARDWARE</span><b>→</b><span>ASSURANCE</span><b>↺</b></div>
      <div className="robot-stack-grid">{robotLearningStack.map((item) => <article key={item.layer}><span>{item.layer} · {item.plane}</span><h3>{item.name}</h3><p>{item.detail}</p></article>)}</div>
      <div className="full-stack-boundaries"><article><span>END-TO-END MODEL</span><p>Maps observations to actions through one learned model. It may still depend on somebody else’s data pipeline, controller, drivers, safety and evaluation.</p></article><article><span>FOUNDATION MODEL</span><p>Provides a reusable pretrained capability. It becomes one component of the stack only after embodiment, timing, control and task semantics are connected.</p></article><article><span>FULL PIPELINE</span><p>Covers the declared input-to-output transformation for one workflow. It can be complete as a pipeline while stopping before real deployment or continuous operations.</p></article><article><span>FULL STACK</span><p>Connects the operational loop across data, learning, runtime, hardware and assurance for a stated robot/task scope. “Full” is always relative to that declared scope.</p></article></div>
      <div className="full-stack-real2sim"><strong>WHERE REAL2SIM SITS</strong><p>Real2sim crosses several layers: capture and curation; geometry, appearance, physics and scene state; simulator/task construction; demonstration generation or policy evaluation. It becomes a <b>full-stack robot-learning system</b> only when the resulting assets are connected to training, controller/runtime integration, physical validation, safety, and a failure-driven update loop.</p></div>
    </section>
    </details>

    <details className="foundation-module" id="mocap"><summary><span>05 · HUMAN EVIDENCE</span><strong>Mocap, calibration, actuation, and the sim–real gap</strong><p>How measured human motion becomes aligned evidence, feasible robot commands, and a testable transfer hypothesis.</p><i>＋</i></summary>
    <section className="mocap-section">
      <div className="section-heading"><div><p className="eyebrow">MOTION CAPTURE · CALIBRATION · ACTUATION</p><h2>Measured motion is not yet executable motion.</h2></div><p><b>Motion capture (mocap)</b> estimates how bodies, hands, objects, or sensors move through time in a coordinate system. It becomes useful for real2sim only after correspondence, scale, timing, world alignment, contact, and robot feasibility are made explicit.</p></div>
      <div className="mocap-pipeline" aria-label="Motion capture to robot pipeline"><span>RAW SENSORS<small>pixels · markers · IMUs · gloves</small></span><b>→</b><span>CALIBRATE + SYNC<small>rays · clocks · frames · scale</small></span><b>→</b><span>TRACK + RECONSTRUCT<small>3D points · body/hand/object state</small></span><b>→</b><span>FIT + ALIGN<small>skeleton · SMPL/MANO · world</small></span><b>→</b><span>RETARGET + TEST<small>IK · contact · physics · controller</small></span></div>
      <div className="mocap-grid">{mocapModes.map((item, index) => <article key={item.mode}><span>{String(index + 1).padStart(2,'0')}</span><h3>{item.mode}</h3><dl><div><dt>Measures</dt><dd>{item.measures}</dd></div><div><dt>Strength</dt><dd>{item.strength}</dd></div><div><dt>Failure boundary</dt><dd>{item.failure}</dd></div></dl></article>)}</div>

      <div className="mocap-subheading"><div><p className="eyebrow">WHAT “CALIBRATED MULTIVIEW” ACTUALLY MEANS</p><h2>Many cameras; one metric world.</h2></div><p>A multiview system needs overlapping observations plus known camera models and timestamps. With those contracts, corresponding rays can be triangulated and jointly refined by bundle adjustment. Without them, “fusion” is only an informal aggregation of inconsistent evidence.</p></div>
      <div className="calibration-grid">{calibrationLayers.map((item, index) => <article key={item.layer}><span>{String(index + 1).padStart(2,'0')}</span><h3>{item.layer}</h3><p>{item.solves}</p><blockquote><b>If wrong:</b> {item.breaks}</blockquote></article>)}</div>
      <div className="multiview-note"><strong>FIXED RIG</strong><p>Cameras are calibrated once around a shared volume; synchronization and occlusion coverage dominate.</p><b>↔</b><strong>MOVING / EGOCENTRIC VIEWS</strong><p>Every camera pose changes, so VIO, SLAM, SfM, depth, IMU, loop closure, and cross-view association become part of calibration.</p></div>

      <div className="mocap-subheading actuator-heading"><div><p className="eyebrow">ACTUATORS</p><h2>The simulator’s command must meet the real mechanism.</h2></div><p>An actuator is the complete command-to-force path—not just the motor. For policy transfer, the effective plant includes drive electronics, transmission, joint mechanics, embedded control, limits, delay, and state estimation.</p></div>
      <div className="actuator-flow"><span>POLICY ACTION</span><b>→</b><span>LOW-LEVEL SERVO</span><b>→</b><span>MOTOR / DRIVE</span><b>→</b><span>TRANSMISSION</span><b>→</b><span>JOINT + CONTACT</span><b>↺</b><span>ENCODER / SENSOR</span></div>
      <div className="actuator-grid">{actuatorConcepts.map((item, index) => <article key={item.term}><span>{String(index + 1).padStart(2,'0')}</span><h3>{item.term}</h3><p>{item.detail}</p></article>)}</div>

      <div className="mocap-subheading gap-heading"><div><p className="eyebrow">SIM-TO-REAL GAP</p><h2>A vector of mismatches, not one gap.</h2></div><p>The gap is the difference between simulated and physical closed-loop behavior under the same intended task. Its practical size is policy-dependent: an error matters when it changes observations, actions, contacts, stability, success, or the ranking of candidate policies.</p></div>
      <div className="gap-equation"><span>GAP</span><b>≠</b><span>VISUAL DIFFERENCE</span><b>;</b><span>GAP</span><b>=</b><span>DECISION-RELEVANT MISMATCH</span></div>
      <div className="gap-grid">{sim2RealGapDimensions.map((item, index) => <article key={item.name}><span>{String(index + 1).padStart(2,'0')}</span><h3>{item.name}</h3><p>{item.examples}</p></article>)}</div>
      <div className="gap-mitigation"><strong>REPAIR TOOLBOX</strong><p><b>Measure:</b> calibration + system identification.</p><p><b>Cover:</b> domain randomization + diverse scenes.</p><p><b>Adapt:</b> residual models + online adaptation.</p><p><b>Validate:</b> held-out hardware success + sim–real policy correlation.</p></div>
      <nav className="mocap-references" aria-label="Motion capture and calibration references"><a href="https://www.vicon.com/about-us/what-is-motion-capture/" target="_blank" rel="noreferrer">Vicon · optical mocap ↗</a><a href="https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html" target="_blank" rel="noreferrer">OpenCV · camera calibration ↗</a><a href="https://demuc.de/papers/schoenberger2016sfm.pdf" target="_blank" rel="noreferrer">COLMAP · multiview geometry ↗</a><a href="https://ego-exo4d-data.org/" target="_blank" rel="noreferrer">Ego-Exo4D · synchronized ego/exo capture ↗</a><a href="https://human2humanoid.com/" target="_blank" rel="noreferrer">H2O · mocap to feasible humanoid motion ↗</a><a href="https://github.com/pollen-robotics/microduck_rl" target="_blank" rel="noreferrer">MicroDuck · actuator-gap modeling ↗</a></nav>
    </section>
    </details>

    <details className="foundation-module" id="survey"><summary><span>06 · RESEARCH MAP</span><strong>Surveys and focused evidence audits</strong><p>Survey taxonomies, the egocentric-to-Unitree check, and the Google robotics lineage.</p><i>＋</i></summary>
    <section className="survey-section">
      <div className="section-heading"><div><p className="eyebrow">SURVEY / CITATION RADAR</p><h2>Use surveys as maps, not finish lines.</h2></div><p>The supplied <a href="https://scholar.google.com/scholar?oi=bibs&amp;hl=en&amp;cites=17444276066101837403" target="_blank" rel="noreferrer">Google Scholar citation graph ↗</a> is anchored on DexImit. It is used here as a discovery lead, triangulated against broader human-video, HOI, video-generation, and reality-gap surveys.</p></div>
      <div className="survey-grid">{surveyRadar.map((item) => <a href={item.href} target="_blank" rel="noreferrer" className="survey-card" key={item.title} title={`Boundary: ${item.boundary}`}><span>{item.year} · SURVEY</span><h3>{item.title}</h3><b>{item.scope}</b><dl><div><dt>Taxonomy</dt><dd>{item.taxonomy}</dd></div><div><dt>Use</dt><dd>{item.value}</dd></div></dl><i>Read source ↗</i></a>)}</div>
      <div className="foundation-focus-grid">
        <details className="foundation-focus-note">
          <summary><span>FOCUSED AUDIT · 01</span><strong>Egocentric video → Unitree + dexterous hand</strong><i>＋</i></summary>
          <div><div className="unitree-heading"><div><p className="eyebrow">EVIDENCE TABLE</p><h2>“Direct” still has four caveats.</h2></div><p>EgoScale, EgoHumanoid, and Wh0 remain the strongest matches. HumanX is a whole-body comparator rather than full finger-level control.</p></div><div className="unitree-table-shell"><table className="unitree-table"><thead><tr><th>Work</th><th>Human-video source</th><th>Robot / hand</th><th>Hand action interface</th><th>Aligned robot data?</th><th>Verdict</th></tr></thead><tbody>{unitreeVideoTransfer.map((item) => <tr key={item.work}><td><a href={item.href} target="_blank" rel="noreferrer">{item.work} ↗</a></td><td>{item.source}</td><td>{item.robot}</td><td>{item.hand}</td><td>{item.robotData}</td><td>{item.verdict}</td></tr>)}</tbody></table></div><p className="survey-note"><b>Negative check:</b> DexImit uses two UR5e arms with XHands, not Unitree. Demonstration scheduling alone also does not create a real2sim world.</p></div>
        </details>
        <details className="foundation-focus-note">
          <summary><span>FOCUSED AUDIT · 02</span><strong>Google robotics lineage</strong><i>＋</i></summary>
          <div><div className="google-audit-heading"><div><p className="eyebrow">GOOGLE DEEPMIND / GOOGLE ROBOTICS</p><h2>Direct matches and important neighbors.</h2></div><p>The audit follows the method across Google Research, Brain, and current Google DeepMind branding.</p></div><div className="google-audit-grid">{googleRoboticsAudit.map((item) => <a href={item.href} target="_blank" rel="noreferrer" key={item.name}><span>{item.verdict}</span><h3>{item.name} ↗</h3><p>{item.detail}</p></a>)}</div></div>
        </details>
      </div>
    </section>
    </details>

    <details className="foundation-module" id="rl-loop"><summary><span>07 · LEARNING LOOP</span><strong>Where reinforcement learning enters real2sim</strong><p>RL as feasibility test, dynamics-aware adapter, robustness engine, and reality-gap repair mechanism.</p><i>＋</i></summary>
    <section className="rl-section">
      <div className="section-heading light"><div><p className="eyebrow">RL IN REAL2SIM</p><h2>Not just the last box.</h2></div><p>Reinforcement learning is the interaction engine that turns a reconstructed world into evidence about executability, recovery, counterfactual behavior, and transfer. It can enter before, inside, and after simulator construction.</p></div>
      <div className="rl-loop" aria-label="Closed real2sim reinforcement-learning loop"><span>REAL OBSERVATIONS</span><b>→</b><span>WORLD + BODY MODEL</span><b>→</b><span>RL INTERACTION</span><b>→</b><span>POLICY / FAILURE SIGNAL</span><b>→</b><span>REAL DEPLOYMENT</span><b>↺</b></div>
      <div className="rl-principle"><strong>Core distinction</strong><p><b>Behavior cloning</b> learns from the actions present in a fixed dataset. <b>RL</b> changes the data distribution by acting, observing consequences, and optimizing a reward. That makes simulator transition fidelity—and not only visual similarity—central.</p></div>
      <div className="rl-role-grid">{rlRoles.map((item) => <article key={item.number}><header><span>{item.number}</span><b>{item.where}</b></header><h3>{item.title}</h3><p>{item.role}</p><blockquote>{item.signal}</blockquote><small>EVIDENCE</small><p>{item.evidence}</p><nav aria-label={`${item.title} references`}>{item.refs.map((ref) => <a href={ref.href} target="_blank" rel="noreferrer" key={ref.label}>{ref.label} ↗</a>)}</nav></article>)}</div>
      <div className="rl-boundary"><span>WHAT RL CANNOT REPAIR BY ITSELF</span><p>A policy can exploit a wrong simulator more efficiently than it can correct one. RL does not infer missing scale, repair collision meshes, identify unobserved friction, or prove causal fidelity unless the observations, action space, transitions, reward, and real checks expose those errors.</p><strong>REAL2SIM BUILDS THE HYPOTHESIS · RL INTERROGATES IT · REALITY ADJUDICATES IT</strong></div>
    </section>
    </details>

    <details className="foundation-module" id="taxonomy"><summary><span>08 · TRANSFER LANGUAGE</span><strong>Human-video taxonomy and working lexicon</strong><p>Task-, observation-, and action-level transfer plus operational definitions for commonly conflated terms.</p><i>＋</i></summary>
    <section className="taxonomy-section">
      <div className="section-heading light"><div><p className="eyebrow">HUMAN VIDEO → ROBOT TAXONOMY</p><h2>Three levels of transfer.</h2></div><p>Human video can supervise a robot without ever becoming a robot trajectory. This task / observation / action split is adapted from the 2026 <a href="https://arxiv.org/abs/2604.27621" target="_blank" rel="noreferrer">Robot Learning from Human Videos survey ↗</a>.</p></div>
      <div className="transfer-paths">{transferPaths.map((path) => <article className="transfer-card" key={path.level}><span>{path.level}</span><h3>{path.title}</h3><strong>{path.preserves}</strong><div className="transfer-flow">{path.intermediates.map((item, index) => <span key={item}>{item}{index < path.intermediates.length - 1 && <b>→</b>}</span>)}</div><dl><div><dt>Typical output</dt><dd>{path.output}</dd></div><div><dt>Boundary</dt><dd>{path.limitation}</dd></div></dl></article>)}</div>
      <div className="lexicon-heading"><div><p className="eyebrow">WORKING LEXICON</p><h2>Terms that are often conflated.</h2></div><p>Open a term for its operational definition, the nearest contrast, and primary references.</p></div>
      <div className="glossary-grid">{glossary.map((item, index) => <details className="glossary-item" key={item.term}><summary><span>{String(index + 1).padStart(2, '0')}</span><strong>{item.term}</strong><i>＋</i></summary><div><p>{item.definition}</p><blockquote><b>Distinguish:</b> {item.distinction}</blockquote><small>PRIMARY REFERENCES</small><nav aria-label={`${item.term} references`}>{item.refs.map((ref) => <a href={ref.href} target="_blank" rel="noreferrer" key={ref.label}>{ref.label} ↗</a>)}</nav></div></details>)}</div>
    </section>
    </details>

    <details className="foundation-module" id="questions"><summary><span>09 · ENDURING QUESTIONS</span><strong>Scientific tensions across robotics, vision, and graphics</strong><p>Correspondence, fusion, representation, dynamics, evaluation, and the vocabulary each community brings.</p><i>＋</i></summary>
    <section className="questions-section">
      <div className="section-heading"><div><p className="eyebrow">LONG-STANDING SCIENTIFIC QUESTIONS</p><h2>The questions outlast the tools.</h2></div><p>These are the assumptions underneath every human-to-robot and real-to-sim system—and the right anchors for comparing generations of work.</p></div>
      <div className="question-grid">{scientificQuestions.map((item) => <article className="question-card" id={`question-${item.number.toLowerCase()}`} key={item.number}><span>{item.number} · {item.title}</span><div className="question-meta">{item.communities.map((community) => <b className={`community-${community.toLowerCase().replace(' ', '-')}`} key={community}>{community}</b>)}</div><h3>{item.question}</h3><p>{item.tension}</p><div className="question-terms">{item.vocabulary.map((term) => <span key={term}>{term}</span>)}</div><div className="question-anchors"><small>ANCHORS</small>{item.anchors.map((anchor) => <a key={anchor.label} href={anchor.href} target="_blank" rel="noreferrer">{anchor.label} ↗</a>)}</div></article>)}</div>
      <div className="discipline-heading"><p className="eyebrow">DOMAIN VOCABULARY MAP</p><h2>Same world, different verbs.</h2><p>The boundaries overlap, but each community tends to optimize a different notion of evidence and fidelity.</p></div>
      <div className="discipline-grid">{communityLenses.map((lens) => <article className={`discipline-card discipline-${lens.community.toLowerCase().replace(' ', '-')}`} key={lens.community}><header><span>{lens.community}</span><strong>{lens.asks}</strong></header><div className="discipline-terms">{lens.terms.map((term) => <span key={term}>{term}</span>)}</div><blockquote>{lens.distinction}</blockquote><nav aria-label={`${lens.community} references`}>{lens.refs.map((ref) => <a href={ref.href} target="_blank" rel="noreferrer" key={ref.label}>{ref.label} ↗</a>)}</nav></article>)}</div>
    </section>
    </details>

    <details className="foundation-module" id="method"><summary><span>10 · METHODOLOGY</span><strong>How this tracker compares claims</strong><p>Historical baselines, units of comparison, evidence levels, metrics, and scope boundaries.</p><i>＋</i></summary>
    <section className="method-section">
      <div><p className="eyebrow">METHODOLOGY</p><h2>Compare assumptions, not just outcomes.</h2></div>
      <div className="method-schema" aria-label="Retargeting comparison schema"><span>Human / real evidence</span><b>→</b><span>Correspondence target</span><b>→</b><span>Constraints &amp; priors</span><b>→</b><span>Feasibility mechanism</span><b>→</b><span>Robot / simulator output</span><b>→</b><span>Evaluation evidence</span></div>
      <div className="method-grid"><article><span>01</span><h3>Historical baseline</h3><p>We do not label observation-to-robot transfer as new by default. Claims are situated against constraint-based retargeting, imitation learning, movement primitives, and learning from demonstration.</p></article><article><span>02</span><h3>Unit of comparison</h3><p>A pipeline is decomposed by input, representation, preserved invariants, robot constraints, feasibility method, output, and evidence.</p></article><article><span>03</span><h3>Evidence ladder</h3><p>We distinguish a paper claim, a visual demonstration, released code, reproducible assets, simulation evaluation, and physical-robot validation.</p></article><article><span>04</span><h3>No universal score</h3><p>Pose error, contact fidelity, naturalness, task success, robustness, and sim–real correlation remain separate metrics tied to their protocol.</p></article></div>
      <div className="method-boundary"><strong>Scope boundary</strong><p>The tracker covers both <em>retargeting</em>—adapting motion or task structure across embodiments—and <em>real-to-sim</em>—recovering reusable scene, appearance, or physics state from real observations. They overlap, but neither is a synonym for the other.</p></div>
    </section>
    </details>
    <SiteFooter />
  </main>;
}
